SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PKG_SYSTEM004@INT_LIST](
@A_PLANT			VARCHAR(50),
@A_USER_ID			VARCHAR(50),
@A_DEPARTMENT		VARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
DECLARE @V_MASTER_FLAG VARCHAR(1);
BEGIN TRY
SET @V_MASTER_FLAG = (SELECT T1.MASTER_FLAG FROM ESYSMSTUSR T1 WHERE T1.USER_ID = @A_USER_ID)
IF(@V_MASTER_FLAG = 'Y')
BEGIN	
		SELECT T.USERROLE AS USERROLE,
               T.USERROLE_NAME AS USERROLE_NAME
        FROM ESYSMSTROL T
        WHERE T.PLANT = @A_PLANT
        ORDER BY T.USERROLE ASC;

		SELECT 'N' AS USEFLAG,
               '' AS MENUNAME,
               '' AS MENUSEQ,
               '' AS UPRSEQ,
               '' AS FORMROLE
		WHERE @@ROWCOUNT < 0
END
ELSE
BEGIN
		SELECT T.USERROLE AS USERROLE,
               T.USERROLE_NAME AS USERROLE_NAME
        FROM ESYSMSTROL T
        WHERE T.PLANT = @A_PLANT
		AND T.USERROLE <> 'ROLE_ADMIN'
        ORDER BY T.USERROLE ASC;

		SELECT 'N' AS USEFLAG,
               '' AS MENUNAME,
               '' AS MENUSEQ,
               '' AS UPRSEQ,
               '' AS FORMROLE
		WHERE @@ROWCOUNT < 0
END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH








GO