SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP@INIT_PUT](
@A_DEPARTMENT		NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
	
	   SET NOCOUNT OFF;  
		BEGIN
			SELECT VENDER_ID, NAME FROM EWIP_VENDER
			SELECT CODE, NAME FROM EWIP_UNITS
			SELECT ID, COST_CTR FROM EWIP_COST_CTR 
			SELECT ID, GL_ACCOUNT FROM EWIP_GL_ACCOUNT
			SELECT CODE,NAME FROM EWIP_SPAREPART_TYPE WHERE DEPT_CODE = @A_DEPARTMENT
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH

GO