SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PO@GET_MRP_BY_POID](
@A_PO_ID     NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			SELECT OPR.PO_ID,OPR.[PR_CODE],PR.MRP_CODE,PRD.SPAREPART_CODE,ME.CODE_MERGED,SP.NAME_VI,SP.NAME_KR,PRD.QUANTITY_NEED_BUY,PRD.UNIT,PRD.PRICE_US,PRD.PRICE_VN,PRD.DATE_NEED_FINISH,PRD.DEPT_CODE,OPR.STATUS
			FROM [dbo].[EWIP_ORDER_PR] OPR
			INNER JOIN [dbo].[EWIP_PURCHASE_REQUEST] PR ON OPR.PR_CODE = PR.PR_CODE
			INNER JOIN [dbo].[EWIP_PURCHASE_REQUEST_DETAIL] PRD ON PRD.PR_CODE = OPR.PR_CODE
			INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON SP.CODE = PRD.SPAREPART_CODE AND SP.SP_DEPT_CODE = PRD.DEPT_CODE
			LEFT JOIN [dbo].[EWIP_MERGE_SPAREPART_CODE] ME ON ME.SPARE_PART_CODE = SP.CODE AND ME.DEPT_CODE = SP.SP_DEPT_CODE
			WHERE [PO_ID] = @A_PO_ID

       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO