SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_BOM_SPAREPART@GET](
@A_DEPARTMENT		NVARCHAR(50),
@A_SPARE_PART_CODE  NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			
			SELECT SP.CODE,SP.NAME_VI,SP.NAME_KR,SU.RATE as QUANTITY_IN_PACK,SU.UNIT_CODE_MIN AS UNIT,BOM.WORKING_DAY_NUMBER,BOM.WORKING_LINE_NUMBER,BOM.WORKING_A_LINE,BOM.[WORKING_A_LINE_PACK],BOM.WORKING_A_MONTH,BOM.RATE,BOM.FROM_TIME,BOM.TO_TIME
			FROM [dbo].[EWIP_SPARE_PART] SP
			INNER JOIN [dbo].[EWIP_SPARE_PART_DEPT] SD ON SP.CODE = SD.SPARE_PART_CODE AND SD.DEPT_CODE =SP.SP_DEPT_CODE
			INNER JOIN [dbo].[EWIP_SPAREPART_UNIT] SU ON SP.CODE = SU.SPARE_PART_CODE AND SU.DEPT_CODE = SP.SP_DEPT_CODE AND SU.UNIT_CODE = 'PACK'
			LEFT JOIN [dbo].[EWIP_BOM] BOM ON SP.CODE = BOM.SPARE_PART_CODE AND BOM.DEPT_CODE = SP.SP_DEPT_CODE
			WHERE SP.CODE =@A_SPARE_PART_CODE AND SP.SP_DEPT_CODE = @A_DEPARTMENT

			SELECT UNIT_CODE AS CODE,UNIT_CODE AS [NAME] , sp.IMAGE  
			FROM [dbo].[EWIP_SPAREPART_UNIT] uni
			INNER JOIN [dbo].[EWIP_SPARE_PART] sp ON sp.CODE = uni.SPARE_PART_CODE AND SP.SP_DEPT_CODE = uni.DEPT_CODE
			WHERE SPARE_PART_CODE = @A_SPARE_PART_CODE AND DEPT_CODE = @A_DEPARTMENT
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO