SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_MRP_LIST@DELETE](
@A_DEPARTMENT		NVARCHAR(50),
@A_MRP_CODE         NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN

			DECLARE @CHECK nvarchar(50)
		    -- MRP-20210728-001
		   
		  DELETE [dbo].[EWIP_MRP_LIST]
		  WHERE DEPT_CODE = @A_DEPARTMENT AND MRP_CODE = @A_MRP_CODE

		  DELETE [dbo].[EWIP_PURCHASE_REQUEST]
		  WHERE MRP_CODE = @A_MRP_CODE AND DEPT_CODE = @A_DEPARTMENT

		  DELETE [dbo].[EWIP_PURCHASE_REQUEST_DETAIL]
		  WHERE MRP_CODE = @A_MRP_CODE AND DEPT_CODE =@A_DEPARTMENT

		  UPDATE [dbo].[EWIP_MRP]
		  SET [MRP_CODE] = NULL
		  WHERE DEPT_CODE = @A_DEPARTMENT AND MRP_CODE = @A_MRP_CODE

       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO