SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP_INVENTORY@REPORT_BY_SPAREPART_LOCATION](
@A_DEPARTMENT		NVARCHAR(50),
@A_STOCK_CODE       NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  

			SELECT sl.SPARE_PART_CODE,sp.NAME_VI,sl.CONDITION_CODE,TIME_IN, 
			     (CASE [EXPIRED_DATE] WHEN '2199-01-01' THEN NULL
				 ELSE [EXPIRED_DATE]
				 END) AS [EXPIRED_DATE],CAST(GETDATE() as date) as INVENTORY_ASSETS_TIME,sl.UNIT_ID as UNIT,SL.LOCATION_CODE AS LOCATION,SUM(sl.QUANTITY) AS QUANTITY, '0' as QUANTITY_REAL, '' AS DIFF
			FROM [dbo].[EWIP_SPAREPART_LOCATION] sl
			INNER join [dbo].[EWIP_SPARE_PART] sp ON sl.DEPT_CODE = sp.SP_DEPT_CODE AND sl.SPARE_PART_CODE = SP.CODE
			WHERE SL.STOCK_CODE = @A_STOCK_CODE AND SL.DEPT_CODE = @A_DEPARTMENT
			GROUP BY sl.DEPT_CODE,sl.STOCK_CODE,sl.SPARE_PART_CODE,SL.LOCATION_CODE,sp.NAME_VI,sl.UNIT_ID,sl.CONDITION_CODE,TIME_IN,[EXPIRED_DATE]
			ORDER BY SL.LOCATION_CODE
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO