SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_LOCATION_SPAREPART@DELETE](
@A_STT        INT,
@A_SPARE_PART_CODE NVARCHAR(50),
@A_LOCATION        NVARCHAR(50),
@A_CONDITION       VARCHAR(50),
@A_DEPART_MENT     VARCHAR(50),
@A_STOCK           VARCHAR(50),
@A_UNIT            VARCHAR(20),
@A_EXPIRED_DATE    NVARCHAR(50),
@A_TIME_IN         NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  

			DECLARE @CHECK int;
			DECLARE @CHECK1 int;
			DECLARE @STT INT;

			SELECT @CHECK = COUNT(*) FROM [EWIP_SPAREPART_LOCATION] WHERE ID = @A_STT
			SELECT @CHECK1 = COUNT(*) FROM [EWIP_SPAREPART_LOCATION] 
			WHERE LOCATION_CODE = @A_LOCATION 
					AND SPARE_PART_CODE = @A_SPARE_PART_CODE
					AND UNIT_ID = @A_UNIT 
					AND CONDITION_CODE = @A_CONDITION
			        AND DEPT_CODE =@A_DEPART_MENT 
					AND STOCK_CODE = @A_STOCK
					AND [EXPIRED_DATE] =  CAST(@A_EXPIRED_DATE AS date)
					AND TIME_IN = CAST(@A_TIME_IN AS date)

			IF @CHECK > 0 
				DELETE FROM [dbo].[EWIP_SPAREPART_LOCATION] 
				WHERE ID = @A_STT
			ELSE
			   IF @CHECK1 > 0
					 BEGIN
						SELECT @STT = ID FROM [EWIP_SPAREPART_LOCATION] 
						WHERE LOCATION_CODE = @A_LOCATION 
								AND SPARE_PART_CODE = @A_SPARE_PART_CODE 
								AND UNIT_ID = @A_UNIT 
								AND CONDITION_CODE = @A_CONDITION
								AND DEPT_CODE =@A_DEPART_MENT 
								AND STOCK_CODE = @A_STOCK
								AND [EXPIRED_DATE] =  CAST(@A_EXPIRED_DATE AS date)
								AND TIME_IN = CAST(@A_TIME_IN AS date)

						IF @STT  <> '' AND @STT IS NOT NULL
							DELETE FROM [dbo].[EWIP_SPAREPART_LOCATION] 
							WHERE ID = @STT
					END			
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO