SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PKG_SYSTEM008@INT_LIST](
@A_PLANT			VARCHAR(50),
@A_USER_ID			VARCHAR(50),
@A_DEPARTMENT		VARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

DECLARE @V_MASTER_FLAG VARCHAR(1);

BEGIN TRY
SET @V_MASTER_FLAG = (SELECT T1.MASTER_FLAG FROM ESYSMSTUSR T1 WHERE T1.USER_ID = @A_USER_ID AND T1.DEPARTMENT = @A_DEPARTMENT)
IF(@V_MASTER_FLAG = 'Y')
BEGIN	
		SELECT T1.USER_ID,
			   T1.USER_NAME,
			   T1.DEPARTMENT
			   --T2.COMMNAME AS DEPT_NAME
		FROM ESYSMSTUSR T1
			 --LEFT OUTER JOIN ESYSMSTCOD T2 ON T2.PLANT = T1.PLANT AND T2.COMMGRP = 'USER_DEPT'-- AND T2.COMMCODE = T1.DEPT_CODE
		WHERE T1.PLANT = @A_PLANT
		AND T1.USEFLAG = 'Y'
		--AND T1.DEPARTMENT = @A_DEPARTMENT
		ORDER BY T1.USER_NAME;

		SELECT 'N' AS SEL,
			   T1.USERROLE AS USERROLE,
               T1.USERROLE_NAME AS USERROLE_NAME
	    FROM ESYSMSTROL T1
		WHERE T1.PLANT = @A_PLANT
		AND T1.USEFLAG = 'Y'
		ORDER BY T1.USERROLE_NAME;
END
ELSE
BEGIN
		SELECT T1.USER_ID,
			   T1.USER_NAME
			   --t1.DEPT_CODE,
			   --T2.COMMNAME AS DEPT_NAME
		FROM ESYSMSTUSR T1
			 --LEFT OUTER JOIN ESYSMSTCOD T2 ON T2.PLANT = T1.PLANT AND T2.COMMGRP = 'USER_DEPT'-- AND T2.COMMCODE = T1.DEPT_CODE
		WHERE T1.PLANT = @A_PLANT
		AND T1.USEFLAG = 'Y'
		AND T1.MASTER_FLAG IS NULL
		AND T1.DEPARTMENT = @A_DEPARTMENT
		ORDER BY T1.USER_NAME;

		SELECT 'N' AS SEL,
			   T1.USERROLE AS USERROLE,
               T1.USERROLE_NAME AS USERROLE_NAME
	    FROM ESYSMSTROL T1
		WHERE T1.PLANT = @A_PLANT
		AND T1.USEFLAG = 'Y'
		AND T1.USERROLE <> 'ROLE_ADMIN'
		AND T1.DEPARTMENT = @A_DEPARTMENT
		ORDER BY T1.USERROLE_NAME;
END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH







GO