SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PKG_LOGDAT001@GET_LIST](
@A_DEPARTMENT		VARCHAR(50),
@A_FROM_DATE		VARCHAR(50),
@A_TO_DATE			VARCHAR(50),
@A_USER_ID			VARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
	
	if(@A_USER_ID = '') SET @A_USER_ID = NULL;

	SELECT T1.USER_ID,
           T2.USER_NAME AS USER_NAME,
           dbo.[CHAR_TO_DATE](T1.ACCESS_TIME) AS ACCESS_TIME,
           T1.ACCESS_IP,
           T1.ACCESS_PC
    FROM ESYSLOGLGN T1,
            ESYSMSTUSR T2
    WHERE T1.DEPARTMENT = @A_DEPARTMENT
    AND T2.USER_ID = T1.USER_ID
    AND T1.USER_ID = ISNULL(@A_USER_ID, T1.USER_ID)
    AND T1.ACCESS_TIME BETWEEN @A_FROM_DATE+'000000' AND @A_TO_DATE+'235959'
    ORDER BY T1.ACCESS_TIME;

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH








GO