SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PO@PUT_PO](
@A_DATA             [dbo].[PO_DETAIL_TYPE] READONLY,
@A_LIST_PR_CODE     NVARCHAR(MAX),
@A_PO_ID_TEMP       NVARCHAR(50),
@A_PO_ID            NVARCHAR(50),
@A_DATE_NEED_FINISH  NVARCHAR(50),
@A_DATE_CREATE_PO   NVARCHAR(50),
@A_TITLE            NVARCHAR(50),
@A_USER             NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			
			BEGIN TRAN
			DELETE FROM [dbo].[EWIP_ORDER_DETAIL]
			WHERE [PO_ID_TEMP] = @A_PO_ID_TEMP OR PO_ID_TEMP IS NULL

			INSERT INTO [dbo].[EWIP_ORDER_DETAIL]
			SELECT 
					[PO_ID],
					[PO_CREATE],
					[BKGRP],
					[KUNNR],
					[PSTYP],
					[SPARE_PART_CODE],
					[WERKS],
					[LGORT],
					[NETPR_PRICE],
					[PER],
					[WAERS],
					[MWSKZ],
					[KNTTP],
					[MATKL],
					[POSID],
					[DEPT_CODE],
					[PO_QTY],
					[UNIT],
					[PR_CODE],
					[PO_ID_TEMP],
					[TXZ01_DESCRIPTION],
					[LIFNR],
					[EINDT_DELIVERY_DATE],
					[SAKNR_GL_ACCOUNT],
					[KOSTL_COST_CENTER]
			FROM @A_DATA
			   
            DECLARE @CHECK INT 
			SELECT @CHECK = COUNT(*) 
			FROM [dbo].[EWIP_ORDER]
			WHERE [PO_ID_TEMP] = @A_PO_ID_TEMP

		    DECLARE @STATUS_UPDATE NVARCHAR(50) = 'PUR_RECEIPT';
		    IF @A_PO_ID IS NOT NULL AND @A_PO_ID != ''
		      BEGIN
		        SET @STATUS_UPDATE = 'ORDER'
		      END

			IF @CHECK > 0
			  BEGIN
					UPDATE [dbo].[EWIP_ORDER]
					SET [PO_ID] = @A_PO_ID,[DATE_ORERED] = GETDATE(),[USER_ID] = @A_USER,[UPDATED_DATE] = GETDATE(),[TITLE] = @A_TITLE,[DATE_NEED_FINISH] = CAST(@A_DATE_NEED_FINISH AS date),STATUS = @STATUS_UPDATE
					WHERE [PO_ID_TEMP] = @A_PO_ID_TEMP
			  END
			ELSE 
			  BEGIN
					INSERT INTO [dbo].[EWIP_ORDER]
					VALUES(@A_PO_ID,GETDATE(),GETDATE(),@STATUS_UPDATE,@A_USER,GETDATE(),@A_TITLE,NULL,CAST(@A_DATE_NEED_FINISH AS date),@A_PO_ID_TEMP)
			  END

			  UPDATE [dbo].[EWIP_ORDER_PR]
			  SET [PO_ID] = @A_PO_ID,[PO_ID_TEMP] = @A_PO_ID_TEMP, STATUS = (CASE WHEN @A_PO_ID IS NOT NULL AND @A_PO_ID != '' THEN 'ORDER' ELSE STATUS END)
			  WHERE [PR_CODE] IN (SELECT TRIM(VALUE) FROM STRING_SPLIT(@A_LIST_PR_CODE,'^'))

			UPDATE [dbo].[EWIP_PURCHASE_REQUEST]
			SET [PR_STATUS] = @STATUS_UPDATE ,USER_UPDATE = @A_USER,DATE_UPDATE = GETDATE()
			WHERE [PR_CODE] IN (SELECT TRIM(VALUE) FROM STRING_SPLIT(@A_LIST_PR_CODE,'^'))

			UPDATE [dbo].[EWIP_PURCHASE_REQUEST_DETAIL]
			SET [STATUS] =  @STATUS_UPDATE,USER_UPDATE = @A_USER,DATE_UPDATE = GETDATE()
			WHERE [MRP_CODE] IN (SELECT [MRP_CODE] FROM [dbo].[EWIP_PURCHASE_REQUEST] WHERE [PR_CODE] IN (SELECT TRIM(VALUE) FROM STRING_SPLIT(@A_LIST_PR_CODE,'^')))

			UPDATE [dbo].[EWIP_MRP]
			SET STATUS = @STATUS_UPDATE,USER_UPDATE = @A_USER,DATE_UPDATE = GETDATE()
			WHERE [MRP_CODE] IN (SELECT [MRP_CODE] FROM [dbo].[EWIP_PURCHASE_REQUEST] WHERE [PR_CODE] IN (SELECT TRIM(VALUE) FROM STRING_SPLIT(@A_LIST_PR_CODE,'^')))
			
			UPDATE [dbo].[EWIP_MRP_LIST]
			SET STATUS = @STATUS_UPDATE,USER_UPDATE = @A_USER,DATE_UPDATE = GETDATE()
			WHERE [MRP_CODE] IN (SELECT [MRP_CODE] FROM [dbo].[EWIP_PURCHASE_REQUEST] WHERE [PR_CODE] IN (SELECT TRIM(VALUE) FROM STRING_SPLIT(@A_LIST_PR_CODE,'^')))
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
	COMMIT TRAN
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
  ROLLBACK TRAN
END CATCH
GO