SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PO@MERGE_CODE](
@A_PR_LIST  NVARCHAR(MAX),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			
			SELECT 
				SP.CODE as [SPARE_PART_CODE],
				ME.[CODE_MERGED],
				SP.NAME_VI,
				SP.NAME_KR,
				OPR.DEPT_CODE
				FROM [dbo].[EWIP_ORDER_PR] OPR
				INNER JOIN [dbo].[EWIP_PURCHASE_REQUEST] PR ON OPR.PR_CODE = PR.PR_CODE AND OPR.DEPT_CODE = PR.DEPT_CODE
				INNER JOIN [dbo].[EWIP_PURCHASE_REQUEST_DETAIL] PRD ON PR.PR_CODE = PRD.PR_CODE AND PR.MRP_CODE = PRD.MRP_CODE AND PR.DEPT_CODE = PRD.DEPT_CODE
				INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON SP.[SP_DEPT_CODE] = PR.DEPT_CODE AND SP.CODE = PRD.SPAREPART_CODE
				INNER JOIN [dbo].[EWIP_SPARE_PART_DEPT] SPD ON SP.CODE = SPD.SPARE_PART_CODE AND SP.[SP_DEPT_CODE] = SPD.DEPT_CODE
				LEFT JOIN [dbo].[EWIP_MERGE_SPAREPART_CODE] ME ON SP.SP_DEPT_CODE = ME.[DEPT_CODE] AND ME.[SPARE_PART_CODE] = SP.CODE
			WHERE OPR.PR_CODE IN (SELECT VALUE FROM STRING_SPLIT(@A_PR_LIST,'^'))

       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO