SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PKG_SYSTEM008@PUT_ITEM](
@A_PLANT			VARCHAR(50),
@A_XML				XML,
@A_USER_ID			VARCHAR(50),
@A_TRAN_USER_ID		VARCHAR(30),
@A_DEPARTMENT		VARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

DECLARE	@V_TRAN_TIME	VARCHAR(14);

DECLARE @V_USERROLE		VARCHAR(30);
DECLARE @V_COUNT		INT;


BEGIN TRY
	SET @V_TRAN_TIME = dbo.FUN_CURR_TIME();

	BEGIN TRAN

		DELETE
		FROM ESYSMSTURO
		WHERE PLANT = @A_PLANT
		AND USER_ID = @A_USER_ID
		AND DEPARTMENT = @A_DEPARTMENT
		;

	
		DECLARE R_REC cursor for
		SELECT DISTINCT
			'USERROLE' = x.v.value('USERROLE[1]', 'VARCHAR(30)')
		FROM @A_XML.nodes('DocumentElement/Table') x(v);

		OPEN R_REC
		FETCH NEXT FROM R_REC into @V_USERROLE;

		SET @V_COUNT = 0; 

		WHILE @@FETCH_STATUS = 0
			BEGIN
				SET @V_COUNT = @V_COUNT + 1;

				INSERT INTO ESYSMSTURO (
					PLANT,
					DEPARTMENT,
					USER_ID,
					ITEM_NO,
					USERROLE,
					CREATE_TIME,
					CREATE_USER
				) VALUES (
					@A_PLANT,
					@A_DEPARTMENT,
					@A_USER_ID,
					@V_COUNT,
					@V_USERROLE,
					@V_TRAN_TIME,
					@A_TRAN_USER_ID
				);
				FETCH NEXT FROM R_REC into @V_USERROLE;
			END
		CLOSE R_REC
	COMMIT TRAN;

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_001';
END TRY
BEGIN CATCH

	rollback tran;
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH








GO