SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_COMM@GET_LOGIN](
@A_PLANT VARCHAR(50),
@A_USER_ID VARCHAR(50),
@A_DEPARTMENT VARCHAR(50),
@N_RETURN  int			 OUTPUT,
@V_RETURN  NVARCHAR(4000) OUTPUT
)
AS 
BEGIN TRY
	SELECT T1.PASSWORD AS PASSWORD,
			T1.USER_ID AS USER_ID,
			T1.USER_NAME AS USER_NAME
	FROM ESYSMSTUSR T1
	WHERE T1.PLANT = @A_PLANT
	AND T1.USER_ID = @A_USER_ID
	AND T1.DEPARTMENT = @A_DEPARTMENT
	AND T1.USEFLAG = 'Y';
  
	SELECT T1.USERROLE,
		   T2.USERROLE_NAME
	FROM ESYSMSTURO T1,
		 ESYSMSTROL T2
	WHERE T1.PLANT = @A_PLANT
	AND T1.USER_ID = @A_USER_ID
	AND T2.PLANT = T1.PLANT
	AND T2.USERROLE = T1.USERROLE;

  SET @N_RETURN = 0;
  SET @V_RETURN = 'MSG_COM_004';
END TRY
BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH


GO