SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_LOCATION_SPAREPART@GET_SINGLE](
@A_STT              INT,
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			SELECT [LOCATION_CODE] AS LOCATION,[SPARE_PART_CODE],[CONDITION_CODE],QUANTITY,UNIT_ID AS UNIT,STOCK_CODE AS KHO,[EXPIRED_DATE],TIME_IN
			FROM [dbo].[EWIP_SPAREPART_LOCATION] 
			WHERE ID = @A_STT
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO