SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_INVOICE@IMPORT](
@A_USER   NVARCHAR(50),
@A_DATA				[dbo].[INVOICE_TYPE] READONLY,	
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			INSERT INTO [dbo].[EWIP_INVOICES]
			SELECT 
					 [INVOICE_DOC_NO]
					,[CONFIRM]
					,[POSTING]
					,[PO_NO]
					,[BENEFICIARY]
					,[BENEFICIARY_NAME]
					,[BASELINE_DATE]
					,[ACCOUNTING_DOC]
					,[DOC_NO_OF_INVOICE_DOC_NO]
					,[MATERIAL_ID]
					,[MATERIAL_DESC]
					,[EXCHANGE_RATE]
					,[AMOUNT_LOCAL]
					,[PURCH_ORG]
					,[POSTING_DATE]
					,[PURCH_GRP]
					,[BL_NO_HOUSE]
					,[DOC_DATE]
					,[QUANTITY]
					,[UNIT]
					,[INVOICE_AMOUNT]
					,[CURRENCY]
					,[BL_DOC_NO]
					,[LC_NO]
					,[IMPORT_REQUEST_NO]
					,[COMMERCIAL_INVOICE_NO]
					,[TRANSACTION]
					,[CREATE_BY]
					,@A_USER AS [IMPORT_BY]
					,SYSDATETIME() AS [IMPORT_DATE]
			FROM @A_DATA
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO