SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PO@MERGED_CODE_PUT](
@A_DATA     [dbo].[EWIP_MERGE_SPAREPART_CODE_TYPE] READONLY,
@A_USER           NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			
			MERGE [dbo].[EWIP_MERGE_SPAREPART_CODE] AS TARGET
			USING @A_DATA AS SOURCE
			ON (
					TARGET.[SPARE_PART_CODE] = SOURCE.SPARE_PART_CODE AND 
					TARGET.[DEPT_CODE] = SOURCE.DEPT_CODE
				)
			WHEN MATCHED 
			    THEN UPDATE SET TARGET.[CODE_MERGED]=SOURCE.CODE_MERGED ,TARGET.[USER_CREATE] = @A_USER,TARGET.[DATE_CREATE] = SYSDATETIME()
			WHEN NOT MATCHED BY TARGET
			    THEN INSERT([SPARE_PART_CODE],[CODE_MERGED],[DEPT_CODE],[USER_CREATE],[DATE_CREATE])
				     VALUES(SOURCE.SPARE_PART_CODE,SOURCE.CODE_MERGED,SOURCE.DEPT_CODE,@A_USER,SYSDATETIME());
			
        END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO