SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PR@INIT_LIST](
@A_DEPARTMENT		NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			SELECT [PR_CODE],[MRP_CODE],[TOTAL_VALUE],[TOTAL_VALUE_US],[DATE_CREATE],[DATE_NEED_FINISH],[DATE_END_ACTUAL],[USER_CREATE],[USER_UPDATE],[DATE_UPDATE],[PR_STATUS]
			FROM [dbo].[EWIP_PURCHASE_REQUEST]
			WHERE DEPT_CODE = @A_DEPARTMENT
			ORDER BY [DATE_CREATE] DESC,[DATE_NEED_FINISH] ASC
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO