SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PO@GET_DETAIL_PO](
@A_PO_ID_TEMP NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			
			SELECT 
			FORMAT(PO_CREATE, 'yyyyMMdd') as PO_CREATE,
			ODT.VENDOR,
			ODT.KUNNR,
			ODT.BKGRP,
			ODT.PSTYP,
			(CASE WHEN ME.CODE_MERGED IS NOT NULL AND ME.CODE_MERGED != '' THEN ME.CODE_MERGED ELSE ODT.SPARE_PART_CODE END) AS SPARE_PART_CODE,
			ODT.TXZ01_DESCRIPTION,
			ODT.WERKS,
			ODT.LGORT,
			ODT.PO_QTY,
			ODT.UNIT,
			ODT.NETPR,
			ODT.PER,
			ODT.WAERS,
			ODT.MWSKZ,
			ODT.DELIVERY_DATE,
			ODT.KNTTP,
			ODT.MATKL,
			ODT.POSID,
			ODT.GL_ACCOUNT,
			ODT.COST_CENTER,
			ODT.DEPT_CODE
			FROM [dbo].[EWIP_ORDER] OD
			INNER JOIN [dbo].[EWIP_ORDER_DETAIL] ODT ON OD.PO_ID_TEMP = ODT.PO_ID_TEMP
			LEFT JOIN [dbo].[EWIP_MERGE_SPAREPART_CODE] ME ON ME.SPARE_PART_CODE = ODT.SPARE_PART_CODE AND ME.DEPT_CODE = ODT.DEPT_CODE
			WHERE OD.PO_ID_TEMP = @A_PO_ID_TEMP


			SELECT OD.[SPARE_PART_CODE] AS SPAREPART_CODE,OPR.PR_CODE,OPR.DEPT_CODE
			FROM [dbo].[EWIP_ORDER_PR] OPR
			INNER JOIN  [dbo].[EWIP_ORDER_DETAIL] OD ON OPR.PR_CODE = OD.PR_CODE
			WHERE OPR.PO_ID_TEMP = @A_PO_ID_TEMP

			SELECT [TITLE] FROM [dbo].[EWIP_ORDER] WHERE [PO_ID_TEMP] = @A_PO_ID_TEMP
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH

GO