SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PR@GET_ALL_DEPT](
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			
			SELECT PR.[ID],PR.[PR_CODE],[MRP_CODE],[TOTAL_VALUE],[TOTAL_VALUE_US],PR.[DATE_CREATE],PR.[DATE_NEED_FINISH],PR.[DEPT_CODE],[PR_STATUS] as STATUS
			FROM [dbo].[EWIP_PURCHASE_REQUEST] PR
			LEFT JOIN [dbo].[EWIP_ORDER_PR] OPR ON PR.PR_CODE = OPR.PR_CODE 
			WHERE [PR_STATUS] IN('ACCEPT','NEW','WAIT_ACCEPT') AND (OPR.PO_ID IS NULL or OPR.PO_ID = '')
			ORDER BY PR.[DATE_CREATE] DESC

			SELECT distinct [PO_ID]
			FROM [dbo].[EWIP_ORDER]
			WHERE STATUS != 'COMPLETE' AND STATUS != 'CANCEL' AND PO_ID is not null and PO_ID != ''

			SELECT OPR.[ID],OPR.[PR_CODE],PR.MRP_CODE,PR.TOTAL_VALUE,PR.TOTAL_VALUE_US,PR.[DATE_CREATE],PR.[DATE_NEED_FINISH],PR.[DEPT_CODE],OPR.STATUS
			FROM [dbo].[EWIP_ORDER_PR] OPR
			INNER JOIN [dbo].[EWIP_PURCHASE_REQUEST] PR ON OPR.PR_CODE = PR.PR_CODE
			WHERE ([PO_ID] IS NULL OR [PO_ID] = '') AND OPR.STATUS = 'PUR_RECEIPT'
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO