SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP_INVENTORY@GET_BY_SPARE_CODE](
@A_DEPARTMENT		NVARCHAR(50),
@A_STOCK            NVARCHAR(50),
@A_SPARE_PART_CODE  NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			SELECT inv.[QUANTITY],inv.QUANTITY_REAL,UNIT_ID AS UNIT,[IMAGE]
			FROM [dbo].[EWIP_SPAREPART_INVENTORY] inv
			INNER JOIN [dbo].[EWIP_SPARE_PART] sp ON inv.SPARE_PART_CODE = sp.CODE AND sp.SP_DEPT_CODE = inv.DEPT_CODE
			WHERE inv.DEPT_CODE = @A_DEPARTMENT AND inv.STOCK_CODE = @A_STOCK AND inv.SPARE_PART_CODE = @A_SPARE_PART_CODE

			SELECT MIN_STOCK,[UNIT_CODE] AS UNIT,[IMAGE],[RATE_ALARM]
			FROM [dbo].[EWIP_SETUP_MINSTOCK]
			INNER JOIN [dbo].[EWIP_SPARE_PART] sp ON SPARE_PART_CODE = sp.CODE AND sp.SP_DEPT_CODE = DEPT_CODE
			WHERE [SPARE_PART_CODE] = @A_SPARE_PART_CODE AND [STOCK_CODE] = @A_STOCK AND DEPT_CODE = @A_DEPARTMENT

		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH

GO