SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP@GET_MAX_AUTO_CODE](
@A_TYPE             NVARCHAR(50),
@A_DEPARTMENT		NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			SELECT TOP 1 CODE,CAST(SUBSTRING(CODE, 4, 4) AS int) AS STT
			FROM EWIP_SPARE_PART 
			WHERE CODE LIKE @A_TYPE+'%' AND [SP_DEPT_CODE] = @A_DEPARTMENT
			ORDER BY STT DESC;
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO