SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
create PROC [dbo].[PKG_BUSINESS_INVOICE@GET_ALL](
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			SELECT * FROM [dbo].[EWIP_INVOICES]
			ORDER BY [IMPORT_DATE] DESC
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO