SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PKG_LOGDAT002@POP_GET_LIST](
@A_PLANT			VARCHAR(50),
@A_FROM_DATE		VARCHAR(50),
@A_TO_DATE			VARCHAR(50),
@A_FORM_CODE		VARCHAR(50),
@A_USER_ID			VARCHAR(50),
@A_LANG				VARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY

    SELECT T1.USER_ID,
           T1.FORM_CODE,
           (CASE WHEN @A_LANG = 'KOR' THEN T2.KOR
					  WHEN @A_LANG = 'VTN' THEN T2.VTN END)
			 AS FORMNAME,
           dbo.[CHAR_TO_DATE](T1.ACCESS_TIME) AS LAST_ACCESS_TIME
    FROM ESYSLOGFOM T1,
         ESYSMSTGLA T2
    WHERE T1.PLANT = @A_PLANT
    AND T2.PLANT = T1.PLANT
    AND T2.GLSR = T1.FORM_CODE
    AND T1.USER_ID = @A_USER_ID
    AND T1.FORM_CODE = @A_FORM_CODE
    AND T1.ACCESS_TIME BETWEEN @A_FROM_DATE+'000000' AND @A_TO_DATE+'235959'
    ORDER BY T1.ACCESS_TIME;

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO