SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_ORDER_PR@PUT](
@A_USER NVARCHAR(50),
@A_PO_ID NVARCHAR(50),
@A_PR_CODE NVARCHAR(50),
@A_STATUS NVARCHAR(50),
@A_DATE_NEED_FINISH NVARCHAR(50),
@A_DEPT_CODE_PR NVARCHAR(50),
@A_PO_ID_TEMP  NVARCHAR(50),
@A_IS_DETACK NVARCHAR(20),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			
			BEGIN TRAN
			IF EXISTS(SELECT TOP 1 * FROM [dbo].[EWIP_ORDER_PR] WHERE PR_CODE = @A_PR_CODE AND DEPT_CODE = @A_DEPT_CODE_PR)
			    BEGIN
					UPDATE [dbo].[EWIP_ORDER_PR]
					SET [PO_ID] = @A_PO_ID,STATUS = @A_STATUS,[DATE_NEED_FINISH] = CAST(@A_DATE_NEED_FINISH AS date),DATE_UPDATE = GETDATE(),USER_UPDATE = @A_USER,PO_ID_TEMP = (CASE WHEN @A_IS_DETACK = 'True' then NULL ELSE @A_PO_ID_TEMP END)
					WHERE PR_CODE = @A_PR_CODE AND DEPT_CODE = @A_DEPT_CODE_PR
				END
			ELSE
			   BEGIN
					INSERT INTO [dbo].[EWIP_ORDER_PR]
					VALUES(@A_PO_ID,@A_PR_CODE,@A_STATUS,@A_DATE_NEED_FINISH,NULL,GETDATE(),GETDATE(),@A_USER,@A_USER,@A_DEPT_CODE_PR,@A_PO_ID_TEMP)
			   END

			   UPDATE [dbo].[EWIP_PURCHASE_REQUEST]
			   SET PR_STATUS = @A_STATUS,USER_UPDATE = @A_USER,DATE_UPDATE = GETDATE()
			   WHERE PR_CODE = @A_PR_CODE AND DEPT_CODE = @A_DEPT_CODE_PR

			   UPDATE [dbo].[EWIP_MRP_LIST]
			   SET STATUS = @A_STATUS,USER_UPDATE = @A_USER,DATE_UPDATE = GETDATE()
			   WHERE MRP_CODE IN (SELECT MRP_CODE FROM [dbo].[EWIP_PURCHASE_REQUEST] WHERE PR_CODE = @A_PR_CODE AND DEPT_CODE = @A_DEPT_CODE_PR)

			   UPDATE [dbo].[EWIP_MRP]
			   SET STATUS = @A_STATUS,USER_UPDATE = @A_USER,DATE_UPDATE = GETDATE()
			   WHERE MRP_CODE IN (SELECT MRP_CODE FROM [dbo].[EWIP_PURCHASE_REQUEST] WHERE PR_CODE = @A_PR_CODE AND DEPT_CODE = @A_DEPT_CODE_PR)

			   UPDATE [dbo].[EWIP_PURCHASE_REQUEST_DETAIL]
			   SET STATUS = @A_STATUS
			   WHERE MRP_CODE IN (SELECT MRP_CODE FROM [dbo].[EWIP_PURCHASE_REQUEST] WHERE PR_CODE = @A_PR_CODE AND DEPT_CODE = @A_DEPT_CODE_PR)
			   
			   IF EXISTS(SELECT * FROM [dbo].[EWIP_ORDER_DETAIL] WHERE PO_ID_TEMP = @A_PO_ID_TEMP AND PR_CODE =@A_PR_CODE)
			     BEGIN
						UPDATE [dbo].[EWIP_ORDER_DETAIL]
						SET PO_ID = @A_PO_ID,PO_ID_TEMP = (CASE WHEN @A_IS_DETACK = 'True' then NULL ELSE @A_PO_ID_TEMP END)
						WHERE PO_ID_TEMP = @A_PO_ID_TEMP AND PR_CODE =@A_PR_CODE
				 END
				ELSE
				    BEGIN
					   
					     DECLARE @WAERS NVARCHAR(50)
						 SELECT TOP 1 @WAERS = [WAERS] 
						 FROM [dbo].[EWIP_ORDER_DETAIL]
						 WHERE PO_ID_TEMP = @A_PO_ID_TEMP
					    
						 INSERT INTO [dbo].[EWIP_ORDER_DETAIL]
						 SELECT 
						        NULL,
								SYSDATETIME(),
								'' as [BKGRP],
								'' as KUNNR,
								'' as [PSTYP],
								PRD.SPAREPART_CODE as [SPARE_PART_CODE],
								'' AS [WERKS],
								'' AS [LGORT],
								(CASE WHEN @WAERS = 'VND' THEN PRD.PRICE_VN ELSE PRD.PRICE_US END) AS PRICE,
								1 AS PER,
								CASE WHEN @WAERS = 'VND' THEN 'VND' ELSE 'USD' END,
								'VZ' AS [MWSKZ],
								'K' as [KNTTP],
								'8000' as [MATKL],
								'' as POSID,
								PRD.DEPT_CODE,
								PRD.QUANTITY_NEED_BUY AS [PO_QTY],
								PRD.[UNIT],
								@A_PR_CODE,
								@A_PO_ID_TEMP,
								SP.NAME_KR +' '+ SP.[SPECIFICATIONS] AS TXZ01,
								PRD.VENDOR_ID,
								PRD.DATE_NEED_FINISH,
								SP.[GL_ACCOUNT],
								SPD.COST_CTR
								FROM [dbo].[EWIP_PURCHASE_REQUEST_DETAIL] PRD
								INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON SP.[SP_DEPT_CODE] = PRD.DEPT_CODE AND SP.CODE = PRD.SPAREPART_CODE
								INNER JOIN [dbo].[EWIP_SPARE_PART_DEPT] SPD ON SP.CODE = SPD.SPARE_PART_CODE AND SP.[SP_DEPT_CODE] = SPD.DEPT_CODE
								WHERE PRD.PR_CODE = @A_PR_CODE AND PRD.DEPT_CODE = @A_DEPT_CODE_PR
					END

       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
	COMMIT TRAN
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
  ROLLBACK TRAN
END CATCH
GO