SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_GOODS_RECEIPT_ISSUE@HISTORY_BY_CODE](
@A_DEPT_CODE NVARCHAR(50),
@A_STOCK_CODE NVARCHAR(50),
@A_SPARE_PART NVARCHAR(50),
@A_TIME_FROM NVARCHAR(50),
@A_TIME_TO NVARCHAR(50),
@N_RETURN	int				OUTPUT,
@V_RETURN	NVARCHAR(MAX)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
		 DECLARE @SQLStament nvarchar(max)

		 SET @SQLStament = N'
				SELECT HI.[SPARE_PART_CODE],HI.[QUANTITY],HI.[UNIT], SUBSTRING(OU.LOCATION,1,CHARINDEX(''_'',OU.LOCATION) - 1) AS LOCATION,HI.[DEPT_CODE],HI.[STOCK_CODE],HI.[DATE],[TIME_INPUT],cast(HI.[MONTH] as nvarchar) as THANG,cast(HI.[YEAR] as nvarchar) AS NAM,HI.[IN_OUT],HI.[STATUS] 
				FROM [dbo].[EWIP_HISTORY_INVENTORY] HI
				LEFT JOIN [dbo].[EWIP_INVENTORY_DELIVERY_RECEIVING] ON CODE_NO = HI.[STOCK_IN_OUT_CODE]
				LEFT JOIN [dbo].[EWIP_STOCK_OUT] OU ON HI.STOCK_IN_OUT_CODE = OU.STOCK_OUT_CODE AND HI.DEPT_CODE = OU.DEPT_CODE AND HI.SPARE_PART_CODE = OU.SPARE_PART_CODE
				LEFT JOIN [dbo].[EWIP_SP_STOCKIN] KIN ON  HI.STOCK_IN_OUT_CODE = KIN.STOCK_IN_CODE AND HI.SPARE_PART_CODE = KIN.SPARE_PART_CODE AND HI.DEPT_CODE = KIN.DEPT_CODE
				WHERE HI.DEPT_CODE = ''' + @A_DEPT_CODE + ''' AND HI.STOCK_CODE = ''' + @A_STOCK_CODE+''''

		IF @A_SPARE_PART <> '' 
		   BEGIN
				 SET @SQLStament += N' AND HI.SPARE_PART_CODE = ''' + @A_SPARE_PART + '''';
		   END

		IF @A_TIME_FROM <> '' 
		     SET @SQLStament += N' AND HI.[DATE] >= CAST(''' + @A_TIME_FROM + ''' AS date)'

		IF  @A_TIME_TO <> '' 
		     SET @SQLStament += N' AND HI.[DATE] <= CAST('''+@A_TIME_TO+''' AS date)'

			 SET @SQLStament += N' ORDER BY HI.[DATE] DESC,[TIME_INPUT] DESC'

		PRINT @SQLStament
		EXEC (@SQLStament)
	 END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';

END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH

GO