SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PRICE@PUT](
@A_DEPT_CODE  NVARCHAR(50),
@A_SPARE_PART_CODE NVARCHAR(50),
@A_IS_EDIT       NVARCHAR(50),
@A_PRICE_VN      NVARCHAR(50),
@A_PRICE_US      NVARCHAR(50),
@A_DATE          NVARCHAR(50),
@A_UNIT         NVARCHAR(50),
@A_ID           NVARCHAR(50),
@N_RETURN		 int   OUTPUT,
@V_RETURN		 NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			DECLARE @CHECK INT = 0
			
			IF @A_IS_EDIT = 'False'
			  BEGIN
					INSERT INTO [dbo].[EWIP_SPAREPART_PRICE]
					VALUES(@A_SPARE_PART_CODE,NULL,CAST(@A_PRICE_VN AS float),CAST(@A_PRICE_US AS float),@A_UNIT,@A_DEPT_CODE,CAST(@A_DATE AS date))
			   END
			ELSE
			    BEGIN
					  UPDATE [dbo].[EWIP_SPAREPART_PRICE]
					  SET [PRICE_VN] = @A_PRICE_VN,PRICE_US = @A_PRICE_US ,UNIT_CODE = @A_UNIT,[DATE] = CAST(@A_DATE AS date),SPARE_PART_CODE = @A_SPARE_PART_CODE
					  WHERE ID = @A_ID
				END
			
			DECLARE @CHECK1 INT = 0

			SELECT @CHECK1 = COUNT(*) 
			FROM [dbo].[EWIP_INVENTORY_BY_TIME]
			WHERE [SPARE_PART_CODE] = @A_SPARE_PART_CODE AND [DEPT_CODE]=@A_DEPT_CODE AND [MONTH] = MONTH(CAST(@A_DATE AS date)) AND [YEAR] = YEAR(CAST(@A_DATE AS date))

			IF @CHECK1 > 0
			   UPDATE [dbo].[EWIP_INVENTORY_BY_TIME]
			   SET [PRICE_VN] = @A_PRICE_VN/[dbo].[CONVERT_UNIT](@A_UNIT,[UNIT],SPARE_PART_CODE,@A_DEPT_CODE),[PRICE_US] = @A_PRICE_US/[dbo].[CONVERT_UNIT](@A_UNIT,[UNIT],SPARE_PART_CODE,@A_DEPT_CODE)
			   WHERE [SPARE_PART_CODE] = @A_SPARE_PART_CODE AND [DEPT_CODE]=@A_DEPT_CODE AND [MONTH] = MONTH(CAST(@A_DATE AS date)) AND [YEAR] = YEAR(CAST(@A_DATE AS date))

       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO