SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_MRP_LIST@PUT](
@A_DEPARTMENT		NVARCHAR(50),
@A_MRP_CODE         NVARCHAR(50),
@A_TITLE            NVARCHAR(50),
@A_STATUS           NVARCHAR(50),
@A_DATE_NEED_FINISH  NVARCHAR(50),
@A_USER             NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN

			DECLARE @CHECK nvarchar(50)
		    -- MRP-20210728-001
		   
		   SELECT @CHECK = COUNT(*) 
		   FROM [dbo].[EWIP_MRP_LIST]
		   WHERE [MRP_CODE] = @A_MRP_CODE AND [DEPT_CODE] = @A_DEPARTMENT

		    IF @A_DATE_NEED_FINISH = ''
					    SET @A_DATE_NEED_FINISH = NULL

		   IF @CHECK = 0
				BEGIN
					 INSERT INTO [dbo].[EWIP_MRP_LIST]
					 VALUES(@A_MRP_CODE,GETDATE(),'NEW',@A_DEPARTMENT,NULL,CAST(@A_DATE_NEED_FINISH AS DATE),@A_USER,NULL,NULL,@A_TITLE)
				END
			ELSE
			    BEGIN
					 UPDATE [dbo].[EWIP_MRP_LIST]
					 SET [STATUS] = @A_STATUS,[DATE_NEED_FINISH] = CAST(@A_DATE_NEED_FINISH AS DATE),[USER_UPDATE] = @A_USER,[DATE_UPDATE] = GETDATE(),[TITLE]= @A_TITLE
					  WHERE [MRP_CODE] = @A_MRP_CODE AND [DEPT_CODE] = @A_DEPARTMENT 
				END
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH

select CAST(NULL AS DATE)
GO