SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
create PROC [dbo].[PKG_BUSINESS_PO@GET_MERGE_CODE_BY_SPARE](
@A_SPARE_PART_CODE  NVARCHAR(50),
@A_DEPT_CODE NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			
			SELECT [SPARE_PART_CODE],[CODE_MERGED],[DEPT_CODE]
			FROM  [dbo].[EWIP_MERGE_SPAREPART_CODE] ME 
			WHERE [SPARE_PART_CODE] = @A_SPARE_PART_CODE AND DEPT_CODE = @A_DEPT_CODE

       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO