SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_EXCHANGE_RATE@PUT](
@A_RATE			   NVARCHAR(20),
@A_DATE             NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			DECLARE @CHECK INT
			SELECT @CHECK = COUNT(*) 
			FROM [dbo].[EWIP_EXCHANGE_RATE]
			WHERE [FROM] = 'USD' AND [TO] = 'VND' AND FORMAT (VALID_TIME, 'yyyyMMdd') =  FORMAT (CAST(@A_DATE as date), 'yyyyMMdd')

			IF @CHECK  = 0 
			   BEGIN
						INSERT INTO [dbo].[EWIP_EXCHANGE_RATE]
						VALUES(CAST(@A_DATE AS date),'USD','VND',CAST(@A_RATE AS float),GETDATE(),GETDATE());
			   END
			ELSE
			   BEGIN
						UPDATE [dbo].[EWIP_EXCHANGE_RATE]
						SET RATE = CAST(@A_RATE AS float) ,UPDATED_AT = GETDATE(),VALID_TIME = CAST(@A_DATE AS DATE)
						WHERE [FROM] = 'USD' AND [TO] = 'VND' AND FORMAT (VALID_TIME, 'yyyyMMdd') =  FORMAT (CAST(@A_DATE as date), 'yyyyMMdd')
			   END
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO