SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_INVENTORY_SHEET@GET_DETAIL](
@A_SHEET_ID NVARCHAR(50),
@A_DEPT_CODE NVARCHAR(50),
@A_STOCK NVARCHAR(50),
@N_RETURN  int	OUTPUT,
@V_RETURN  NVARCHAR(4000) OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  

			DECLARE @SHEET_MONTH DATE

			SELECT @SHEET_MONTH = [INVENTORY_SHEET_MONTH] FROM [dbo].[EWIP_INVENTORY_SHEET] WHERE [SHEET_ID] = @A_SHEET_ID AND DEPT_CODE = @A_DEPT_CODE AND STOCK_CODE = @A_STOCK

			IF @SHEET_MONTH IS NOT NULL AND FORMAT(@SHEET_MONTH,'yyyyMM') = FORMAT(GETDATE(),'yyyyMM')
			    BEGIN
					SELECT sl.SPARE_PART_CODE,sp.NAME_VI,sl.CONDITION_CODE,sl.TIME_IN, 
			          (CASE sl.[EXPIRED_DATE] 
					    WHEN '2199-01-01' THEN NULL
						WHEN '1900-01-01' THEN NULL
				       ELSE sl.[EXPIRED_DATE]
				       END) AS [EXPIRED_DATE],CAST(GETDATE() as date) as INVENTORY_ASSETS_TIME,sl.UNIT_ID as UNIT,SL.LOCATION_CODE AS LOCATION,SUM(sl.QUANTITY) AS QUANTITY, SUM(SD.QUANTITY_REAL) as QUANTITY_REAL, SUM(SD.QUANTITY_REAL) - SUM(sl.QUANTITY) AS DIFF
					 FROM [dbo].[EWIP_SPAREPART_LOCATION] sl
					INNER join [dbo].[EWIP_SPARE_PART] sp ON sl.[DEPT_CODE] = SP.SP_DEPT_CODE AND Sl.[SPARE_PART_CODE] = SP.CODE
					left JOIN  [dbo].[EWIP_INVENTORY_SHEET_DETAIL] SD  ON SD.DEPT_CODE = sl.DEPT_CODE AND SD.SPARE_PART_CODE = sl.SPARE_PART_CODE and SD.STOCK_CODE = sl.STOCK_CODE 
					           AND ISNULL(SD.LOCATION,'') = ISNULL(SL.LOCATION_CODE,'') AND SL.CONDITION_CODE = SD.CONDITION_CODE and  [SHEET_ID] = @A_SHEET_ID AND SL.TIME_IN = SD.TIME_IN AND SL.UNIT_ID = SD.UNIT 
							   AND (CASE WHEN SL.EXPIRED_DATE = '2199-01-01' THEN ''
							             WHEN SL.EXPIRED_DATE IS NULL THEN ''
							           ELSE SL.EXPIRED_DATE END) = 
									   (CASE WHEN SD.EXPIRED_DATE = '2199-01-01' THEN ''
							                            WHEN SD.EXPIRED_DATE IS NULL THEN ''
											WHEN SD.EXPIRED_DATE = '1900-01-01' THEN ''
							                ELSE SD.EXPIRED_DATE END)
								WHERE SL.DEPT_CODE = @A_DEPT_CODE AND SL.STOCK_CODE = @A_STOCK
								GROUP BY SL.DEPT_CODE,SL.STOCK_CODE,sl.SPARE_PART_CODE,SL.LOCATION_CODE,sp.NAME_VI,sl.CONDITION_CODE,sl.TIME_IN,sl.UNIT_ID,sl.[EXPIRED_DATE]
				END
			ELSE
			    BEGIN
					SELECT [SPARE_PART_CODE],SP.NAME_VI ,CONDITION_CODE,TIME_IN, 
							(CASE [EXPIRED_DATE] WHEN '2199-01-01' THEN NULL
							                     WHEN '1900-01-01' THEN NULL
							 ELSE [EXPIRED_DATE]
							 END) AS [EXPIRED_DATE],S.[DATE_START] AS INVENTORY_ASSETS_TIME,SD.UNIT,SD.LOCATION,SD.QUANTITY,cast(SD.QUANTITY_REAL as nvarchar) as QUANTITY_REAL,SD.DIFF
					FROM [dbo].[EWIP_INVENTORY_SHEET_DETAIL] SD 
					INNER JOIN [dbo].[EWIP_INVENTORY_SHEET] S ON SD.[SHEET_ID] = S.[SHEET_ID] AND SD.[DEPT_CODE] =S.[DEPT_CODE] AND SD.[STOCK_CODE] = S.[STOCK_CODE]
					inner join [dbo].[EWIP_SPARE_PART] SP ON SD.[DEPT_CODE] = SP.SP_DEPT_CODE AND SD.[SPARE_PART_CODE] = SP.CODE
					WHERE SD.[SHEET_ID] = @A_SHEET_ID AND SD.[DEPT_CODE] =@A_DEPT_CODE AND SD.[STOCK_CODE] = @A_STOCK
				END

			
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO