SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PR@GET_MRP_LIST](
@A_DEPARTMENT		NVARCHAR(100),
@A_MRP_CODE          NVARCHAR(50),
@A_PR_CODE           NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			
			SELECT 
				SP.GL_ACCOUNT, 
				SPD.COST_CTR,
				SP.CODE AS SPAREPART_CODE,
				SP.NAME_VI,
				SP.NAME_KR,
				SP.IMAGE,
				MRP.UNIT,
				MRP.QUANTITY_NEED_BUY,
				(CASE WHEN PRD.[EXPECTED_PRICE_VN] IS NULL OR PRD.[EXPECTED_PRICE_VN] = 0 THEN price.PRICE_VN/[dbo].[CONVERT_UNIT](price.UNIT_CODE,MRP.UNIT,sp.CODE,@A_DEPARTMENT)
				     ELSE PRD.[EXPECTED_PRICE_VN]/[dbo].[CONVERT_UNIT](PRD.UNIT,MRP.UNIT,sp.CODE,@A_DEPARTMENT)
				END) AS EXPECTED_PRICE_VN,
				(CASE WHEN PRD.[PRICE_VN] IS NULL OR PRD.[PRICE_VN] = 0 THEN price.PRICE_VN/[dbo].[CONVERT_UNIT](price.UNIT_CODE,MRP.UNIT,sp.CODE,@A_DEPARTMENT)
				     ELSE PRD.[PRICE_VN]/[dbo].[CONVERT_UNIT](PRD.UNIT,MRP.UNIT,sp.CODE,@A_DEPARTMENT)
				END) AS PRICE_VN,
				(CASE WHEN PRD.[EXPECTED_PRICE_US] IS NULL OR PRD.[EXPECTED_PRICE_US] = 0 THEN price.PRICE_US/[dbo].[CONVERT_UNIT](price.UNIT_CODE,MRP.UNIT,sp.CODE,@A_DEPARTMENT)
				     ELSE PRD.[EXPECTED_PRICE_US]/[dbo].[CONVERT_UNIT](PRD.UNIT,MRP.UNIT,sp.CODE,@A_DEPARTMENT)
				END) AS [EXPECTED_PRICE_US],
				(CASE WHEN PRD.[PRICE_US] IS NULL OR PRD.[PRICE_US] = 0 THEN price.PRICE_US/[dbo].[CONVERT_UNIT](price.UNIT_CODE,MRP.UNIT,sp.CODE,@A_DEPARTMENT)
				     ELSE PRD.[PRICE_US]/[dbo].[CONVERT_UNIT](PRD.UNIT,MRP.UNIT,sp.CODE,@A_DEPARTMENT)
				END) AS PRICE_US,
				(CASE WHEN PRD.[TOTAL_MONEY_VN] IS NULL OR PRD.[TOTAL_MONEY_VN] = 0 THEN (price.PRICE_VN/[dbo].[CONVERT_UNIT](price.UNIT_CODE,MRP.UNIT,sp.CODE,@A_DEPARTMENT)) * MRP.QUANTITY_NEED_BUY
				     ELSE PRD.[TOTAL_MONEY_VN]
				END) AS [TOTAL_MONEY_VN],
				(CASE WHEN PRD.[TOTAL_MONEY_US] IS NULL OR PRD.[TOTAL_MONEY_US] = 0 THEN (price.PRICE_US/[dbo].[CONVERT_UNIT](price.UNIT_CODE,MRP.UNIT,sp.CODE,@A_DEPARTMENT)) * MRP.QUANTITY_NEED_BUY
				     ELSE PRD.[TOTAL_MONEY_US]
				END) AS [TOTAL_MONEY_US],
				(CASE WHEN PRD.[VENDOR_ID] IS NULL OR PRD.[VENDOR_ID] = '' THEN SP.VENDER_ID
				    ELSE PRD.[VENDOR_ID] END) AS VENDOR_ID,
				MRP.DATE_NEED_FINISH,
				MRP.ID as STT_MRP,
				MRP.DATE_END_ACTUAL,
				(CASE WHEN (PRD.DATE_CREATE IS NULL OR PRD.DATE_CREATE = '')THEN MRP.DATE_UPDATE
				      ELSE PRD.DATE_CREATE 
				END) AS DATE_CREATE
			FROM [dbo].[EWIP_MRP] MRP
			INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON MRP.SPAREPART_CODE = SP.CODE AND SP.SP_DEPT_CODE = MRP.DEPT_CODE
			INNER JOIN [dbo].[EWIP_SPARE_PART_DEPT] SPD ON MRP.SPAREPART_CODE  = SPD.SPARE_PART_CODE AND MRP.DEPT_CODE = SPD.DEPT_CODE
			LEFT JOIN  [dbo].[EWIP_PURCHASE_REQUEST_DETAIL] PRD ON MRP.MRP_CODE = PRD.[MRP_CODE] AND MRP.DEPT_CODE = PRD.[DEPT_CODE] AND MRP.SPAREPART_CODE = PRD.[SPAREPART_CODE] AND (PRD.[PR_CODE] in (@A_PR_CODE,'') or PRD.[PR_CODE] is null)
			LEFT JOIN   (
							SELECT TOP 1 WITH TIES 
							[SPARE_PART_CODE],
							[PRICE_VN],
							[PRICE_US], 
							[UNIT_CODE]
							FROM [dbo].[EWIP_SPAREPART_PRICE]
							WHERE [DEPT_CODE] = @A_DEPARTMENT 
							ORDER BY ROW_NUMBER() OVER(PARTITION BY SPARE_PART_CODE ORDER BY [DATE] DESC)
						) AS price ON MRP.SPAREPART_CODE = price.SPARE_PART_CODE
			 LEFT JOIN [dbo].[EWIP_VENDER] VD ON PRD.[VENDOR_ID] = VD.VENDER_ID
			WHERE MRP.DEPT_CODE = @A_DEPARTMENT AND MRP.MRP_CODE = @A_MRP_CODE 

			SELECT TOP 1 [PR_STATUS],
			       [MRP_CODE],
				   [TOTAL_VALUE],
				   [TOTAL_VALUE_US],
				   (CASE WHEN [DATE_END_ACTUAL] IS NULL THEN [DATE_NEED_FINISH]
				        ELSE [DATE_END_ACTUAL]
					END) AS DATE_NEED_FINISH,
				   [PURPOSE_OF_BUYING],
					[DATE_CREATE]
			FROM [dbo].[EWIP_PURCHASE_REQUEST]
			WHERE [PR_CODE] = @A_PR_CODE AND DEPT_CODE = @A_DEPARTMENT

       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO