SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PKG_COMM@CHG_PWD](
@A_PLANT	VARCHAR(50),
@A_USER_ID	VARCHAR(50),
@A_CURR_PWD	NVARCHAR(50),
@A_CHG_PWD	NVARCHAR(50),
@N_RETURN  int			 OUTPUT,
@V_RETURN  NVARCHAR(4000) OUTPUT
)
AS

DECLARE @V_CHECK	INT;

BEGIN TRY

  SET @V_CHECK = 0;

    SELECT  @V_CHECK = COUNT(*)
    FROM ESYSMSTUSR T1
    WHERE T1.PLANT = @A_PLANT
	AND T1.USER_ID  = @A_USER_ID
    AND T1.PASSWORD = @A_CURR_PWD;
	--test
    IF @V_CHECK = 0 
	  BEGIN
		SET @N_RETURN = -1;
		SET @V_RETURN = 'MSG_ERR_149';
		RETURN;
	  END

    BEGIN TRAN
		UPDATE ESYSMSTUSR 
		SET PASSWORD = @A_CHG_PWD
		WHERE PLANT = @A_PLANT
		AND USER_ID = @A_USER_ID;
	COMMIT TRAN;

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_001';
END TRY
BEGIN CATCH

	rollback tran;
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO