SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PR@DELETE](
@A_DEPARTMENT		NVARCHAR(50),
@A_PR_CODE          NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			DELETE FROM [dbo].[EWIP_PURCHASE_REQUEST]
			WHERE [PR_CODE] = @A_PR_CODE AND DEPT_CODE = @A_DEPARTMENT

			DELETE FROM [dbo].[EWIP_PURCHASE_REQUEST_DETAIL]
			WHERE [PR_CODE] =@A_PR_CODE AND DEPT_CODE = @A_DEPARTMENT

			DELETE FROM [dbo].[EWIP_ORDER_PR]
			WHERE PR_CODE = @A_PR_CODE AND DEPT_CODE = @A_DEPARTMENT

			DELETE FROM [dbo].[EWIP_ORDER_DETAIL]
			WHERE PR_CODE = @A_PR_CODE AND DEPT_CODE = @A_DEPARTMENT

       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO