SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_MRP_LIST@GET](
@A_DEPARTMENT		NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN

			DECLARE @CHECK nvarchar(50)
		    -- MRP-20210728-001
		   
		   SELECT * FROM [dbo].[EWIP_MRP_LIST] 
		   WHERE [DEPT_CODE] = @A_DEPARTMENT AND [STATUS] IN('NEW','WAIT_ACCEPT')
		   ORDER BY [MRP_CODE] DESC 

       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO