SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP_INVENTORY@DELETE](
@A_DEPARTMENT		NVARCHAR(50),
@A_STOCK            VARCHAR(50),
@A_SPARE_PART_CODE  NVARCHAR(50),
@A_IS_INVENTORY        NVARCHAR(2),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			IF @A_IS_INVENTORY = '1'
				DELETE FROM [dbo].[EWIP_SPAREPART_INVENTORY] 
				WHERE [SPARE_PART_CODE] = @A_SPARE_PART_CODE AND [STOCK_CODE] = @A_STOCK AND [DEPT_CODE] = @A_DEPARTMENT
            ELSE
			   DELETE FROM [dbo].[EWIP_SETUP_MINSTOCK]
			   WHERE [SPARE_PART_CODE] = @A_SPARE_PART_CODE AND [STOCK_CODE] = @A_STOCK AND [DEPT_CODE] = @A_DEPARTMENT
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH

GO