CREATE TABLE [dbo].[EWIP_SPAREPART_LOCATION_TRANSACTION] (
  [ID] [int] IDENTITY,
  [SPARE_PART_CODE] [nvarchar](50) NOT NULL,
  [LOCATION_CODE_FROM] [nvarchar](50) NULL,
  [LOCATION_CODE_TO] [nvarchar](50) NULL,
  [CONDITION_CODE] [varchar](50) NULL,
  [QUANTITY] [float] NULL,
  [DEPT_CODE] [varchar](50) NULL,
  [STOCK_CODE] [varchar](50) NULL,
  [UNIT_ID] [varchar](20) NULL,
  [EXPIRED_DATE] [date] NULL,
  [TIME_IN] [date] NULL,
  [DATE_MOVE] [datetime] NULL,
  [USER_MOVE] [nvarchar](50) NULL,
  CONSTRAINT [PK_EWIP_SPAREPART_LOCATION_TRANSACTION] PRIMARY KEY CLUSTERED ([ID])
)
ON [PRIMARY]
GO