CREATE TABLE [dbo].[ESYSLOGLGN] (
  [PLANT] [varchar](10) NOT NULL,
  [DEPARTMENT] [varchar](50) NOT NULL,
  [USER_ID] [varchar](30) NOT NULL,
  [HIST_SEQ] [int] NOT NULL,
  [ACCESS_TIME] [varchar](14) NOT NULL,
  [ACCESS_IP] [varchar](20) NULL,
  [ACCESS_PC] [varchar](100) NULL,
  CONSTRAINT [PK_ESYSLOGLGN] PRIMARY KEY CLUSTERED ([PLANT], [DEPARTMENT], [USER_ID], [HIST_SEQ])
)
ON [PRIMARY]
GO