CREATE TABLE [dbo].[ESYSMSTMRO] (
  [PLANT] [varchar](10) NOT NULL,
  [DEPARTMENT] [varchar](50) NOT NULL,
  [USERROLE] [varchar](30) NOT NULL,
  [MENUSEQ] [int] NOT NULL,
  [FORMROLE] [varchar](3) NULL,
  [USEFLAG] [char](1) NULL CONSTRAINT [DF_ESYSMSTMRO_USEFLAG] DEFAULT ('Y'),
  [CREATE_TIME] [varchar](14) NULL,
  [UPDATE_TIME] [varchar](20) NULL,
  [CREATE_USER] [varchar](30) NULL,
  CONSTRAINT [PK_ESYSMSTMRO] PRIMARY KEY CLUSTERED ([PLANT], [DEPARTMENT], [USERROLE], [MENUSEQ])
)
ON [PRIMARY]
GO