CREATE TABLE [dbo].[ESYSMSTROL] (
  [PLANT] [varchar](10) NOT NULL,
  [DEPARTMENT] [varchar](50) NOT NULL,
  [USERROLE] [varchar](20) NOT NULL,
  [USERROLE_NAME] [nvarchar](50) NOT NULL,
  [USEFLAG] [char](1) NOT NULL CONSTRAINT [DF_ESYSMSTROL_USEFLAG] DEFAULT ('Y'),
  [REMARKS] [nvarchar](4000) NULL,
  [CREATE_TIME] [varchar](14) NOT NULL,
  [CREATE_USER] [varchar](30) NOT NULL,
  [UPDATE_TIME] [varchar](14) NULL,
  [UPDATE_USER] [varchar](30) NULL,
  CONSTRAINT [PK_ESYSMSTROL] PRIMARY KEY CLUSTERED ([PLANT], [DEPARTMENT], [USERROLE])
)
ON [PRIMARY]
GO