CREATE TABLE [dbo].[EWIP_SPARE_PART_DEPT] (
  [DEPT_CODE] [nvarchar](100) NOT NULL,
  [SPARE_PART_CODE] [nvarchar](50) NOT NULL,
  [COST_CTR] [varchar](50) NULL,
  CONSTRAINT [PK_EWIP_SPARE_PART_DEPT] PRIMARY KEY CLUSTERED ([DEPT_CODE], [SPARE_PART_CODE])
)
ON [PRIMARY]
GO