CREATE TABLE [dbo].[EWIP_MERGE_SPAREPART_CODE] (
  [ID] [int] IDENTITY,
  [SPARE_PART_CODE] [nvarchar](50) NULL,
  [CODE_MERGED] [nvarchar](50) NULL,
  [DEPT_CODE] [nvarchar](50) NULL,
  [USER_CREATE] [nvarchar](50) NULL,
  [DATE_CREATE] [datetime] NULL,
  CONSTRAINT [PK_EWIP_MERGE_SPAREPART_CODE] PRIMARY KEY CLUSTERED ([ID])
)
ON [PRIMARY]
GO