CREATE TABLE [dbo].[EWIP_SPAREPART_TYPE] (
  [ID] [int] IDENTITY,
  [CODE] [varchar](50) NOT NULL,
  [NAME] [nvarchar](50) NULL,
  [DEPT_CODE] [nvarchar](100) NOT NULL,
  CONSTRAINT [PK_EWIP_SPAREPART_TYPE] PRIMARY KEY CLUSTERED ([ID])
)
ON [PRIMARY]
GO