CREATE TABLE [dbo].[ESYSMSTFORM] (
  [PLANT] [varchar](10) NOT NULL,
  [DEPARTMENT] [varchar](50) NOT NULL,
  [FORM] [varchar](30) NOT NULL,
  [FORMNAME] [nvarchar](50) NOT NULL,
  [MENUAL_FILE] [nvarchar](4000) NULL,
  [ACCESS_TYPE] [char](1) NULL,
  [USEFLAG] [char](1) NOT NULL CONSTRAINT [DF_ESYSMSTFORM_USEFLAG] DEFAULT ('Y'),
  [REMARKS] [nvarchar](4000) NULL,
  [CREATE_TIME] [varchar](14) NOT NULL,
  [CREATE_USER] [varchar](20) NOT NULL,
  [UPDATE_TIME] [varchar](14) NULL,
  [UPDATE_USER] [varchar](20) NULL,
  CONSTRAINT [PK_ESYSMSTFORM] PRIMARY KEY CLUSTERED ([PLANT], [DEPARTMENT], [FORM])
)
ON [PRIMARY]
GO