CREATE TABLE [dbo].[SPAREPART_CODE_ENCRIPT] (
  [SPARE_PART_CODE] [nvarchar](50) NOT NULL,
  [ENCRIPT_CODE] [nvarchar](50) NULL,
  [DEPT_CODE] [nvarchar](50) NOT NULL,
  CONSTRAINT [PK_SPAREPART_CODE_ENCRIPT] PRIMARY KEY CLUSTERED ([SPARE_PART_CODE], [DEPT_CODE])
)
ON [PRIMARY]
GO