CREATE TABLE [dbo].[ESYSLOGFORM] (
  [PLANT] [varchar](10) NOT NULL,
  [USER_ID] [varchar](30) NOT NULL,
  [HIST_SEQ] [int] NOT NULL,
  [FORM_CODE] [varchar](30) NOT NULL,
  [DEPARTMENT] [varchar](50) NOT NULL,
  [ACCESS_TIME] [varchar](14) NOT NULL,
  CONSTRAINT [PK_ESYSLOGFORM] PRIMARY KEY CLUSTERED ([PLANT], [USER_ID], [HIST_SEQ], [FORM_CODE], [DEPARTMENT])
)
ON [PRIMARY]
GO