CREATE TABLE [dbo].[EWIP_GL_ACCOUNT] (
  [ID] [int] IDENTITY,
  [GL_ACCOUNT] [varchar](50) NOT NULL,
  [SHORT_TEXT_VN] [nvarchar](50) NULL,
  [SHORT_TEXT_KR] [nvarchar](200) NULL,
  CONSTRAINT [PK_EWIP_GL_ACCOUNT] PRIMARY KEY CLUSTERED ([ID])
)
ON [PRIMARY]
GO