CREATE TABLE [dbo].[ESYSMSTGLA] (
  [PLANT] [varchar](10) NOT NULL,
  [DEPARTMENT] [varchar](50) NOT NULL CONSTRAINT [DF_ESYSMSTGLA_DEPARTMENT] DEFAULT ('ALL'),
  [GLSR] [varchar](200) NOT NULL,
  [ENG] [nvarchar](4000) NULL,
  [KOR] [nvarchar](4000) NULL,
  [CHN] [nvarchar](4000) NULL,
  [VTN] [nvarchar](4000) NULL,
  [MASTER_FLAG] [char](1) NULL,
  [CREATE_TIME] [varchar](14) NOT NULL,
  [CREATE_USER] [varchar](20) NOT NULL,
  [UPDATE_TIME] [varchar](14) NULL,
  [UPDATE_USER] [varchar](20) NULL,
  [USE_FLAG] [varchar](1) NULL CONSTRAINT [DF_ESYSMSTGLA_USE_FLAG] DEFAULT ('N'),
  CONSTRAINT [PK_ESYSMSTGLA] PRIMARY KEY CLUSTERED ([PLANT], [DEPARTMENT], [GLSR])
)
ON [PRIMARY]
GO