CREATE TYPE [dbo].[PO_DETAIL_TYPE] AS TABLE (
  [PO_ID] [nvarchar](50) NULL,
  [PO_ID_TEMP] [nvarchar](50) NULL,
  [PO_CREATE] [nvarchar](50) NULL,
  [LIFNR] [nvarchar](50) NULL,
  [PR_CODE] [nvarchar](50) NULL,
  [KUNNR] [nvarchar](50) NULL,
  [BKGRP] [nvarchar](50) NULL,
  [PSTYP] [nvarchar](50) NULL,
  [SPARE_PART_CODE] [nvarchar](50) NULL,
  [TXZ01_DESCRIPTION] [nvarchar](max) NULL,
  [WERKS] [nvarchar](50) NULL,
  [LGORT] [nvarchar](50) NULL,
  [LGORT_STOREAGE_LOCATION] [nvarchar](50) NULL,
  [PO_QTY] [nvarchar](50) NULL,
  [UNIT] [nvarchar](50) NULL,
  [NETPR_PRICE] [nvarchar](50) NULL,
  [PER] [nvarchar](50) NULL,
  [WAERS] [nvarchar](50) NULL,
  [MWSKZ] [nvarchar](50) NULL,
  [EINDT_DELIVERY_DATE] [nvarchar](50) NULL,
  [KNTTP] [nvarchar](50) NULL,
  [MATKL] [nvarchar](50) NULL,
  [POSID] [nvarchar](50) NULL,
  [SAKNR_GL_ACCOUNT] [nvarchar](50) NULL,
  [KOSTL_COST_CENTER] [nvarchar](50) NULL,
  [DEPT_CODE] [nvarchar](50) NULL
)
GO