SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PO@CANCEL_MERGE_CODE](
@A_DATA [dbo].[EWIP_MERGE_SPAREPART_CODE_TYPE] READONLY,
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			
			DELETE [dbo].[EWIP_MERGE_SPAREPART_CODE]
			WHERE ([SPARE_PART_CODE] +'^'+[CODE_MERGED]+'^'+[DEPT_CODE]) IN (SELECT [SPARE_PART_CODE]+'^'+[CODE_MERGED]+'^'+[DEPT_CODE] FROM @A_DATA)

       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
