SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP@GET_NAME_KR](
@A_DEPARTMENT		NVARCHAR(50),
@A_CODE				NVARCHAR(MAX),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
			SELECT distinct
			   sp.CODE,
			   sp.NAME_VI,
			   sp.NAME_KR			   
			FROM EWIP_SPARE_PART sp 
			WHERE TRIM(sp.CODE) IN (SELECT TRIM(VALUE) FROM string_split(@A_CODE,'$')) AND sp.[SP_DEPT_CODE] = @A_DEPARTMENT;
		
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
