SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PO@CANCEL_PO](
@A_DATA            [dbo].[SP_MRP_PR_PO_TYPE] READONLY,
@A_CANCEL_ALL       NVARCHAR(20),
@A_USER             NVARCHAR(50),
@A_PO_ID           NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			DECLARE @STATUS_CANCEL NVARCHAR(20) = 'CANCEL';
			DECLARE @STATUS_NEW NVARCHAR(50) = 'NEW'
			IF @A_CANCEL_ALL = 'True'
			   BEGIN
					UPDATE [dbo].[EWIP_ORDER]
					SET STATUS = @STATUS_CANCEL,USER_ID = @A_USER,UPDATED_DATE = GETDATE()
					WHERE PO_ID IN (SELECT DISTINCT [PO_ID] FROM @A_DATA)
			   END
			   
              DECLARE @PO_ID NVARCHAR(50)
			  DECLARE @MRP_CODE NVARCHAR(50)
			  DECLARE @PR_CODE NVARCHAR(50)
			  DECLARE @SPARE_PART_CODE NVARCHAR(50)
			  DECLARE @DEPT_CODE NVARCHAR(50)

			   DECLARE poCursor CURSOR FOR
			   SELECT PO_ID,MRP_CODE,PR_CODE,[SPARE_PART_CODE],[DEPT_CODE] FROM @A_DATA

			   OPEN poCursor

			   FETCH NEXT FROM poCursor
			   INTO @PO_ID,@MRP_CODE,@PR_CODE,@SPARE_PART_CODE,@DEPT_CODE

			   WHILE @@FETCH_STATUS = 0
			       BEGIN
						UPDATE [dbo].[EWIP_MRP]
						SET [STATUS] = @STATUS_NEW,MRP_CODE = NULL
						WHERE [SPAREPART_CODE] = @SPARE_PART_CODE AND MRP_CODE = @MRP_CODE AND DEPT_CODE = @DEPT_CODE
						
						UPDATE [dbo].[EWIP_PURCHASE_REQUEST_DETAIL]
						SET STATUS = @STATUS_NEW,MRP_CODE = NULL,PR_CODE = NULL
						WHERE MRP_CODE = @MRP_CODE AND PR_CODE = @PR_CODE AND [SPAREPART_CODE] = @SPARE_PART_CODE

						DELETE [dbo].[EWIP_ORDER_DETAIL]
						WHERE SPARE_PART_CODE = @SPARE_PART_CODE AND DEPT_CODE = @DEPT_CODE AND PR_CODE = @PR_CODE AND PO_ID = @A_PO_ID

						FETCH NEXT FROM poCursor
						INTO @PO_ID,@MRP_CODE,@PR_CODE,@SPARE_PART_CODE,@DEPT_CODE
				   END
				   CLOSE poCursor
				   DEALLOCATE poCursor


			   DECLARE poCursor1 CURSOR FOR
			   SELECT PO_ID,MRP_CODE,PR_CODE,[SPARE_PART_CODE],[DEPT_CODE] FROM @A_DATA

			   OPEN poCursor1

			   FETCH NEXT FROM poCursor1
			   INTO @PO_ID,@MRP_CODE,@PR_CODE,@SPARE_PART_CODE,@DEPT_CODE

			   WHILE @@FETCH_STATUS = 0
			       BEGIN
						IF NOT EXISTS (SELECT * FROM [dbo].[EWIP_MRP] WHERE [MRP_CODE] = @MRP_CODE AND DEPT_CODE = @DEPT_CODE)
						    UPDATE [dbo].[EWIP_MRP_LIST]
							SET [STATUS] = @STATUS_CANCEL,USER_UPDATE =@A_USER,DATE_UPDATE = GETDATE()
							WHERE [MRP_CODE] = @MRP_CODE AND DEPT_CODE = @DEPT_CODE

						IF NOT EXISTS (SELECT * FROM [dbo].[EWIP_PURCHASE_REQUEST_DETAIL] WHERE [PR_CODE] = @PR_CODE AND MRP_CODE = @MRP_CODE AND DEPT_CODE = @DEPT_CODE)
						     BEGIN
							      UPDATE [dbo].[EWIP_PURCHASE_REQUEST]	
								  SET [PR_STATUS] = @STATUS_CANCEL,USER_UPDATE = @A_USER, DATE_UPDATE = GETDATE()
								  WHERE [PR_CODE] = @PR_CODE AND MRP_CODE = @MRP_CODE AND DEPT_CODE = @DEPT_CODE 
							 END
						ELSE
						   BEGIN
								  UPDATE [dbo].[EWIP_PURCHASE_REQUEST]	
								  SET TOTAL_VALUE = (SELECT SUM([TOTAL_MONEY_VN]) FROM [dbo].[EWIP_PURCHASE_REQUEST_DETAIL] WHERE PR_CODE = @PR_CODE AND DEPT_CODE = @DEPT_CODE),
								       [TOTAL_VALUE_US] =  (SELECT SUM(TOTAL_MONEY_US) FROM [dbo].[EWIP_PURCHASE_REQUEST_DETAIL] WHERE PR_CODE = @PR_CODE AND DEPT_CODE = @DEPT_CODE),
										[DATE_NEED_FINISH] = (SELECT MAX([DATE_NEED_FINISH]) FROM [dbo].[EWIP_PURCHASE_REQUEST_DETAIL] WHERE PR_CODE = @PR_CODE AND DEPT_CODE = @DEPT_CODE),
										USER_UPDATE = @A_USER,DATE_UPDATE = GETDATE()
								  WHERE [PR_CODE] = @PR_CODE AND MRP_CODE = @MRP_CODE AND DEPT_CODE = @DEPT_CODE 
						   END

					   IF NOT EXISTS (SELECT * FROM [dbo].[EWIP_PURCHASE_REQUEST] WHERE [PR_CODE] = @PR_CODE AND MRP_CODE = @MRP_CODE AND DEPT_CODE = @DEPT_CODE AND PR_STATUS != @STATUS_CANCEL)
					      BEGIN
								DELETE [dbo].[EWIP_ORDER_PR]
								WHERE PR_CODE = @PR_CODE AND DEPT_CODE = @DEPT_CODE
						  END
                       ELSE 
					      UPDATE  [dbo].[EWIP_ORDER_PR]
						  SET [DATE_NEED_FINISH] =  (SELECT MAX([DATE_NEED_FINISH]) FROM [dbo].[EWIP_PURCHASE_REQUEST_DETAIL] WHERE PR_CODE = @PR_CODE AND DEPT_CODE = @DEPT_CODE),USER_UPDATE = @A_USER,DATE_UPDATE = GETDATE()
						  WHERE PR_CODE = @PR_CODE
						        
						FETCH NEXT FROM poCursor1
						INTO @PO_ID,@MRP_CODE,@PR_CODE,@SPARE_PART_CODE,@DEPT_CODE
				   END
				   CLOSE poCursor1
				   DEALLOCATE poCursor1
				
				 UPDATE [dbo].[EWIP_ORDER]
				 SET [DATE_NEED_FINISH] = (SELECT MAX([DATE_NEED_FINISH]) FROM [dbo].[EWIP_ORDER_PR] WHERE PO_ID = @A_PO_ID)
				 WHERE PO_ID = @A_PO_ID

       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
