SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP_EQUIPMENT@PUT](
@A_CODE             NVARCHAR(50),-- MA THIET BI
@A_EQ_NAME          NVARCHAR(50),
@A_EQ_TYPE          NVARCHAR(50),
@A_EQ_YEAR          NVARCHAR(50),
@A_EQ_LOCATION      NVARCHAR(50),
@A_EQ_SERIAL        NVARCHAR(50),
@A_EQ_ORIGIN        NVARCHAR(50),
@A_EQ_MODEL         NVARCHAR(50),
@A_DETAIL_INFO      NVARCHAR(MAX),
@A_IMAGE            NVARCHAR(MAX),
@A_USER				NVARCHAR(50),
@A_DEPARTMENT		NVARCHAR(50),
@A_DATA_SPARE       NVARCHAR(MAX),
@A_STATUS           NVARCHAR(50),
@A_DATE_IN          NVARCHAR(50),
@A_SUB_LOCATION		NVARCHAR(50),
@A_MANUFACTURER     NVARCHAR(200),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  

			IF @A_DATE_IN = '' 
			    SET @A_DATE_IN = NULL

			IF @A_EQ_YEAR = ''
			    SET  @A_EQ_YEAR = NULL

			IF EXISTS(SELECT TOP 1 * FROM [dbo].[EWIP_EQUIPMENT] WHERE [EQUIPMENT_ID] = @A_CODE AND [DEPT_CODE] = @A_DEPARTMENT)
			   BEGIN
					  	UPDATE [dbo].[EWIP_EQUIPMENT]
						SET [EQUIPMENT_NAME] = @A_EQ_NAME,
							[EQUIPMENT_TYPE] = @A_EQ_TYPE,
							[EQ_MANUFACTURING_YEAR] = YEAR (CAST(@A_EQ_YEAR AS DATE)),
							[EQ_SERIAL] = @A_EQ_SERIAL,
							[EQ_ORIGIN] = @A_EQ_ORIGIN,
							[EQ_MODEL] = @A_EQ_MODEL,
							[IMAGE] = @A_IMAGE,
							[DETAIL_INFO] = @A_DETAIL_INFO,
							[USER_UPDATE] = @A_USER,
							[SYS_TIME] = SYSDATETIME(),
							[STATUS] = @A_STATUS,
							DATE_IN = @A_DATE_IN,
							[MANUFACTURER] = @A_MANUFACTURER
						WHERE [EQUIPMENT_ID] = @A_CODE AND [DEPT_CODE] = @A_DEPARTMENT
			   END
			ELSE
			   BEGIN
					 INSERT INTO [dbo].[EWIP_EQUIPMENT]
					    ([EQUIPMENT_ID]
					    ,[EQUIPMENT_NAME]
					    ,[EQUIPMENT_TYPE]
					    ,[EQ_MANUFACTURING_YEAR]
					    ,[EQ_SERIAL]
					    ,[EQ_ORIGIN]
					    ,[EQ_MODEL]
					    ,[IMAGE]
					    ,[DETAIL_INFO]
					    ,[DEPT_CODE]
					    ,[USER_UPDATE]
					    ,[SYS_TIME],[STATUS],DATE_IN,[MANUFACTURER])
					 VALUES
					    (@A_CODE,@A_EQ_NAME,@A_EQ_TYPE, YEAR(CAST(@A_EQ_YEAR AS DATE)),@A_EQ_SERIAL,@A_EQ_ORIGIN,@A_EQ_MODEL,@A_IMAGE,@A_DETAIL_INFO,@A_DEPARTMENT,@A_USER,SYSDATETIME(),@A_STATUS,@A_DATE_IN,@A_MANUFACTURER)
				END

				DELETE FROM [dbo].[EWIP_EQUIPMENT_BOM]
				WHERE [EQUIPMENT_ID] = @A_CODE AND [DEP_CODE] = @A_DEPARTMENT

				INSERT INTO [dbo].[EWIP_EQUIPMENT_BOM]
				SELECT @A_CODE,TRIM(VALUE),@A_DEPARTMENT FROM string_split(@A_DATA_SPARE, '^')

				DELETE FROM [dbo].[EWIP_EQUIPMENT_LOCATION_RELATION]
				WHERE [EQUIPMENT_ID] = @A_CODE AND [DEPT_CODE] = @A_DEPARTMENT

				INSERT INTO [dbo].[EWIP_EQUIPMENT_LOCATION_RELATION]
				VALUES(@A_CODE,@A_EQ_LOCATION,@A_DEPARTMENT,@A_SUB_LOCATION)
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
