SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_GOC_PLANT@INIT](
@A_DEPARTMENT		NVARCHAR(50),
@A_DATE             NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  

			IF @A_DEPARTMENT = 'SMT'
				SELECT CAST([WEEK] AS NVARCHAR) AS [WEEK]
						,[UPDATE_DATE]
						,CAST([MONTH] AS NVARCHAR) AS MONTH
						,[MODEL]
						,[MODEL_NAME]
						,[SALES_PLAN]
						,[SALES_PLAN_POINT]
						,[WHC_PLAN]
						,[WHC_PLAN_POINT]
						,[STOCK] AS STOCKS
						,[STOCK_POINT]
						,[UPDATE_TIME_SYS]
						,[USER_UPDATE]
						,CAST([YEAR_PLAN] AS NVARCHAR) AS YEAR
	           FROM EWIP_GOC_PLAN_SMT egps 
				WHERE egps.MONTH =  MONTH(CAST(@A_DATE AS DATE)) AND egps.YEAR_PLAN = YEAR(CAST(@A_DATE AS DATE))
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
