SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PRICE@GET_DATE_FOR_IMPORT](
@A_DEPT_CODE NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			
			SELECT ROW_NUMBER() OVER(ORDER BY ID ASC) AS STT,CODE,NAME_VI AS NAME_VN,'' AS PRICE_VND,'' AS PRICE_USD,'PACK' AS UNIT,FORMAT (getdate(), 'dd/MM/yyyy ') AS [TIME], 'USD OR VND' AS INPUT_DEFAULT  
			FROM [dbo].[EWIP_SPARE_PART] WHERE SP_DEPT_CODE = @A_DEPT_CODE
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
