SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PRODUCT_ACTUAL_PLANT@INIT](
@A_DEPARTMENT		NVARCHAR(50),
@A_DATE             NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  

			IF @A_DEPARTMENT = 'SMT'
				SELECT LOT_NO,[MODEL],[PRODUCT_POINT],[WEEK],[MONTH],[DATE],[UPDATE_TIME_SYS],[USER_UPDATE]
				FROM [dbo].[EWIP_DAILY_ACTUAL_PROCD_SMT]
				WHERE [MONTH] = MONTH(CAST(@A_DATE AS DATE)) AND YEAR([DATE]) = YEAR(CAST(@A_DATE AS DATE))
				ORDER BY DATE
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
