SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP_INVENTORY@REPORT_BY_SPAREPART](
@A_DEPARTMENT		NVARCHAR(50),
@A_STOCK_CODE       NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  

			DECLARE @PACK_UNIT NVARCHAR(50) = 'PACK';

		 --   SELECT ROW_NUMBER() OVER(ORDER BY inv.SPARE_PART_CODE ASC) as STT,
			--	inv.SPARE_PART_CODE AS CODE, 
			--	sp.NAME_VI,sp.NAME_KR,
			--	sp_type.NAME as SPARE_PART_TYPE,
			--	'Pack' as UNIT,
			--	SUB.PRICE_VN/[dbo].[CONVERT_UNIT](SUB.[UNIT_CODE],@PACK_UNIT,inv.SPARE_PART_CODE,@A_DEPARTMENT)  AS PRICE_VN,
			--	SUB.PRICE_US/[dbo].[CONVERT_UNIT](SUB.[UNIT_CODE],@PACK_UNIT,inv.SPARE_PART_CODE,@A_DEPARTMENT)  AS PRICE_US,
			--	([dbo].[CONVERT_UNIT](inv.UNIT_IN_CODE,@PACK_UNIT,inv.SPARE_PART_CODE,@A_DEPARTMENT)* ISNULL(inv.QUANTITY,0) - ISNULL(SUB1.QUANTITY_PACK,0)) as QUANTITY,
			--	 SUM(SPL.QUANTITY *([dbo].[CONVERT_UNIT](spl.UNIT_ID,@PACK_UNIT,spl.SPARE_PART_CODE,@A_DEPARTMENT))) AS AMOUNT_VN,
			--	(SUB.PRICE_US/[dbo].[CONVERT_UNIT](SUB.[UNIT_CODE],@PACK_UNIT,inv.SPARE_PART_CODE,@A_DEPARTMENT)) * ([dbo].[CONVERT_UNIT](inv.UNIT_IN_CODE,@PACK_UNIT,inv.SPARE_PART_CODE,@A_DEPARTMENT)*ISNULL(inv.QUANTITY,0) - ISNULL(SUB1.QUANTITY_PACK,0)) AS AMOUNT_US,
			--	[dbo].[CONVERT_UNIT](mins.UNIT_CODE,@PACK_UNIT,inv.SPARE_PART_CODE,@A_DEPARTMENT)*mins.MIN_STOCK as MIN_STOCK,
			--	[dbo].[CONVERT_UNIT](bom.UNIT,@PACK_UNIT,inv.SPARE_PART_CODE,@A_DEPARTMENT)*bom.[WORKING_A_MONTH] AS WORKING_A_MONTH,
			--	[dbo].[CONVERT_UNIT](sp.UNIT_ID,@PACK_UNIT,inv.SPARE_PART_CODE,@A_DEPARTMENT)*sp.[MIN_ORDER] AS MIN_ORDER,
			--	SP.VENDER_ID,
			--	inv.STOCK_CODE
			--FROM [dbo].[EWIP_SPAREPART_INVENTORY] inv
			--INNER JOIN [dbo].[EWIP_SPARE_PART] sp ON inv.SPARE_PART_CODE = sp.CODE and inv.DEPT_CODE = SP.SP_DEPT_CODE
			--LEFT JOIN (
			--				SELECT [SPARE_PART_CODE],[dbo].[CONVERT_UNIT]([UNIT_ID],@PACK_UNIT,SPARE_PART_CODE,@A_DEPARTMENT)* ISNULL([QUANTITY],0) as QUANTITY_PACK
			--				FROM [dbo].[EWIP_SPAREPART_LOCATION] 
			--				WHERE [DEPT_CODE] = @A_DEPARTMENT AND [STOCK_CODE] = @A_STOCK_CODE AND (CONDITION_CODE = 'INTEGRATED' OR CONDITION_CODE = 'NG')
			--		  ) AS SUB1 ON inv.SPARE_PART_CODE = SUB1.SPARE_PART_CODE 
			--LEFT JOIN [dbo].[EWIP_SPAREPART_LOCATION] SPL ON inv.SPARE_PART_CODE = SPL.SPARE_PART_CODE AND inv.DEPT_CODE = SPL.DEPT_CODE AND SPL.CONDITION_CODE NOT IN('INTEGRATED','NG')
			--LEFT JOIN [dbo].[EWIP_SETUP_MINSTOCK] mins ON inv.SPARE_PART_CODE = mins.SPARE_PART_CODE AND mins.DEPT_CODE = @A_DEPARTMENT
			--LEFT JOIN [dbo].[EWIP_BOM] bom ON inv.SPARE_PART_CODE = bom.[SPARE_PART_CODE] AND bom.[DEPT_CODE] = @A_DEPARTMENT
			--LEFT JOIN [dbo].[EWIP_SPAREPART_TYPE] sp_type ON sp.TYPE = sp_type.CODE AND sp_type.DEPT_CODE = @A_DEPARTMENT
			--LEFT JOIN (SELECT TOP 1 WITH TIES 
			--			[SPARE_PART_CODE],
			--			[PRICE_VN],
			--			[PRICE_US], 
			--			[UNIT_CODE]
			--			FROM [dbo].[EWIP_SPAREPART_PRICE]
			--			WHERE [DEPT_CODE] = @A_DEPARTMENT
			--			ORDER BY ROW_NUMBER() OVER(PARTITION BY SPARE_PART_CODE ORDER BY [DATE] DESC)) SUB ON SUB.SPARE_PART_CODE = inv.SPARE_PART_CODE
			--LEFT JOIN (
			--				SELECT EO.PO_ID AS PO_NO,eprd.SPAREPART_CODE ,'Pack' as UNIT,eprd.DEPT_CODE,eprd.PRICE_VN/[dbo].[CONVERT_UNIT](eprd.UNIT,@PACK_UNIT,eprd.SPAREPART_CODE,@A_DEPARTMENT) AS PRICE_VN,eprd.PRICE_US/[dbo].[CONVERT_UNIT](eprd.UNIT,@PACK_UNIT,eprd.SPAREPART_CODE,@A_DEPARTMENT) AS PRICE_US
			--				FROM EWIP_ORDER eo
			--				INNER JOIN EWIP_ORDER_PR eop ON EO.PO_ID_TEMP = eop.PO_ID_TEMP
			--				INNER JOIN EWIP_PURCHASE_REQUEST epr ON EOP.PR_CODE = EPR.PR_CODE AND EOP.DEPT_CODE = EPR.DEPT_CODE
			--				INNER JOIN EWIP_PURCHASE_REQUEST_DETAIL eprd ON EPR.PR_CODE = eprd.PR_CODE AND EPR.DEPT_CODE = eprd.DEPT_CODE
			--		   ) SUB2 ON SUB2.SPAREPART_CODE = SPL.SPARE_PART_CODE AND SUB2.DEPT_CODE = SPL.DEPT_CODE AND SUB2.PO_NO = SPL.PO_NO

			--WHERE inv.DEPT_CODE = @A_DEPARTMENT and inv.STOCK_CODE = @A_STOCK_CODE


			SELECT ROW_NUMBER() OVER(ORDER BY ESL.SPARE_PART_CODE ASC) as STT,
			       ESL.SPARE_PART_CODE,SP.NAME_VI,SP.NAME_KR,
			       ROUND(SUM(ISNULL(ESL.QUANTITY,0) * ([dbo].[CONVERT_UNIT](esl.UNIT_ID,@PACK_UNIT,esl.SPARE_PART_CODE,@A_DEPARTMENT))),3) AS QUANTITY,
				   ISNULL(SUB2.PRICE_VN,SUB.PRICE_VN) as PRICE_VN,
				   ISNULL(SUB2.PRICE_US,SUB.PRICE_US) AS PRICE_US,
			       SUM(ISNULL(ESL.QUANTITY,0) * ([dbo].[CONVERT_UNIT](esl.UNIT_ID,@PACK_UNIT,esl.SPARE_PART_CODE,@A_DEPARTMENT)) * ISNULL(SUB2.PRICE_VN,SUB.PRICE_VN)) AS AMOUNT_VN,
				   SUM(ISNULL(ESL.QUANTITY,0) * ([dbo].[CONVERT_UNIT](esl.UNIT_ID,@PACK_UNIT,esl.SPARE_PART_CODE,@A_DEPARTMENT)) * ISNULL(SUB2.PRICE_US,SUB.PRICE_US)) AS AMOUNT_US, 
				   'PACK' AS UNIT,
				   sp_type.NAME AS SPARE_PART_TYPE,
				   [dbo].[CONVERT_UNIT](mins.UNIT_CODE,@PACK_UNIT,esl.SPARE_PART_CODE,@A_DEPARTMENT)*mins.MIN_STOCK as MIN_STOCK,
				   [dbo].[CONVERT_UNIT](bom.UNIT,@PACK_UNIT,esl.SPARE_PART_CODE,@A_DEPARTMENT)*bom.[WORKING_A_MONTH] AS WORKING_A_MONTH,
				   [dbo].[CONVERT_UNIT](sp.UNIT_ID,@PACK_UNIT,esl.SPARE_PART_CODE,@A_DEPARTMENT)*sp.[MIN_ORDER] AS MIN_ORDER,
				   V.NAME AS VENDER_ID,--SP.VENDER_ID,
				   SP.SP_DEPT_CODE AS DEPARTMENT
			FROM EWIP_SPAREPART_LOCATION esl
			INNER JOIN [dbo].[EWIP_SPARE_PART] sp ON esl.SPARE_PART_CODE = sp.CODE and ESL.DEPT_CODE = SP.SP_DEPT_CODE
			LEFT JOIN (
							SELECT EO.PO_ID AS PO_NO,eprd.SPAREPART_CODE ,'PACK' as UNIT,eprd.DEPT_CODE,eprd.PRICE_VN/[dbo].[CONVERT_UNIT](eprd.UNIT,@PACK_UNIT,eprd.SPAREPART_CODE,@A_DEPARTMENT) AS PRICE_VN,eprd.PRICE_US/[dbo].[CONVERT_UNIT](eprd.UNIT,@PACK_UNIT,eprd.SPAREPART_CODE,@A_DEPARTMENT) AS PRICE_US
							FROM EWIP_ORDER eo
							INNER JOIN EWIP_ORDER_PR eop ON EO.PO_ID_TEMP = eop.PO_ID_TEMP
							INNER JOIN EWIP_PURCHASE_REQUEST epr ON EOP.PR_CODE = EPR.PR_CODE AND EOP.DEPT_CODE = EPR.DEPT_CODE
							INNER JOIN EWIP_PURCHASE_REQUEST_DETAIL eprd ON EPR.PR_CODE = eprd.PR_CODE AND EPR.DEPT_CODE = eprd.DEPT_CODE
					   ) SUB2 ON SUB2.SPAREPART_CODE = esl.SPARE_PART_CODE AND SUB2.DEPT_CODE = esl.DEPT_CODE AND SUB2.PO_NO = esl.PO_NO
            LEFT JOIN [dbo].[EWIP_SPAREPART_TYPE] sp_type ON sp.TYPE = sp_type.CODE --AND sp_type.DEPT_CODE = @A_DEPARTMENT
			LEFT JOIN [dbo].[EWIP_BOM] bom ON esl.SPARE_PART_CODE = bom.[SPARE_PART_CODE] AND bom.[DEPT_CODE] = @A_DEPARTMENT
			LEFT JOIN [dbo].[EWIP_SETUP_MINSTOCK] mins ON esl.SPARE_PART_CODE = mins.SPARE_PART_CODE AND mins.DEPT_CODE = @A_DEPARTMENT
			LEFT JOIN (SELECT TOP 1 WITH TIES 
						[SPARE_PART_CODE],
						[PRICE_VN]/[dbo].[CONVERT_UNIT]([UNIT_CODE],@PACK_UNIT,[SPARE_PART_CODE],@A_DEPARTMENT) AS [PRICE_VN],
						[PRICE_US]/[dbo].[CONVERT_UNIT]([UNIT_CODE],@PACK_UNIT,[SPARE_PART_CODE],@A_DEPARTMENT) AS [PRICE_US], 
						@PACK_UNIT AS UNIT
						FROM [dbo].[EWIP_SPAREPART_PRICE]
						WHERE [DEPT_CODE] = @A_DEPARTMENT 
						ORDER BY ROW_NUMBER() OVER(PARTITION BY SPARE_PART_CODE ORDER BY [DATE] DESC)) SUB ON SUB.SPARE_PART_CODE = ESL.SPARE_PART_CODE
			LEFT JOIN EWIP_VENDER V ON V.VENDER_ID = SP.VENDER_ID
			WHERE ESL.DEPT_CODE = @A_DEPARTMENT AND ESL.STOCK_CODE = @A_STOCK_CODE AND esl.CONDITION_CODE NOT IN('INTEGRATED','NG')
			GROUP BY ESL.SPARE_PART_CODE,SP.NAME_VI,SP.NAME_KR,sp_type.NAME,  V.NAME, SP.SP_DEPT_CODE,mins.MIN_STOCK,mins.UNIT_CODE,bom.UNIT,bom.[WORKING_A_MONTH],sp.UNIT_ID,sp.[MIN_ORDER],SUB2.PRICE_VN,SUB2.PRICE_US,SUB.PRICE_VN,SUB.PRICE_US
 		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
