SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PKG_SYSTEM008@GET_LIST](
@A_PLANT			VARCHAR(50),
@A_USER_ID			VARCHAR(50),
@A_DEPARTMENT		VARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

DECLARE @V_MASTER_FLAG VARCHAR(1);

BEGIN TRY

	SET @V_MASTER_FLAG = (SELECT T1.MASTER_FLAG FROM ESYSMSTUSR T1 WHERE T1.USER_ID = @A_USER_ID and T1.DEPARTMENT = @A_DEPARTMENT)
	IF(@V_MASTER_FLAG = 'Y')
	BEGIN	
		SELECT CASE WHEN T2.USER_ID IS NULL THEN 'N'
					ELSE 'Y' END AS SEL,
			   T1.USERROLE,
			   T1.USERROLE_NAME
		FROM ESYSMSTROL T1 LEFT OUTER JOIN ESYSMSTURO T2 
		ON T2.USERROLE = T1.USERROLE AND T2.USER_ID = @A_USER_ID AND T2.PLANT = @A_PLANT AND T1.DEPARTMENT = T2.DEPARTMENT
	END
	ELSE
	BEGIN
		SELECT CASE WHEN T2.USER_ID IS NULL THEN 'N'
					ELSE 'Y' END AS SEL,
			   T1.USERROLE,
			   T1.USERROLE_NAME
		FROM ESYSMSTROL T1 LEFT OUTER JOIN ESYSMSTURO T2 
		ON T2.USERROLE = T1.USERROLE AND T2.USER_ID = @A_USER_ID AND T2.PLANT = @A_PLANT AND T1.DEPARTMENT = T2.DEPARTMENT 
		WHERE T1.USERROLE <> 'ROLE_ADMIN' AND T1.DEPARTMENT = @A_DEPARTMENT
	END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH








GO
