SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_VENDOR@PUT](
@A_VENDOR_ID NVARCHAR(50),
@A_VENDOR_NAME NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			IF NOT EXISTS(SELECT * FROM [dbo].[EWIP_VENDER] WHERE VENDER_ID = @A_VENDOR_ID)
			   INSERT INTO [dbo].[EWIP_VENDER]
			   VALUES(@A_VENDOR_ID,@A_VENDOR_NAME,NULL,NULL,NULL)

       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
