SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PR@INIT_LIST](
@A_DEPARTMENT		NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			SELECT DISTINCT PR.[PR_CODE],[MRP_CODE],SPO.PO_ID,[TOTAL_VALUE],[TOTAL_VALUE_US],PR.[DATE_CREATE],PR.[DATE_NEED_FINISH],PR.[DATE_END_ACTUAL],PR.[USER_CREATE],PR.[USER_UPDATE],PR.[DATE_UPDATE],[PR_STATUS]
			FROM [dbo].[EWIP_PURCHASE_REQUEST] PR
			LEFT JOIN [dbo].[EWIP_ORDER_PR] OPR ON PR.PR_CODE = OPR.PR_CODE AND PR.DEPT_CODE = OPR.DEPT_CODE
			LEFT JOIN [dbo].[EWIP_SAP_PO] SPO ON OPR.PO_ID = SPO.PO_ID
			WHERE PR.DEPT_CODE = @A_DEPARTMENT
			ORDER BY PR.[DATE_CREATE] DESC,PR.[DATE_NEED_FINISH] ASC
        END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
