SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_EQUIPMENT@DELETE](
@A_CODE             NVARCHAR(50),-- MA THIET BI
@A_DEPARTMENT		NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  

			DELETE FROM [dbo].[EWIP_EQUIPMENT]
			WHERE [EQUIPMENT_ID] = @A_CODE AND [DEPT_CODE] = @A_DEPARTMENT

			DELETE FROM [dbo].[EWIP_SPAREPART_DOCUMENT]
			WHERE [CODE] = @A_CODE AND [DEPT_CODE] = @A_DEPARTMENT

			DELETE [dbo].[EWIP_EQUIPMENT_BOM]
			WHERE [EQUIPMENT_ID] = @A_CODE AND [DEP_CODE] = @A_DEPARTMENT

			DELETE [dbo].[EWIP_EQUIPMENT_LOCATION_RELATION]
			WHERE [EQUIPMENT_ID] = @A_CODE AND [DEPT_CODE] = @A_DEPARTMENT
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH


GO
