SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_LOCATION@INSERT_BATCH_INVENTORY_REAL](
@A_DATA  SPAREPART_LOCATION_INVENTORY_TYPE1  READONLY, -- USING FOR IMPORT BUT NOT USE IN CURRENT
@A_DEPARTMENT_CODE NVARCHAR(50),
@A_STOCK NVARCHAR(50),
@A_USER NVARCHAR(50),
@A_TIME NVARCHAR(50),
@N_RETURN  int	OUTPUT,
@V_RETURN  NVARCHAR(4000) OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  

			BEGIN TRAN
			DECLARE @SPARE_PART_CODE  NVARCHAR(50)
			DECLARE @UNIT NVARCHAR(50)
			DECLARE @QUANTITY_REAL FLOAT
			DECLARE @INVENTORY_ASSETS_TIME NVARCHAR(50)
			DECLARE @DEPT_CODE NVARCHAR(50)
			DECLARE @STOCK_CODE NVARCHAR(50)

			DECLARE cursorInventory CURSOR FOR
			SELECT [SPARE_PART_CODE],'PACK' AS [UNIT],SUM([dbo].[CONVERT_UNIT](UNIT,'PACK',[SPARE_PART_CODE],@A_DEPARTMENT_CODE) * CAST([QUANTITY_REAL] AS float)) AS [QUANTITY_REAL],[INVENTORY_ASSETS_TIME],@A_DEPARTMENT_CODE AS [DEPT_CODE],@A_STOCK AS [STOCK_CODE]
			FROM @A_DATA
			GROUP BY [SPARE_PART_CODE],[INVENTORY_ASSETS_TIME]

			OPEN cursorInventory

			FETCH NEXT FROM cursorInventory
			INTO @SPARE_PART_CODE,@UNIT,@QUANTITY_REAL,@INVENTORY_ASSETS_TIME,@DEPT_CODE,@STOCK_CODE

			WHILE @@FETCH_STATUS = 0
							BEGIN
									IF @A_TIME <> '' AND @A_TIME IS NOT NULL
									    SET @INVENTORY_ASSETS_TIME = @A_TIME

							        DECLARE @dateAssets date = CAST(@INVENTORY_ASSETS_TIME AS DATE)
									DECLARE @YEAR INT= YEAR(@dateAssets)
									DECLARE @MONTH INT= MONTH(@dateAssets)

								   EXEC [dbo].[PKG_BUSINESS_INVENTORY_BY_TIME@PUT_QUANTITY_REAL]
										@A_DEPARTMENT = @DEPT_CODE,
										@A_STOCK       = @STOCK_CODE,
										@A_SPARE_PART_CODE = @SPARE_PART_CODE,
										@A_QUANTITY_REAL   = @QUANTITY_REAL,
										@A_UNIT            = @UNIT,
										@A_DATE			   =  @INVENTORY_ASSETS_TIME,
										@A_YEAR            = @YEAR,
										@A_MONTH		   = @MONTH,
										@A_QUANTITY        = -1,
										@A_USER            = @A_USER,
										@N_RETURN		   = @N_RETURN 	OUT,
										@V_RETURN		   = @V_RETURN	OUT

									IF @N_RETURN <> 0 
										THROW @N_RETURN, @V_RETURN, 1;

								   FETCH NEXT FROM cursorInventory
								   INTO @SPARE_PART_CODE,@UNIT,@QUANTITY_REAL,@INVENTORY_ASSETS_TIME,@DEPT_CODE,@STOCK_CODE
							END
		
					CLOSE cursorInventory
					DEALLOCATE cursorInventory
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
	COMMIT TRAN
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
  Rollback TRAN
END CATCH
GO
