SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP_INVENTORY@REPORT_BY_DAY_INVENTORY](
@A_DEPARTMENT		NVARCHAR(50),
@A_TIME_FROM        NVARCHAR(50),
@A_TIME_TO          NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  

			IF cast(GETDATE() as date) >= CAST(@A_TIME_FROM AS DATE) AND cast(GETDATE() as date) <= CAST(@A_TIME_TO AS DATE)
			   BEGIN
						EXEC [dbo].[PKG_BUSINESS_LOCATION@BASE_LINE_RUN_TIME]
						     @A_DEPT_CODE = @A_DEPARTMENT,
							 @N_RETURN = @N_RETURN OUTPUT,
							 @V_RETURN =@V_RETURN OUTPUT
			   END

			SELECT [DATE],CAST([WEEK] AS NVARCHAR) AS [WEEK],CAST(DATEPART(dw,[DATE]) AS NVARCHAR) AS [WEEKDAY],CAST(MONTH([DATE]) AS NVARCHAR) AS 'MONTHS',CAST([QUARTER] AS NVARCHAR) AS [QUARTER],[SPARE_PART_CODE],SP.NAME_VI,SP.NAME_KR,[IN_VALUES_VN],[OUT_VALUES_VN],[INVENTORY_VALUES_VN],[IN_VALUES_US],[OUT_VALUES_US],[INVENTORY_VALUES_US],[QUANTITY_IN],[QUANTITY_OUT],[QUANTITY_INVENTORY],[QTY_INVENTORY_INCLUDE],[UNIT],
			T.NAME AS 'PHAN LOAI'
			FROM [dbo].[EWIP_INVENTORY_QTY_VALUE_BY_DAY] D
			INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON D.SPARE_PART_CODE = SP.CODE AND D.DEPT_CODE = SP.SP_DEPT_CODE
			LEFT JOIN [dbo].[EWIP_SPAREPART_TYPE] T ON SP.TYPE = T.CODE
			WHERE [DATE] BETWEEN CAST(@A_TIME_FROM AS DATE) AND CAST(@A_TIME_TO AS DATE) AND [DEPT_CODE] = @A_DEPARTMENT
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
