SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_GOODS_RECEIPT_ISSUE@HISTORY](
@A_DEPT_CODE NVARCHAR(50),
@A_STOCK_CODE NVARCHAR(50),
@N_RETURN	int				OUTPUT,
@V_RETURN	NVARCHAR(50)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			     SELECT * FROM [dbo].[EWIP_HISTORY_INVENTORY] A
				 INNER JOIN [dbo].[EWIP_INVENTORY_DELIVERY_RECEIVING] ON CODE_NO = [STOCK_IN_OUT_CODE]
				 WHERE A.DEPT_CODE = @A_DEPT_CODE AND A.STOCK_CODE = @A_STOCK_CODE
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH

GO
