SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP@DELETE](
@A_CODE				VARCHAR(50),
@A_DEPARTMENT		VARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
DECLARE @V_CHECK  TINYINT = 0;

BEGIN TRY
	
	SELECT @V_CHECK = COUNT(*) FROM EWIP_SPARE_PART WHERE CODE = @A_CODE AND [SP_DEPT_CODE] = @A_DEPARTMENT

	IF @V_CHECK > 0
		BEGIN	    
		    DELETE [dbo].[EWIP_SPARE_PART] WHERE CODE = @A_CODE AND [SP_DEPT_CODE] = @A_DEPARTMENT
			DELETE [dbo].[EWIP_SPARE_PART_DEPT]  WHERE [SPARE_PART_CODE] = @A_CODE AND [DEPT_CODE] = @A_DEPARTMENT
            DELETE [dbo].[EWIP_SPAREPART_UNIT] WHERE [SPARE_PART_CODE] = @A_CODE AND [DEPT_CODE] = @A_DEPARTMENT
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
