SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PKG_SYSTEM005@PUT_ITEM](
@A_PLANT			VARCHAR(50),
@A_USER_ID			VARCHAR(20),
@A_PASSWORD			NVARCHAR(200),
@A_USER_NAME		NVARCHAR(100),
@A_PHONE_NUM		NVARCHAR(30),
@A_EMAIL			NVARCHAR(100),
@A_USEFLAG			VARCHAR(1),
@A_REMARKS			NVARCHAR(4000),
@A_TRAN_USER_ID		VARCHAR(30),
@A_DEPARTMENT		VARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

DECLARE	@V_TRAN_TIME	VARCHAR(14);
DECLARE	@V_CHECK		INT;
DECLARE	@V_MASTER_FLAG	VARCHAR(5);



BEGIN TRY
	SET @V_TRAN_TIME = dbo.FUN_CURR_TIME();
	SET @V_CHECK = 0;

	SELECT @V_CHECK = COUNT(*)
    FROM ESYSMSTUSR T1
    WHERE T1.PLANT = @A_PLANT
    AND T1.USER_ID = @A_USER_ID
	AND T1.DEPARTMENT = @A_DEPARTMENT
	;

	BEGIN TRAN
		IF @V_CHECK != 0 
			BEGIN
				SET @V_MASTER_FLAG = (SELECT T1.MASTER_FLAG FROM ESYSMSTUSR T1 WHERE T1.USER_ID = @A_TRAN_USER_ID)
				IF(@V_MASTER_FLAG = 'Y')
				BEGIN	
					UPDATE ESYSMSTUSR
					SET USER_NAME = @A_USER_NAME,
						PASSWORD = @A_PASSWORD,
						PHONE_NUM = @A_PHONE_NUM,
						EMAIL = @A_EMAIL,
						USEFLAG = @A_USEFLAG,
						REMARKS = @A_REMARKS,
						UPDATE_TIME = @V_TRAN_TIME,
						UPDATE_USER = @A_TRAN_USER_ID,
						DEPARTMENT = @A_DEPARTMENT
					WHERE  USER_ID = @A_USER_ID
				END
				ELSE
					BEGIN
						UPDATE ESYSMSTUSR
						SET USER_NAME = @A_USER_NAME,
							PASSWORD = @A_PASSWORD,
							PHONE_NUM = @A_PHONE_NUM,
							EMAIL = @A_EMAIL,
							USEFLAG = @A_USEFLAG,
							REMARKS = @A_REMARKS,
							UPDATE_TIME = @V_TRAN_TIME,
							UPDATE_USER = @A_TRAN_USER_ID,
							DEPARTMENT = @A_DEPARTMENT
						WHERE PLANT = @A_PLANT
						AND USER_ID = @A_USER_ID
						AND DEPARTMENT = @A_DEPARTMENT;
					END
			END
		ELSE
			BEGIN
				INSERT INTO ESYSMSTUSR (
					PLANT,
					DEPARTMENT,
					USER_ID,
					PASSWORD,
					USER_NAME,
					PHONE_NUM,
					EMAIL,
					USEFLAG,
					REMARKS,
					CREATE_TIME,
					CREATE_USER
				) VALUES (
					@A_PLANT,
					@A_DEPARTMENT,
					@A_USER_ID,
					@A_PASSWORD,
					@A_USER_NAME,
					@A_PHONE_NUM,
					@A_EMAIL,
					@A_USEFLAG,
					@A_REMARKS,
					@V_TRAN_TIME,
					@A_TRAN_USER_ID
				);
			END
	COMMIT TRAN;

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_001';
END TRY
BEGIN CATCH

	rollback tran;
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH








GO
