SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_GOODS_RECEIPT_ISSUE@INIT](
@A_STOCK_INT_OUT_CODE NVARCHAR(50),
@A_DEPT_CODE NVARCHAR(50),
@A_STOCK_CODE NVARCHAR(50),
@A_INOUT      NVARCHAR(50),
@N_RETURN	int				OUTPUT,
@V_RETURN	NVARCHAR(50)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			IF @A_INOUT = 'IN'
			 BEGIN
				SELECT IDR.CODE_NO as RECEIPT_ISSUE_CODE,SPIN.SPARE_PART_CODE,SPIN.QUANTITY,SPIN.UNIT_CODE AS UNIT,SPIN.PRICE_VN,SPIN.PRICE_US,SPIN.AMOUNT_VN,SPIN.AMOUNT_US,SPIN.CAUSE,SPIN.NOTE,
			       SPIN.STOCK_CODE,IDR.DEPT_CODE,'' AS [LOCATION],NULL AS [RETURN_TIME],SPIN.TYPE_IN_CODE as TYPE_IN_OUT_CODE,IDR.DATE as CREATE_DATE,SP.NAME_VI,SPIN.[QUANTITY_NG],SPIN.[EXPRIRED_DATE],SPIN.[IS_INTEGRATED]
				FROM [dbo].[EWIP_INVENTORY_DELIVERY_RECEIVING] IDR 
				INNER JOIN [dbo].[EWIP_SP_STOCKIN] SPIN ON IDR.CODE_NO = SPIN.STOCK_IN_CODE and IDR.DEPT_CODE = SPIN.DEPT_CODE
				LEFT JOIN [dbo].[EWIP_SPARE_PART] SP ON SPIN.SPARE_PART_CODE = SP.CODE AND SP.SP_DEPT_CODE = SPIN.DEPT_CODE
				WHERE IDR.DEPT_CODE = @A_DEPT_CODE AND IDR.CODE_NO = @A_STOCK_INT_OUT_CODE AND IDR.STOCK_CODE = @A_STOCK_CODE

				SELECT IDR.STOCK_CODE,SPIN.TYPE_IN_CODE,IDR.ORDER_CODE,IDR.USER_CREATE,IDR.DATE,IDR.STATUS,IDR.[DELIVERET_RECEIVER]
				FROM [dbo].[EWIP_INVENTORY_DELIVERY_RECEIVING] IDR  
				INNER JOIN [dbo].[EWIP_SP_STOCKIN] SPIN ON IDR.CODE_NO = SPIN.STOCK_IN_CODE AND IDR.DEPT_CODE = SPIN.DEPT_CODE
				WHERE IDR.DEPT_CODE = @A_DEPT_CODE AND IDR.CODE_NO = @A_STOCK_INT_OUT_CODE AND IDR.STOCK_CODE = @A_STOCK_CODE
			 END
			 ELSE
			   BEGIN
				   SELECT IDR.CODE_NO as RECEIPT_ISSUE_CODE,SPIN.SPARE_PART_CODE,SPIN.[QUANTITY],SPIN.[UNIT_ID] AS UNIT,NULL AS PRICE_VN,NULL AS PRICE_US,NULL AS AMOUNT_VN,NULL AS AMOUNT_US,SPIN.CAUSE,'' AS NOTE,
				       SPIN.STOCK_CODE,IDR.DEPT_CODE,SPIN.[LOCATION],[RETURN_TIME], SPIN.TYPE_OUT_CODE as TYPE_IN_OUT_CODE,IDR.DATE as CREATE_DATE,SP.NAME_VI,0 AS QUANTITY_NG,NULL AS EXPRIRED_DATE, NULL AS IS_INTEGRATED
					FROM [dbo].[EWIP_INVENTORY_DELIVERY_RECEIVING] IDR 
					INNER JOIN [dbo].[EWIP_STOCK_OUT] SPIN ON IDR.CODE_NO = SPIN.STOCK_OUT_CODE AND IDR.DEPT_CODE = SPIN.DEPT_CODE
					LEFT JOIN [dbo].[EWIP_SPARE_PART] SP ON SPIN.SPARE_PART_CODE = SP.CODE AND SPIN.DEPT_CODE = SP.SP_DEPT_CODE
					WHERE IDR.DEPT_CODE = @A_DEPT_CODE AND IDR.CODE_NO = @A_STOCK_INT_OUT_CODE AND IDR.STOCK_CODE = @A_STOCK_CODE

					SELECT IDR.STOCK_CODE,SPIN.TYPE_OUT_CODE as TYPE_IN_CODE,IDR.ORDER_CODE,IDR.USER_CREATE,IDR.DATE,IDR.STATUS,IDR.[DELIVERET_RECEIVER]
					FROM [dbo].[EWIP_INVENTORY_DELIVERY_RECEIVING] IDR  
					INNER JOIN [dbo].[EWIP_STOCK_OUT] SPIN ON IDR.CODE_NO = SPIN.STOCK_OUT_CODE AND IDR.DEPT_CODE = SPIN.DEPT_CODE
					WHERE IDR.DEPT_CODE = @A_DEPT_CODE AND IDR.CODE_NO = @A_STOCK_INT_OUT_CODE AND IDR.STOCK_CODE = @A_STOCK_CODE
			   END
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH

GO
