SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_LOCATION@DELETE](
@A_CODE             NVARCHAR(50),
@A_DEPARTMENT       NVARCHAR(100),
@A_STOCK            VARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
		    begin TRAN;
			DELETE FROM [dbo].[EWIP_LOCATIONS] WHERE CODE = @A_CODE AND STOCK_CODE = @A_STOCK AND DEPT_CODE = @A_DEPARTMENT
			DELETE FROM [dbo].[EWIP_SPAREPART_LOCATION]  WHERE [LOCATION_CODE] = @A_CODE AND STOCK_CODE = @A_STOCK AND DEPT_CODE = @A_DEPARTMENT
			COMMIT TRAN;
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
  ROLLBACK TRAN;
END CATCH
GO
