SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP_INVENTORY@CHECK_INVENTORY_ALARM](
@A_DEPARTMENT		NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  

		    SELECT *
			FROM [dbo].[EWIP_SPAREPART_INVENTORY] inv
			INNER JOIN [dbo].[EWIP_SPARE_PART] sp ON inv.SPARE_PART_CODE = sp.CODE
			LEFT JOIN [dbo].[EWIP_SETUP_MINSTOCK] mins ON inv.SPARE_PART_CODE = mins.SPARE_PART_CODE AND inv.DEPT_CODE = mins.DEPT_CODE AND inv.STOCK_CODE =mins.STOCK_CODE
			WHERE inv.DEPT_CODE = @A_DEPARTMENT AND inv.QUANTITY <= [dbo].[CONVERT_UNIT](mins.UNIT_CODE,inv.UNIT_IN_CODE,inv.SPARE_PART_CODE,@A_DEPARTMENT)* mins.MIN_STOCK
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH

GO
