SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP_INVENTORY@PUT](
@A_DEPARTMENT		NVARCHAR(50),
@A_STOCK            VARCHAR(50),
@A_SPARE_PART_CODE  NVARCHAR(50),
@A_QUANTITY         FLOAT,
@A_QUANTITY_REAL    FLOAT,
@A_UNIT             VARCHAR(20),
@A_USER             NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			DECLARE @CHECK1 int;
			DECLARE @CHECK2 int;

			IF(@A_QUANTITY_REAL < 0)
				SET @A_QUANTITY_REAL = NULL; 
			

			SELECT @CHECK1 = COUNT(*) FROM [dbo].[EWIP_SPAREPART_INVENTORY] WHERE [SPARE_PART_CODE] = @A_SPARE_PART_CODE AND [DEPT_CODE] = @A_DEPARTMENT AND STOCK_CODE = @A_STOCK
			SELECT @CHECK2 = COUNT(*) 
			FROM [dbo].[EWIP_INVENTORY_BY_TIME] 
			WHERE [SPARE_PART_CODE] = @A_SPARE_PART_CODE AND [DEPT_CODE] = @A_DEPARTMENT AND STOCK_CODE = @A_STOCK AND [MONTH] = MONTH(GETDATE()) AND [YEAR]=YEAR(GETDATE())

			IF @CHECK1 > 0
			    BEGIN
					UPDATE [dbo].[EWIP_SPAREPART_INVENTORY] SET QUANTITY = @A_QUANTITY , QUANTITY_REAL = @A_QUANTITY_REAL,UNIT_IN_CODE = @A_UNIT,UPDATE_DATE = GETDATE(),[USER_UPDATE] = @A_USER
					WHERE [SPARE_PART_CODE] = @A_SPARE_PART_CODE AND [DEPT_CODE] = @A_DEPARTMENT AND STOCK_CODE = @A_STOCK
				END
			ELSE
			    BEGIN
					INSERT INTO [dbo].[EWIP_SPAREPART_INVENTORY]
					VALUES(@A_SPARE_PART_CODE,@A_QUANTITY,@A_UNIT,@A_QUANTITY_REAL,@A_DEPARTMENT,@A_STOCK,GETDATE(),GETDATE(),@A_USER)
				END

			DECLARE @PRICE_VN float
			DECLARE @PRICE_US float

			SELECT TOP 1 @PRICE_VN = PRICE_VN/[dbo].[CONVERT_UNIT]([UNIT_CODE],@A_UNIT,SPARE_PART_CODE,@A_DEPARTMENT) ,@PRICE_US = PRICE_US/[dbo].[CONVERT_UNIT]([UNIT_CODE],@A_UNIT,SPARE_PART_CODE,@A_DEPARTMENT) 
			FROM [dbo].[EWIP_SPAREPART_PRICE]
			WHERE [SPARE_PART_CODE] = @A_SPARE_PART_CODE AND DEPT_CODE = @A_DEPARTMENT AND CAST(GETDATE() AS date) >=  [DATE]
			ORDER BY [DATE] DESC

			IF @CHECK2 > 0 
				   UPDATE [dbo].[EWIP_INVENTORY_BY_TIME] 
				   SET QUANTITY = @A_QUANTITY , QUANTITY_REAL = @A_QUANTITY_REAL,UNIT = @A_UNIT,[DATE]= GETDATE(),[YEAR] = YEAR(GETDATE()),[MONTH]=MONTH(GETDATE()),
				   [PRICE_VN] = @PRICE_VN,[PRICE_US] = @PRICE_US 
				   WHERE [SPARE_PART_CODE] = @A_SPARE_PART_CODE AND [DEPT_CODE] = @A_DEPARTMENT AND STOCK_CODE = @A_STOCK AND [MONTH] = MONTH(GETDATE()) AND [YEAR]=YEAR(GETDATE())
				ELSE
				  BEGIN
				   INSERT INTO [dbo].[EWIP_INVENTORY_BY_TIME]
				   VALUES(@A_SPARE_PART_CODE,@A_QUANTITY,@A_UNIT,@A_DEPARTMENT,@A_STOCK,GETDATE(),MONTH(GETDATE()),YEAR(GETDATE()),@A_QUANTITY_REAL,@PRICE_VN,@PRICE_US)
				 END
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
