SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_MRP@DETACK_ALL_MRP](
@A_DEPT_CODE        NVARCHAR(50),
@A_USER            NVARCHAR(50),
@A_MRP             NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		     UPDATE [dbo].[EWIP_MRP]
			 SET [MRP_CODE] = NULL,[DATE_UPDATE] = GETDATE(),USER_UPDATE = @A_USER
			 WHERE [MRP_CODE] = @A_MRP AND DEPT_CODE = @A_DEPT_CODE
			 
			 DELETE FROM [dbo].[EWIP_PURCHASE_REQUEST_DETAIL]
			 WHERE MRP_CODE = @A_MRP AND DEPT_CODE = @A_DEPT_CODE

        END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
