SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_MRP_PLAN@PUT](
@A_DEPARTMENT		NVARCHAR(50),
@A_MRP_CODE         NVARCHAR(50),
@A_USER             NVARCHAR(50),
@A_DATA             [dbo].[EWIP_MRP_TYPE] READONLY,
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN

			DECLARE @CHECK nvarchar(50)
			DECLARE @DATE_NEED_FINISH nvarchar(50)
		    -- MRP-20210728-001
		   BEGIN TRAN
		   SELECT @CHECK = COUNT(*) 
		   FROM [dbo].[EWIP_MRP_LIST]
		   WHERE [MRP_CODE] = @A_MRP_CODE AND [DEPT_CODE] = @A_DEPARTMENT

		   SELECT TOP 1 @DATE_NEED_FINISH = [DATE_NEED_FINISH]
		   FROM @A_DATA
		   ORDER BY [DATE_NEED_FINISH] DESC

		   IF @CHECK > 0
		     BEGIN
				UPDATE [dbo].[EWIP_MRP_LIST]
				SET [USER_UPDATE] = @A_USER,[DATE_UPDATE] = GETDATE(),DATE_NEED_FINISH = CAST(@DATE_NEED_FINISH AS date)
				WHERE [MRP_CODE] = @A_MRP_CODE AND [DEPT_CODE] = @A_DEPARTMENT

				DELETE [dbo].[EWIP_MRP]
				WHERE [ID] IN (SELECT ID FROM @A_DATA)

				UPDATE [dbo].[EWIP_MRP]
				SET MRP_CODE = NULL , [USER_UPDATE] = @A_USER ,[DATE_UPDATE] = GETDATE()
				WHERE [MRP_CODE] = @A_MRP_CODE AND DEPT_CODE = @A_DEPARTMENT

				INSERT INTO [dbo].[EWIP_MRP]
				SELECT [SPAREPART_CODE],[QUANTITY_NEED_BUY],[UNIT],[STATUS],[MRP_CODE],[DEPT_CODE],CAST([DATE_NEED_BUY] AS date),CAST([DATE_NEED_FINISH] AS date),CAST([DATE_END_ACTUAL] AS date),@A_USER,CAST([DATE_UPDATE] AS date),[OFF_NOTI],CAST([DATE_NEED_REQUIRED] AS date)
				FROM @A_DATA

				DELETE [dbo].[EWIP_PURCHASE_REQUEST_DETAIL]
				WHERE [MRP_CODE] = @A_MRP_CODE AND [DEPT_CODE] = @A_DEPARTMENT AND [SPAREPART_CODE] NOT IN(SELECT [SPAREPART_CODE] FROM @A_DATA)

				DECLARE @MRP_CS NVARCHAR(50)
				DECLARE @SPAREPART_CODE_CS NVARCHAR(50)
				DECLARE @QUANTITY_NEED_BUY_CS FLOAT
				DECLARE @UNIT_CS NVARCHAR(50)
				DECLARE @STATUS_CS NVARCHAR(50)
				DECLARE @DATE_NEED_FINISH_CS NVARCHAR(50)

				DECLARE cursor_data CURSOR FOR
				SELECT [MRP_CODE],[SPAREPART_CODE],[QUANTITY_NEED_BUY],[UNIT],[STATUS],[DATE_NEED_FINISH]
				FROM @A_DATA

				OPEN cursor_data

				FETCH NEXT FROM cursor_data
				INTO @MRP_CS,@SPAREPART_CODE_CS,@QUANTITY_NEED_BUY_CS,@UNIT_CS,@STATUS_CS,@DATE_NEED_FINISH_CS

				 DECLARE @PRICE_VN FLOAT
				 DECLARE @PRICE_US FLOAT
				 DECLARE @UNIT_PRICE NVARCHAR(50)
				 DECLARE @CHECK_EXIST INT
				 DECLARE @VENDORID NVARCHAR(50)
				 DECLARE @PR_CODE NVARCHAR(50)
				 DECLARE @TOTAL_US FLOAT =  0
				 DECLARE @TOTAL_VN FLOAT = 0

				WHILE @@FETCH_STATUS = 0
					 BEGIN
						 
						 SET @PRICE_VN = 0
						 SET @PRICE_US = 0
						 SET @CHECK_EXIST = 0

						 SELECT @CHECK_EXIST = COUNT(*)
						 FROM [dbo].[EWIP_PURCHASE_REQUEST_DETAIL]
						 WHERE [MRP_CODE] = @MRP_CS AND [DEPT_CODE] = @A_DEPARTMENT AND [SPAREPART_CODE] = @SPAREPART_CODE_CS

						 SELECT TOP 1 @PRICE_VN = ISNULL([PRICE_VN],0),@PRICE_US = ISNULL([PRICE_US],0),@UNIT_PRICE = UNIT_CODE
						 FROM [dbo].[EWIP_SPAREPART_PRICE]
						 WHERE [SPARE_PART_CODE] = @SPAREPART_CODE_CS AND [DEPT_CODE] = @A_DEPARTMENT
						 ORDER BY [DATE] DESC

						 SET @QUANTITY_NEED_BUY_CS = ISNULL(@QUANTITY_NEED_BUY_CS,0)

						 SET @TOTAL_VN += @PRICE_VN * ISNULL(@QUANTITY_NEED_BUY_CS,0)
						 SET @TOTAL_US += @PRICE_US * ISNULL(@QUANTITY_NEED_BUY_CS,0)

						 IF @CHECK_EXIST > 0
						    BEGIN
								 UPDATE [dbo].[EWIP_PURCHASE_REQUEST_DETAIL]
								 SET [QUANTITY_NEED_BUY] = ISNULL(@QUANTITY_NEED_BUY_CS,0) , [UNIT] = @UNIT_CS,[DATE_NEED_FINISH] = @DATE_NEED_FINISH_CS,[STATUS] = @STATUS_CS,
								     [PRICE_VN] = @PRICE_VN/[dbo].[CONVERT_UNIT](@UNIT_PRICE,@UNIT_CS,@SPAREPART_CODE_CS,@A_DEPARTMENT),
									  [PRICE_US] = @PRICE_US/[dbo].[CONVERT_UNIT](@UNIT_PRICE,@UNIT_CS,@SPAREPART_CODE_CS,@A_DEPARTMENT),
									  [TOTAL_MONEY_VN] = (@PRICE_VN/[dbo].[CONVERT_UNIT](@UNIT_PRICE,@UNIT_CS,@SPAREPART_CODE_CS,@A_DEPARTMENT)) * ISNULL(@QUANTITY_NEED_BUY_CS,0),
									  [TOTAL_MONEY_US] = (@PRICE_US/[dbo].[CONVERT_UNIT](@UNIT_PRICE,@UNIT_CS,@SPAREPART_CODE_CS,@A_DEPARTMENT)) * ISNULL(@QUANTITY_NEED_BUY_CS,0),
									 [EXPECTED_PRICE_VN] = @PRICE_VN/[dbo].[CONVERT_UNIT](@UNIT_PRICE,@UNIT_CS,@SPAREPART_CODE_CS,@A_DEPARTMENT),
									 [EXPECTED_PRICE_US]=@PRICE_US/[dbo].[CONVERT_UNIT](@UNIT_PRICE,@UNIT_CS,@SPAREPART_CODE_CS,@A_DEPARTMENT)
								 WHERE [MRP_CODE] = @MRP_CS AND [DEPT_CODE] = @A_DEPARTMENT AND [SPAREPART_CODE] = @SPAREPART_CODE_CS
							END
						 ELSE
						    BEGIN
									SELECT @VENDORID = VENDER_ID
									FROM EWIP_SPARE_PART
									WHERE CODE = @SPAREPART_CODE_CS AND SP_DEPT_CODE = @A_DEPARTMENT

									SELECT @PR_CODE = [PR_CODE]
									FROM [dbo].[EWIP_PURCHASE_REQUEST]
									WHERE MRP_CODE = @A_MRP_CODE AND DEPT_CODE = @A_DEPARTMENT

									INSERT INTO [dbo].[EWIP_PURCHASE_REQUEST_DETAIL]
									VALUES(@MRP_CS,@SPAREPART_CODE_CS,@A_DEPARTMENT,@QUANTITY_NEED_BUY_CS,@UNIT_CS,@PRICE_VN,@PRICE_VN,@PRICE_VN*@QUANTITY_NEED_BUY_CS,@VENDORID,@PR_CODE,@DATE_NEED_FINISH_CS,@A_USER,GETDATE(),GETDATE(),@STATUS_CS,@PRICE_US,@PRICE_US,@PRICE_US*@QUANTITY_NEED_BUY_CS)
							END

						  FETCH NEXT FROM cursor_data
						  INTO @MRP_CS,@SPAREPART_CODE_CS,@QUANTITY_NEED_BUY_CS,@UNIT_CS,@STATUS_CS,@DATE_NEED_FINISH_CS
					 END

				IF EXISTS(SELECT * FROM [dbo].[EWIP_PURCHASE_REQUEST] WHERE MRP_CODE = @A_MRP_CODE AND DEPT_CODE = @A_DEPARTMENT)
				    UPDATE [dbo].[EWIP_PURCHASE_REQUEST]
					SET [TOTAL_VALUE] = @TOTAL_VN,TOTAL_VALUE_US = @TOTAL_US,USER_UPDATE = @A_USER,DATE_UPDATE = GETDATE()
					WHERE MRP_CODE = @A_MRP_CODE AND DEPT_CODE = @A_DEPARTMENT

					CLOSE cursor_data
					DEALLOCATE cursor_data
			 END
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
	COMMIT TRAN
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
  ROLLBACK TRAN
END CATCH
GO
