SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PKG_SYSTEM001@INT_LIST](
@A_PLANT			VARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
	
	SELECT T.GLSR AS GLSR,
			T.VTN AS VTN,
			T.KOR AS KOR
    FROM ESYSMSTGLA T
    WHERE T.PLANT = @A_PLANT
	--AND T.USE_FLAG = 'Y'
	--AND CREATE_TIME LIKE '202007%' OR CREATE_TIME LIKE '202006%' OR CREATE_TIME LIKE '202008%' 
    ORDER BY T.GLSR ASC;

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH








GO
