SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_MRP@UPDATE_STATUS](
@A_PR_CODE NVARCHAR(50),
@A_MRP_CODE NVARCHAR(50),
@A_SPARE_PART_CODE NVARCHAR(50),
@A_STATUS NVARCHAR(50),
@A_DEPARTMENT NVARCHAR(50),
@A_USER NVARCHAR(50),
@A_DATE_END_ACTUAL NVARCHAR(50),
@N_RETURN	int				OUTPUT,
@V_RETURN	NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		        IF @A_DATE_END_ACTUAL = ''
				    SET @A_DATE_END_ACTUAL = NULL

		   		UPDATE [dbo].[EWIP_MRP]
				SET STATUS = @A_STATUS,[DATE_UPDATE] = SYSDATETIME(), USER_UPDATE = @A_USER,DATE_END_ACTUAL = cast(@A_DATE_END_ACTUAL as date)
				WHERE SPAREPART_CODE = @A_SPARE_PART_CODE AND MRP_CODE=@A_MRP_CODE AND DEPT_CODE = @A_DEPARTMENT

				UPDATE [dbo].[EWIP_PURCHASE_REQUEST_DETAIL]
				SET STATUS = @A_STATUS ,DATE_UPDATE = SYSDATETIME(),USER_UPDATE = @A_USER
				WHERE MRP_CODE = @A_MRP_CODE AND DEPT_CODE = @A_DEPARTMENT AND SPAREPART_CODE = @A_SPARE_PART_CODE AND ISNULL(PR_CODE,'') = ISNULL(@A_PR_CODE,'')

				CREATE TABLE #TEMP_MRP(STATUS NVARCHAR(50))

				INSERT INTO #TEMP_MRP
				SELECT DISTINCT STATUS FROM [dbo].[EWIP_MRP] WHERE MRP_CODE=@A_MRP_CODE AND DEPT_CODE = @A_DEPARTMENT

				DECLARE @STATUS_FINAL NVARCHAR(50)
				DECLARE @COUNT_STATUS INT  = 0

				SELECT @COUNT_STATUS = COUNT(*) FROM #TEMP_MRP
				SELECT @STATUS_FINAL = STATUS FROM #TEMP_MRP

				 UPDATE [dbo].[EWIP_MRP_LIST]
				 SET STATUS = 'COMPLETE', USER_UPDATE = @A_USER , DATE_UPDATE = SYSDATETIME()
				 WHERE MRP_CODE = @A_MRP_CODE AND 
				       DEPT_CODE = @A_DEPARTMENT AND 
					   @COUNT_STATUS = 1 AND @STATUS_FINAL = 'COMPLETE'

				UPDATE [dbo].[EWIP_PURCHASE_REQUEST]
				SET PR_STATUS = 'COMPLETE',DATE_UPDATE = SYSDATETIME(), USER_UPDATE = @A_USER
				WHERE MRP_CODE = @A_MRP_CODE AND DEPT_CODE = @A_DEPARTMENT AND @COUNT_STATUS = 1 AND @STATUS_FINAL = 'COMPLETE' AND PR_CODE = @A_PR_CODE
				
				DECLARE @STATUS_PR NVARCHAR(50)
				SELECT @STATUS_PR = [PR_STATUS]
				FROM [dbo].[EWIP_PURCHASE_REQUEST]
				WHERE DEPT_CODE = @A_DEPARTMENT AND PR_CODE = @A_PR_CODE
				
				UPDATE [dbo].[EWIP_ORDER_PR]
				SET  STATUS = @STATUS_PR,DATE_UPDATE = SYSDATETIME() , USER_UPDATE = @A_USER
				WHERE PR_CODE = @A_PR_CODE AND DEPT_CODE = @A_DEPARTMENT
				
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
