SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_LABEL@GET_TEMP](
@A_CODE_TEMP       NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
           
			IF NOT EXISTS(SELECT [LABEL] FROM [dbo].[EWIP_LABEL] WHERE CODE = @A_CODE_TEMP)
			    SELECT [LABEL]  FROM [dbo].[EWIP_LABEL] WHERE CODE = 'QRCODE'
			ELSE
			    SELECT [LABEL]  FROM [dbo].[EWIP_LABEL] WHERE CODE = @A_CODE_TEMP
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
