SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP@SEARCH](
@A_DEPARTMENT		NVARCHAR(50),
@A_CODE             NVARCHAR(50), 
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			SELECT sp.CODE,sp.NAME_VI,sp.NAME_KR,SP.DESCRIPTION,sp.GL_ACCOUNT,spd.COST_CTR,V.NAME as VENDER_NAME,u.CODE AS UNIT, T.NAME AS TYPENAME
			FROM EWIP_SPARE_PART sp 
			     INNER JOIN EWIP_SPARE_PART_DEPT spd ON sp.CODE = spd.SPARE_PART_CODE AND spd.DEPT_CODE = @A_DEPARTMENT
				 INNER JOIN EWIP_VENDER v ON SP.VENDER_ID = V.VENDER_ID
				 INNER JOIN EWIP_UNITS u ON SP.UNIT_ID = u.CODE
				 LEFT JOIN EWIP_SPAREPART_TYPE T ON SP.TYPE = T.CODE -- AND T.DEPT_CODE = @A_DEPARTMENT
			WHERE sp.CODE = @A_CODE
			ORDER BY SP.ID DESC;
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
