SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_MRP@INIT](
@A_DEPARTMENT		NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			SELECT  [MRP_CODE],[TITLE]
			FROM [dbo].[EWIP_MRP_LIST]
			WHERE [DEPT_CODE] = @A_DEPARTMENT AND [STATUS] IN('NEW','WAIT_ACCEPT','ACCEPT')

			SELECT CODE,NAME FROM [dbo].[EWIP_UNITS]

			SELECT CODE,NAME_VI FROM [dbo].[EWIP_SPARE_PART] WHERE SP_DEPT_CODE = @A_DEPARTMENT

			SELECT CODE,NAME FROM [dbo].[EWIP_STATUS_PUR]

			SELECT DISTINCT [SPAREPART_CODE],SP.NAME_VI,[QUANTITY_NEED_BUY],[UNIT],[MRP_CODE],[DATE_NEED_REQUIRED],[DATE_NEED_BUY],[DATE_NEED_FINISH],[DATE_END_ACTUAL],ISNULL(SUB.SUB_QTY_NEED_BUY,0) *[dbo].[CONVERT_UNIT](SUB.SUB_UNIT,MRP.UNIT,MRP.SPAREPART_CODE,MRP.DEPT_CODE) AS SUB_QTY_NEED_BUY,ISNULL(SUB.SUB_DATE_NEED_FINISH,'') AS SUB_DATE_NEED_FINISH,[DEPT_CODE],USER_UPDATE as [USER],[STATUS],[OFF_NOTI],MRP.ID
			FROM [dbo].[EWIP_MRP] MRP
			inner join [dbo].[EWIP_SPARE_PART] SP ON MRP.DEPT_CODE = SP.SP_DEPT_CODE AND MRP.SPAREPART_CODE = SP.CODE
			left join  (SELECT SPAREPART_CODE AS SUB_CODE,QUANTITY_NEED_BUY AS SUB_QTY_NEED_BUY,UNIT AS SUB_UNIT,DATE_NEED_FINISH AS SUB_DATE_NEED_FINISH 
			             FROM [dbo].[EWIP_MRP] 
						 WHERE [DEPT_CODE] = @A_DEPARTMENT AND (STATUS NOT IN('COMPLETE','CANCEL','NEW','WAIT_ACCEPT') AND STATUS IS NOT NULL)
						 ) SUB	ON SUB.SUB_CODE = MRP.SPAREPART_CODE
			WHERE  [DEPT_CODE] = @A_DEPARTMENT AND (MRP.MRP_CODE IS NULL OR MRP.MRP_CODE = '') AND (MRP.STATUS IN('NEW','WAIT_ACCEPT') OR MRP.STATUS IS NULL OR MRP.STATUS = '')
			ORDER BY [DATE_NEED_REQUIRED] DESC,[DATE_NEED_BUY] DESC,[DATE_NEED_FINISH] DESC

			SELECT DISTINCT [SPAREPART_CODE],SP.NAME_VI,[QUANTITY_NEED_BUY],[UNIT],[MRP_CODE],[DATE_NEED_REQUIRED],[DATE_NEED_BUY],[DATE_NEED_FINISH],[DATE_END_ACTUAL],ISNULL(SUB.SUB_QTY_NEED_BUY,0) *[dbo].[CONVERT_UNIT](SUB.SUB_UNIT,MRP.UNIT,MRP.SPAREPART_CODE,MRP.DEPT_CODE) AS SUB_QTY_NEED_BUY,ISNULL(SUB.SUB_DATE_NEED_FINISH,'') AS SUB_DATE_NEED_FINISH,[DEPT_CODE],USER_UPDATE as [USER],[STATUS],[OFF_NOTI],MRP.ID
			FROM [dbo].[EWIP_MRP] MRP
			inner join [dbo].[EWIP_SPARE_PART] SP ON MRP.DEPT_CODE = SP.SP_DEPT_CODE AND MRP.SPAREPART_CODE = SP.CODE
			left join  (SELECT SPAREPART_CODE AS SUB_CODE,QUANTITY_NEED_BUY AS SUB_QTY_NEED_BUY,UNIT AS SUB_UNIT,DATE_NEED_FINISH AS SUB_DATE_NEED_FINISH 
			             FROM [dbo].[EWIP_MRP] 
						 WHERE [DEPT_CODE] = @A_DEPARTMENT AND (STATUS NOT IN('COMPLETE','CANCEL','NEW','WAIT_ACCEPT') AND STATUS IS NOT NULL)
						 ) SUB	ON SUB.SUB_CODE = MRP.SPAREPART_CODE
			WHERE [DEPT_CODE] = @A_DEPARTMENT AND (MRP.MRP_CODE IS not NULL and MRP.MRP_CODE != '') AND MRP.STATUS IN('NEW','WAIT_ACCEPT') AND MRP.STATUS IS NOT NULL
			ORDER BY [DATE_NEED_REQUIRED] DESC,[DATE_NEED_BUY] DESC,[DATE_NEED_FINISH] DESC
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
