SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_EXCHANGE_RATE@PUT](
@A_RATE			   NVARCHAR(20),
@A_DATE             NVARCHAR(50),
@A_RATE_KRW         NVARCHAR(20),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			DECLARE @CHECK INT = 0
			DECLARE @CHECK1 INT = 0

			SELECT @CHECK = COUNT(*) 
			FROM [dbo].[EWIP_EXCHANGE_RATE]
			WHERE [FROM] = 'USD' AND [TO] = 'VND' AND FORMAT (VALID_TIME, 'yyyyMMdd') =  FORMAT (CAST(@A_DATE as date), 'yyyyMMdd')

			SELECT @CHECK1 = COUNT(*) 
			FROM [dbo].[EWIP_EXCHANGE_RATE]
			WHERE [FROM] = 'KRW' AND [TO] = 'VND' AND FORMAT (VALID_TIME, 'yyyyMMdd') =  FORMAT (CAST(@A_DATE as date), 'yyyyMMdd')

			IF @CHECK  = 0 
			   BEGIN
						INSERT INTO [dbo].[EWIP_EXCHANGE_RATE]
						VALUES(CAST(@A_DATE AS date),'USD','VND',CAST(@A_RATE AS float),GETDATE(),GETDATE());
			   END
			ELSE
			   BEGIN
						UPDATE [dbo].[EWIP_EXCHANGE_RATE]
						SET RATE = CAST(@A_RATE AS float) ,UPDATED_AT = GETDATE(),VALID_TIME = CAST(@A_DATE AS DATE)
						WHERE [FROM] = 'USD' AND [TO] = 'VND' AND FORMAT (VALID_TIME, 'yyyyMMdd') =  FORMAT (CAST(@A_DATE as date), 'yyyyMMdd')
			   END

			   IF @CHECK1  = 0 
			      BEGIN
						INSERT INTO [dbo].[EWIP_EXCHANGE_RATE]
						VALUES(CAST(@A_DATE AS date),'KRW','VND',CAST(@A_RATE_KRW AS float),GETDATE(),GETDATE());
			       END
			   ELSE
			       BEGIN
						UPDATE [dbo].[EWIP_EXCHANGE_RATE]
						SET RATE = CAST(@A_RATE_KRW AS float) ,UPDATED_AT = GETDATE(),VALID_TIME = CAST(@A_DATE AS DATE)
						WHERE [FROM] = 'KRW' AND [TO] = 'VND' AND FORMAT (VALID_TIME, 'yyyyMMdd') =  FORMAT (CAST(@A_DATE as date), 'yyyyMMdd')
			       END

			 UPDATE EWIP_SPAREPART_PRICE
			 SET PRICE_VN = CASE WHEN [INPUT_DEFAULT] = 'USD' THEN [PRICE_US] * CAST(@A_RATE AS float) ELSE PRICE_VN END,
			     PRICE_US = CASE WHEN [INPUT_DEFAULT] = 'VND' THEN PRICE_VN / CAST(@A_RATE AS float) ELSE PRICE_US END,
				 DATE= getdate()

			 MERGE [dbo].[EWIP_INVENTORY_BY_TIME] AS TARGET
			 USING EWIP_SPAREPART_PRICE AS SOURCE
			 ON (
			     TARGET.[SPARE_PART_CODE] = SOURCE.SPARE_PART_CODE AND
			 	 TARGET.[DEPT_CODE] = SOURCE.[DEPT_CODE] AND 
			 	 TARGET.[MONTH] = MONTH(CAST(SOURCE.DATE AS date)) AND 
			 	 TARGET.[YEAR] = YEAR(CAST(SOURCE.DATE AS date))
			 	)
			 WHEN MATCHED
			     THEN UPDATE SET TARGET.[PRICE_VN] = SOURCE.[PRICE_VN]/[dbo].[CONVERT_UNIT](SOURCE.UNIT_CODE,TARGET.[UNIT],TARGET.[SPARE_PART_CODE],TARGET.[DEPT_CODE]),TARGET.[PRICE_US] = SOURCE.[PRICE_US]/[dbo].[CONVERT_UNIT](SOURCE.UNIT_CODE,TARGET.[UNIT],TARGET.[SPARE_PART_CODE],TARGET.[DEPT_CODE]);
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
