SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PO@GET_LIST](
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			
			SELECT TOP 1000 OD.[ID],OD.[PO_ID],OD.[PO_ID_TEMP],[TITLE],[DATE_ORERED],FORMAT ([DATE_ORERED], 'hh:mm:ss tt') AS TIME_PO,OD.[STATUS],OD.[DATE_NEED_FINISH],OD.[DATE_CREATE],[UPDATED_DATE],OD.USER_ID AS USER_CREATE
			FROM [dbo].[EWIP_ORDER] OD
			ORDER BY [DATE_ORERED] DESC
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
