SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_INVENTORY_DELIVERY_RECEIVING@GET_BY_TIME](
@A_DEPT_CODE NVARCHAR(50),
@A_TIME_FROM NVARCHAR(50),
@A_TIME_TO  NVARCHAR(50),
@A_PHIEU NVARCHAR(10),
@A_STATUS NVARCHAR(50),
@A_STOCK_CODE  NVARCHAR(50),
@N_RETURN	int				OUTPUT,
@V_RETURN	NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		    SET NOCOUNT OFF;  
			DECLARE @SQL NVARCHAR(4000);

			SET @SQL =  
						'SELECT * FROM 
						(SELECT IDR.[IN_OUT],IDR.[DATE] AS CREATE_DATE,IDR.CODE_NO AS [STOCK_IN_OUT_CODE],IDR.[STOCK_CODE],INO.NAME,IDR.ORDER_CODE,IDR.USER_CREATE,IDR.STATUS,MONTH(IDR.[DATE]) AS [MONTH],YEAR(IDR.[DATE]) AS [YEAR]
							FROM [dbo].[EWIP_INVENTORY_DELIVERY_RECEIVING] IDR 
								INNER join [dbo].[EWIP_SP_STOCKIN] SPIN ON IDR.CODE_NO = SPIN.STOCK_IN_CODE
								left join [dbo].[EWIP_TYPE_IN_OUT] INO ON SPIN.TYPE_IN_CODE = INO.CODE
							WHERE IDR.[DEPT_CODE] = @A_DEPT_CODE AND IDR.STOCK_CODE = @A_STOCK_CODE AND
						      IDR.[DATE] BETWEEN CAST(@A_TIME_FROM AS date) AND CAST(@A_TIME_TO AS date) AND
							  IDR.STATUS IN ('+@A_STATUS + ') AND IDR.[IN_OUT] IN ('+@A_PHIEU + ')
                         UNION
							SELECT IDR.[IN_OUT],IDR.[DATE] AS CREATE_DATE,IDR.CODE_NO AS [STOCK_IN_OUT_CODE],IDR.[STOCK_CODE],INO1.NAME,IDR.ORDER_CODE,IDR.USER_CREATE,IDR.STATUS,MONTH(IDR.[DATE]) AS [MONTH],YEAR(IDR.[DATE]) AS [YEAR]
								FROM [dbo].[EWIP_INVENTORY_DELIVERY_RECEIVING] IDR 
								INNER join [dbo].[EWIP_STOCK_OUT] SO ON SO.STOCK_OUT_CODE = IDR.CODE_NO
								left join [dbo].[EWIP_TYPE_IN_OUT] INO1 ON SO.TYPE_OUT_CODE = INO1.CODE
							WHERE IDR.[DEPT_CODE] = @A_DEPT_CODE AND IDR.STOCK_CODE = @A_STOCK_CODE AND
						      IDR.[DATE] BETWEEN CAST(@A_TIME_FROM AS date) AND CAST(@A_TIME_TO AS date) AND
							  IDR.STATUS IN ('+@A_STATUS + ') AND IDR.[IN_OUT] IN ('+@A_PHIEU + ')
						 
						) AS SUB
						ORDER BY SUB.CREATE_DATE DESC'
				EXEC sp_executesql @SQL ,N'@A_DEPT_CODE NVARCHAR(50),@A_TIME_FROM NVARCHAR(50),@A_TIME_TO NVARCHAR(50),@A_STOCK_CODE NVARCHAR(50)', @A_DEPT_CODE = @A_DEPT_CODE,@A_TIME_FROM = @A_TIME_FROM,@A_TIME_TO = @A_TIME_TO,@A_STOCK_CODE = @A_STOCK_CODE;

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH

GO
