SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_ACTUAL_PRODUCT@IMPORT_SMT](
@A_USER NVARCHAR(50),
@A_DATA [dbo].[DAILY_ACTUAL_PROCD_SMT_TYPE] READONLY,
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			BEGIN TRAN

		TRUNCATE TABLE [EWIP_DAILY_ACTUAL_PROCD_SMT];
        
         MERGE [dbo].[EWIP_DAILY_ACTUAL_PROCD_SMT] AS TARGET
		 USING @A_DATA AS SOURCE
		 ON (TARGET.MODEL = SOURCE.MODEL AND TARGET.[DATE] = CAST(SOURCE.DATE AS DATE) AND TARGET.[LOT_NO] = SOURCE.[LOTNO])
		 WHEN MATCHED
		     THEN UPDATE SET PRODUCT_POINT = CAST(SOURCE.[PRODUCT_POINT] AS FLOAT),
			                 [WEEK] = CAST(SOURCE.[WEEK] AS INT), 
							 MONTH = CAST(SOURCE.[MONTH] AS INT),
							 [UPDATE_TIME_SYS] = SYSDATETIME(),
							 [USER_UPDATE] = @A_USER
		 WHEN NOT MATCHED BY TARGET
		      THEN INSERT([PRODUCT_POINT],[WEEK],[MONTH],[DATE],[UPDATE_TIME_SYS],[USER_UPDATE],[MODEL],LOT_NO)
			  VALUES(CAST(SOURCE.[PRODUCT_POINT] AS FLOAT),CAST(SOURCE.[WEEK] AS INT),CAST(SOURCE.[MONTH] AS INT),CAST(SOURCE.DATE AS DATE),SYSDATETIME(),@A_USER,SOURCE.MODEL,SOURCE.[LOTNO]);
            
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
	COMMIT TRAN
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
  ROLLBACK TRAN
END CATCH
GO
