SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_ORDER_JOURNEY@GET](
@A_PO_NO		NVARCHAR(50),
@A_INVOICE_NO   NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(MAX)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			DECLARE @NVSQL NVARCHAR(MAX)
			DECLARE @params NVARCHAR(MAX) = '@A_PO_NO NVARCHAR(50), @A_INVOICE_NO NVARCHAR(50)'
			SET @NVSQL = N'WITH sqlRowNumber AS(
								SELECT IV.PO_NO,IV.COMMERCIAL_INVOICE_NO AS INVOICE_NO,IV.MATERIAL_ID,IV.MATERIAL_DESC,IV.QUANTITY,IV.UNIT,DL.WAY,DL.ETD,DL.ETA,DL.ETA_WISOL,DL.SHIPPER,DL.NOTE,
								ROW_NUMBER() OVER(PARTITION BY IV.COMMERCIAL_INVOICE_NO ORDER BY DL.IMPORT_DATE DESC) AS row_number
								FROM [dbo].[EWIP_INVOICES] IV
								LEFT JOIN [dbo].[EWIP_LOGISTICS_DAILY_REPORT] DL ON TRIM(DL.INVOICE) LIKE ''%''+TRIM(IV.COMMERCIAL_INVOICE_NO)+''%''
								WHERE 1 = 1 '

								IF @A_INVOICE_NO IS NOT NULL AND @A_INVOICE_NO != ''
								     SET @NVSQL += ' AND @A_INVOICE_NO ' + ' LIKE ''%'' + IV.COMMERCIAL_INVOICE_NO + ''%'''

							    IF @A_PO_NO IS NOT NULL AND @A_PO_NO != ''
								      SET @NVSQL += ' AND @A_PO_NO ' + ' LIKE ''%'' +  IV.PO_NO + ''%'''

			SET @NVSQL += ' ) '
			SET @NVSQL += ' SELECT * FROM (SELECT * FROM sqlRowNumber WHERE row_number = 1) AS SUB1 '

           SET @NVSQL += 
			N' LEFT JOIN (SELECT EO.PO_ID,ISNULL(MSC.SPARE_PART_CODE,eprd.SPAREPART_CODE) as SPAREPART_CODE,eprd.DEPT_CODE + ''-'' + CAST(eprd.QUANTITY_NEED_BUY AS NVARCHAR) + ''-'' + eprd.UNIT AS DEPT_DETAIL
				FROM EWIP_ORDER eo 
				INNER JOIN EWIP_ORDER_PR eop ON EO.PO_ID = EOP.PO_ID
				INNER JOIN EWIP_PURCHASE_REQUEST epr ON EPR.PR_CODE = EOP.PR_CODE
				INNER JOIN EWIP_PURCHASE_REQUEST_DETAIL eprd ON EPR.MRP_CODE = eprd.MRP_CODE
				LEFT JOIN [dbo].[EWIP_MERGE_SPAREPART_CODE] MSC ON MSC.SPARE_PART_CODE = eprd.SPAREPART_CODE AND MSC.DEPT_CODE = eprd.DEPT_CODE
				) SUB2 ON SUB1.PO_NO = SUB2.PO_ID AND SUB1.MATERIAL_ID = SUB2.SPAREPART_CODE'

				PRINT @NVSQL

			EXECUTE sys.sp_executesql @NVSQL ,@params, @A_PO_NO = @A_PO_NO, @A_INVOICE_NO = @A_INVOICE_NO


       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
