SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_EQUIPMENT_BOM@INIT](
@A_DEPARTMENT		NVARCHAR(50),
@A_EQUIPMENT        NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  

			SELECT [EQUIPMENT_ID],[EQUIPMENT_NAME]
			FROM [dbo].[EWIP_EQUIPMENT]
			WHERE DEPT_CODE = @A_DEPARTMENT

			SELECT  E.[EQUIPMENT_ID],E.[EQUIPMENT_NAME],E.[EQUIPMENT_TYPE],E.[EQ_MANUFACTURING_YEAR],E.[EQ_SERIAL],E.[EQ_ORIGIN],E.[EQ_MODEL],E.[IMAGE],E.[DETAIL_INFO],B.[SPARE_PART_CODE],SP.NAME_VI
			FROM [dbo].[EWIP_EQUIPMENT_BOM] B
			INNER JOIN [dbo].[EWIP_EQUIPMENT] E
			ON B.EQUIPMENT_ID = E.EQUIPMENT_ID AND B.DEP_CODE = E.DEPT_CODE
			LEFT JOIN [dbo].[EWIP_SPARE_PART] SP ON B.SPARE_PART_CODE = SP.CODE AND SP.SP_DEPT_CODE = B.DEP_CODE 
			WHERE B.DEP_CODE = @A_DEPARTMENT AND B.[EQUIPMENT_ID] = @A_EQUIPMENT

			SELECT DISTINCT E.EQUIPMENT_ID,E.[EQUIPMENT_NAME],SP.CODE,SP.NAME_VI
			FROM [dbo].[EWIP_EQUIPMENT_BOM] B
			INNER JOIN [dbo].[EWIP_EQUIPMENT] E
			ON B.EQUIPMENT_ID = E.EQUIPMENT_ID AND B.DEP_CODE = E.DEPT_CODE
			LEFT JOIN [dbo].[EWIP_SPARE_PART] SP ON B.SPARE_PART_CODE = SP.CODE AND SP.SP_DEPT_CODE = B.DEP_CODE 
			WHERE B.DEP_CODE = @A_DEPARTMENT AND B.[EQUIPMENT_ID] = @A_EQUIPMENT 

       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
