SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP_EQUIPMENT@GET_BY_ID](
@A_CODE             NVARCHAR(50),-- MA THIET BI
@A_DEPARTMENT		NVARCHAR(50),
@A_IS_EQUIPMENT     NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  

				IF @A_IS_EQUIPMENT = '1'
				    BEGIN
						  	SELECT TOP 1 EQ.[EQUIPMENT_ID] AS CODE ,[EQUIPMENT_NAME] AS NAME,[EQUIPMENT_TYPE] AS TYPE,[EQ_MANUFACTURING_YEAR],[EQ_SERIAL],[EQ_ORIGIN],[EQ_MODEL],[IMAGE],[DETAIL_INFO],[STATUS], EL.EQ_LOCATION_NAME + ' - ' + L.SUB_LOCATION AS EQ_LOCATION_NAME,
							             '' AS [MATERIAL],'' AS [SIZE],'' AS [WEIGHT],EQ.[MANUFACTURER]
							FROM [dbo].[EWIP_EQUIPMENT] EQ
							LEFT JOIN [dbo].[EWIP_EQUIPMENT_LOCATION_RELATION] L ON EQ.EQUIPMENT_ID = L.EQUIPMENT_ID AND EQ.DEPT_CODE = L.DEPT_CODE
							LEFT JOIN [dbo].[EWIP_EQUIPMENT_LOCATION] EL ON EL.ID = L.EQ_LOCATION_ID
							WHERE EQ.EQUIPMENT_ID = @A_CODE AND EQ.DEPT_CODE = @A_DEPARTMENT
							
							SELECT [NAME],[CONTENT_TYPE],[USER_UPLOAD],[SYS_TIME]
							FROM [dbo].[EWIP_SPAREPART_DOCUMENT]
							WHERE [DEPT_CODE] = @A_DEPARTMENT AND [CODE] = @A_CODE AND [IS_EQUIPMENT] = '1'
				    END
				ELSE
				    BEGIN
							SELECT TOP 1 SP.[CODE],ISNULL([NAME_VI],[NAME_KR]) AS NAME,T.NAME AS TYPE,0 AS EQ_MANUFACTURING_YEAR,ISNULL(M.SERIAL_AFTER,M.SERIAL_PRE) AS EQ_SERIAL,'' AS EQ_ORIGIN,'' AS EQ_MODEL, SP.IMAGE ,
							SP.[SPECIFICATIONS] AS DETAIL_INFO,'' AS STATUS,L.LOCATION_CODE AS EQ_LOCATION_NAME,[MATERIAL],[SIZE],[WEIGHT],V.NAME AS [MANUFACTURER]
							FROM [dbo].[EWIP_SPARE_PART] SP
							LEFT JOIN [dbo].[EWIP_SPAREPART_TYPE] T ON SP.TYPE = T.CODE
							LEFT JOIN [dbo].[EWIP_EQUIPMENT_MAINTAIN] M ON SP.CODE = M.SPARE_PART_CODE AND SP.SP_DEPT_CODE = M.DEPT_CODE
							LEFT JOIN [dbo].[EWIP_SPAREPART_LOCATION] L ON SP.CODE = L.[SPARE_PART_CODE] AND SP.SP_DEPT_CODE = L.DEPT_CODE
							LEFT JOIN [dbo].[EWIP_VENDER] V on v.VENDER_ID = sp.VENDER_ID 
							WHERE SP.CODE = @A_CODE AND SP.SP_DEPT_CODE = @A_DEPARTMENT

							SELECT [NAME],[CONTENT_TYPE],[USER_UPLOAD],[SYS_TIME]
							FROM [dbo].[EWIP_SPAREPART_DOCUMENT]
							WHERE [DEPT_CODE] = @A_DEPARTMENT AND [CODE] = @A_CODE AND [IS_EQUIPMENT] != '1'
					END
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH


GO
