SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_EQUIPMENT@INIT](
@A_DEPARTMENT  NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			
			SELECT CODE,NAME FROM [dbo].[EWIP_EQUIPMENT_TYPE]

			SELECT ID AS CODE,[EQ_LOCATION_NAME] AS NAME,[FACTORY] FROM [dbo].[EWIP_EQUIPMENT_LOCATION]

			SELECT DISTINCT EQ.[EQUIPMENT_ID],EQ.[EQUIPMENT_NAME],EQ_TYPE.NAME as EQUIPMENT_TYPE,EQ.[MANUFACTURER],cast(EQ.[EQ_MANUFACTURING_YEAR] as nvarchar) as [EQ_MANUFACTURING_YEAR],EQ.[EQ_SERIAL],EQ.[EQ_ORIGIN],EQ.[EQ_MODEL],[STATUS],L.EQ_LOCATION_NAME,LR.[SUB_LOCATION],EQ.[DATE_IN]
			FROM [dbo].[EWIP_EQUIPMENT] EQ
			LEFT JOIN [dbo].[EWIP_EQUIPMENT_TYPE] EQ_TYPE ON EQ.[EQUIPMENT_TYPE] = EQ_TYPE.CODE
			LEFT JOIN [dbo].[EWIP_EQUIPMENT_LOCATION_RELATION] LR ON EQ.[EQUIPMENT_ID] = LR.[EQUIPMENT_ID] AND EQ.DEPT_CODE = LR.DEPT_CODE
			LEFT JOIN [dbo].[EWIP_SPAREPART_DOCUMENT] SD ON EQ.[EQUIPMENT_ID] = SD.CODE AND EQ.DEPT_CODE = SD.[DEPT_CODE]
			LEFT JOIN [dbo].[EWIP_EQUIPMENT_LOCATION] L ON LR.EQ_LOCATION_ID = L.ID
			WHERE EQ.DEPT_CODE = @A_DEPARTMENT

			SET @N_RETURN = 0;
			SET @V_RETURN = 'MSG_COM_004';
		END
END TRY
BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
