SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_LOCATION@INSERT_SINGLE](
@A_CODE   NVARCHAR(50),
@A_STOCK_CODE VARCHAR(50),
@A_DEPT_CODE NVARCHAR(100),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  

			IF NOT EXISTS(SELECT * FROM [dbo].[EWIP_LOCATIONS] WHERE CODE = @A_CODE AND STOCK_CODE = @A_STOCK_CODE AND DEPT_CODE = @A_DEPT_CODE)			   
				INSERT INTO [dbo].[EWIP_LOCATIONS]
				VALUES(@A_CODE,@A_STOCK_CODE,@A_DEPT_CODE,GETDATE())
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
