SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_FILE_TEMP@INSERT](
@A_FILENAME			NVARCHAR(200),
@A_CONTENT_TYPE		NVARCHAR(200),
@A_DATA             VARBINARY(MAX),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    DECLARE @CHECK int = 0;

			SELECT @CHECK = COUNT(*) FROM [dbo].[EWIP_FILE_TEMP] WHERE [Name] = @A_FILENAME 

			IF @CHECK > 0
			   DELETE FROM [dbo].[EWIP_FILE_TEMP] WHERE [Name] = @A_FILENAME 

			INSERT INTO [dbo].[EWIP_FILE_TEMP]
			VALUES(@A_FILENAME,@A_CONTENT_TYPE,@A_DATA)
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
