SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SAP_PO@PUT](
@A_VENDOR_ID        NVARCHAR(50), 
@A_PO_ID            NVARCHAR(50),
@A_SAP_PO_ID        NVARCHAR(50),
@A_USER             NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
	       IF EXISTS (SELECT * FROM [dbo].[EWIP_SAP_PO] WHERE PO_ID = @A_PO_ID AND VENDOR = @A_VENDOR_ID)
		       BEGIN
					UPDATE [dbo].[EWIP_SAP_PO]
					SET [SAP_PO_ID] = @A_SAP_PO_ID,[DATE_SYS] = SYSDATETIME(),USER_UPDATE = @A_USER
					WHERE PO_ID = @A_PO_ID AND VENDOR = @A_VENDOR_ID
			   END
		   ELSE
		       BEGIN
					 INSERT INTO [dbo].[EWIP_SAP_PO]
					 VALUES(@A_PO_ID,@A_SAP_PO_ID,@A_VENDOR_ID,SYSDATETIME(),@A_USER) 
			   END
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
