SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SPAREPART@ENCRIPT_CODE](
@A_DEPARTMENT		NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			BEGIN TRAN
			DELETE FROM [dbo].[SPAREPART_CODE_ENCRIPT]
			WHERE DEPT_CODE = @A_DEPARTMENT

			INSERT INTO [dbo].[SPAREPART_CODE_ENCRIPT]
			SELECT CODE,ID,SP_DEPT_CODE FROM [dbo].[EWIP_SPARE_PART]
			WHERE [SP_DEPT_CODE] = @A_DEPARTMENT AND LEN(CODE) > 8

			SELECT [SPARE_PART_CODE],[ENCRIPT_CODE] FROM [dbo].[SPAREPART_CODE_ENCRIPT] WHERE DEPT_CODE = @A_DEPARTMENT 
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
	COMMIT TRAN
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
  ROLLBACK TRAN
END CATCH
GO
