SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PO@CREATE_MERGED_CODE](
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN

			DECLARE @MAX_CODE nvarchar(50)

		    -- NO-20210728-001
		    SET NOCOUNT OFF;  
			SELECT TOP 1 @MAX_CODE = [CODE_MERGED]
			FROM [dbo].[EWIP_MERGE_SPAREPART_CODE]
			WHERE FORMAT(GETDATE(),'yyyyMMdd') =  CAST(SUBSTRING([CODE_MERGED],4,8) AS date)
			ORDER BY CAST(SUBSTRING([CODE_MERGED],4,8) AS date) DESC, CAST(SUBSTRING([CODE_MERGED],LEN([CODE_MERGED]) - 2,3) AS INT) DESC

			IF @MAX_CODE IS NULL OR @MAX_CODE = ''
				 BEGIN
					SET @MAX_CODE = 'NO-' + FORMAT(GETDATE(),'yyyyMMdd') +'-'+ '001'
				 END
			ELSE 
			        BEGIN	
						SELECT @MAX_CODE = SUBSTRING(@MAX_CODE,1,12) +  REPLACE(STR((CAST(SUBSTRING(@MAX_CODE,13,3) AS INT)+1), 3), SPACE(1), '0')  
					END
			SELECT @MAX_CODE as CODE
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
