SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_LOGISTICS_DAILY_REPORT@IMPORT](
@A_USER   NVARCHAR(50),
@A_DATA				[dbo].[LOGISTICS_DAILY_REPORT_TYPE] READONLY,	
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			INSERT INTO [dbo].[EWIP_LOGISTICS_DAILY_REPORT]
			SELECT 
					 [WAY]
					 ,[LH]
					 ,[MASTER_B_LMAWB_NO]
					 ,[HOUSE_BL_HAWB_NO]
					 ,[VESSEL_FLIGHT]
					 ,[ETD]
					 ,[ETA]
					 ,[ETA_WISOL]
					 ,[SHIPPER]
					 ,[INVOICE]
					 ,[QUANTITY_PAL]
					 ,[GW_KGS]
					 ,[CW_KGS]
					 ,[MEASUREME_NT]
					 ,[LCL_FCL]
					 ,[CONT_20]
					 ,[CONT_40]
					 ,[POL]
					 ,[POD]
					 ,[TERM]
					 ,[WARE_HOUSE]
					 ,[TIME_DELIVERY]
					 ,[NO_CD]
					 ,[DESCRIPTION_OF_GOODS]
					 ,[NOTE]
					,@A_USER AS [IMPORT_BY]
					,SYSDATETIME() AS [IMPORT_DATE]
			FROM @A_DATA
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
