SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PO@DELETE_PO](
@A_PO_ID NVARCHAR(50),
@A_PO_ID_TEMP NVARCHAR(50),
@A_USER NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		   
		   BEGIN TRAN
		   IF @A_PO_ID != '' AND @A_PO_ID IS NOT NULL
		     BEGIN
					UPDATE [dbo].[EWIP_PURCHASE_REQUEST]
					SET PR_STATUS = 'ACCEPT',DATE_UPDATE = GETDATE(), USER_UPDATE = @A_USER
					WHERE PR_CODE IN (SELECT [PR_CODE] FROM [dbo].[EWIP_ORDER_PR] WHERE PO_ID = @A_PO_ID AND STATUS != 'CANCEL') AND PR_STATUS != 'CANCEL'

					UPDATE [dbo].[EWIP_MRP_LIST]
					SET STATUS = 'ACCEPT',USER_UPDATE = @A_USER,DATE_UPDATE = GETDATE()
					WHERE STATUS != 'CANCEL' AND [MRP_CODE] IN (
					SELECT MRP_CODE 
					FROM [dbo].[EWIP_PURCHASE_REQUEST] PR INNER JOIN [dbo].[EWIP_ORDER_PR] OPR ON PR.PR_CODE = OPR.PR_CODE
					WHERE OPR.PO_ID = @A_PO_ID AND PR.PR_STATUS != 'CANCEL')

					UPDATE [dbo].[EWIP_MRP]
					SET STATUS = 'ACCEPT',DATE_UPDATE = GETDATE(),USER_UPDATE = @A_USER
					WHERE MRP_CODE IN (
					SELECT MRP_CODE 
					FROM [dbo].[EWIP_PURCHASE_REQUEST] PR INNER JOIN [dbo].[EWIP_ORDER_PR] OPR ON PR.PR_CODE = OPR.PR_CODE
					WHERE OPR.PO_ID = @A_PO_ID AND PR.PR_STATUS != 'CANCEL') AND STATUS != 'CANCEL'

					UPDATE [dbo].[EWIP_PURCHASE_REQUEST_DETAIL]
					SET STATUS = 'ACCEPT',DATE_UPDATE = GETDATE(), USER_UPDATE =@A_USER
					WHERE MRP_CODE IN (
					SELECT MRP_CODE 
					FROM [dbo].[EWIP_PURCHASE_REQUEST] PR INNER JOIN [dbo].[EWIP_ORDER_PR] OPR ON PR.PR_CODE = OPR.PR_CODE
					WHERE OPR.PO_ID = @A_PO_ID AND PR.PR_STATUS != 'CANCEL') AND STATUS != 'CANCEL'

					DELETE [dbo].[EWIP_ORDER]
					WHERE PO_ID = @A_PO_ID

					DELETE [dbo].[EWIP_ORDER_PR]
					WHERE PO_ID = @A_PO_ID

					DELETE [dbo].[EWIP_ORDER_DETAIL]
					WHERE PO_ID = @A_PO_ID
			END
		   ELSE 
		      BEGIN
					UPDATE [dbo].[EWIP_PURCHASE_REQUEST]
					SET PR_STATUS = 'ACCEPT',DATE_UPDATE = GETDATE(), USER_UPDATE = @A_USER
					WHERE PR_CODE IN (SELECT [PR_CODE] FROM [dbo].[EWIP_ORDER_PR] WHERE PO_ID_TEMP = @A_PO_ID_TEMP AND STATUS != 'CANCEL') AND PR_STATUS != 'CANCEL'

					UPDATE [dbo].[EWIP_MRP_LIST]
					SET STATUS = 'ACCEPT',USER_UPDATE = @A_USER,DATE_UPDATE = GETDATE()
					WHERE STATUS != 'CANCEL' AND [MRP_CODE] IN (
					SELECT MRP_CODE 
					FROM [dbo].[EWIP_PURCHASE_REQUEST] PR INNER JOIN [dbo].[EWIP_ORDER_PR] OPR ON PR.PR_CODE = OPR.PR_CODE
					WHERE OPR.PO_ID_TEMP = @A_PO_ID_TEMP AND PR.PR_STATUS != 'CANCEL')

					UPDATE [dbo].[EWIP_MRP]
					SET STATUS = 'ACCEPT',DATE_UPDATE = GETDATE(),USER_UPDATE = @A_USER
					WHERE MRP_CODE IN (
					SELECT MRP_CODE 
					FROM [dbo].[EWIP_PURCHASE_REQUEST] PR INNER JOIN [dbo].[EWIP_ORDER_PR] OPR ON PR.PR_CODE = OPR.PR_CODE
					WHERE OPR.PO_ID_TEMP = @A_PO_ID_TEMP AND PR.PR_STATUS != 'CANCEL') AND STATUS != 'CANCEL'

					UPDATE [dbo].[EWIP_PURCHASE_REQUEST_DETAIL]
					SET STATUS = 'ACCEPT',DATE_UPDATE = GETDATE(), USER_UPDATE =@A_USER
					WHERE MRP_CODE IN (
					SELECT MRP_CODE 
					FROM [dbo].[EWIP_PURCHASE_REQUEST] PR INNER JOIN [dbo].[EWIP_ORDER_PR] OPR ON PR.PR_CODE = OPR.PR_CODE
					WHERE OPR.PO_ID_TEMP = @A_PO_ID_TEMP AND PR.PR_STATUS != 'CANCEL') AND STATUS != 'CANCEL'

					DELETE [dbo].[EWIP_ORDER]
					WHERE PO_ID_TEMP = @A_PO_ID_TEMP

					DELETE [dbo].[EWIP_ORDER_PR]
					WHERE PO_ID_TEMP = @A_PO_ID_TEMP

					DELETE [dbo].[EWIP_ORDER_DETAIL]
					WHERE PO_ID_TEMP = @A_PO_ID_TEMP
			  END
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
	COMMIT TRAN
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
  ROLLBACK TRAN
END CATCH
GO
