SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_VIRTUAL_PO@INIT](
@A_DEPARTMENT		NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			DECLARE @MRP NVARCHAR(50)
			DECLARE @PRCODE NVARCHAR(50)
			DECLARE @PO_CODE NVARCHAR(50)

			SET @MRP = [dbo].[F_CREATE_MRP_CODE](@A_DEPARTMENT)
			SET @PRCODE = [dbo].[F_CREATE_PR_CODE](@A_DEPARTMENT)
			SET @PO_CODE = [dbo].[F_CREATE_PO_CODE]()

			SELECT @MRP AS MRP,@PRCODE AS PRCODE,@PO_CODE AS POCODE

			SELECT esp.CODE,esp.NAME_VI FROM EWIP_SPARE_PART esp WHERE esp.SP_DEPT_CODE = @A_DEPARTMENT

			SELECT ev.VENDER_ID,ev.NAME FROM EWIP_VENDER ev


       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
