SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PKG_SYSTEM002@INT_LIST](
@A_PLANT			VARCHAR(50),
@A_LANG				VARCHAR(50),
@A_DEPARTMENT		VARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
	
	SELECT T.FORM AS FORM,
           ( CASE WHEN @A_LANG = 'KOR' THEN T1.KOR
					WHEN @A_LANG = 'VTN' THEN T1.VTN
			 END) AS FORMNAME,
            T.USEFLAG AS USEFLAG,
            T.REMARKS AS REMARKS
    FROM ESYSMSTFORM T
	LEFT JOIN ESYSMSTGLA T1 ON T.FORM = T1.GLSR AND T.DEPARTMENT = T1.DEPARTMENT
    WHERE T.PLANT = @A_PLANT
    ORDER BY T.FORM ASC;

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH








GO
