SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP_INVENTORY@CREATE_BALANCE_WAREHOUSE](
@A_DEPARTMENT		NVARCHAR(50),
@A_USER             NVARCHAR(50),
@A_STOCK_CODE		NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF; 
			BEGIN TRAN;
			UPDATE [dbo].[EWIP_SPAREPART_INVENTORY]
			SET [QUANTITY] = [QUANTITY_REAL], UPDATE_DATE = GETDATE(),USER_UPDATE = @A_USER
			WHERE [DEPT_CODE] = @A_DEPARTMENT AND [STOCK_CODE] = @A_STOCK_CODE AND [QUANTITY_REAL] IS NOT NULL

			UPDATE [dbo].[EWIP_INVENTORY_BY_TIME]
			SET [QUANTITY] = [QUANTITY_REAL]
			WHERE [DEPT_CODE] = @A_DEPARTMENT AND [STOCK_CODE] = @A_STOCK_CODE AND [MONTH] = MONTH(GETDATE()) AND [YEAR] = YEAR(GETDATE()) AND [QUANTITY_REAL] IS NOT NULL
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
	COMMIT TRAN;
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
  ROLLBACK TRAN;
END CATCH


GO
