SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_ALL@CONVERT_UNIT](
@A_UNIT_FROM VARCHAR(20),
	@A_UNIT_TO VARCHAR(20),
	@A_SPARE_PART_CODE NVARCHAR(50),
	@A_DEPT_CODE NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			-- Declare the return variable here
			DECLARE @RATE1 float;
			DECLARE @RATE2 float;
			DECLARE @RESULT float;

			SELECT @RATE1 = RATE 
			FROM [dbo].[EWIP_SPAREPART_UNIT] 
			WHERE [SPARE_PART_CODE] = @A_SPARE_PART_CODE AND UNIT_CODE = @A_UNIT_FROM AND [DEPT_CODE] = @A_DEPT_CODE

			SELECT @RATE2 = RATE 
			FROM [dbo].[EWIP_SPAREPART_UNIT] 
			WHERE [SPARE_PART_CODE] = @A_SPARE_PART_CODE AND UNIT_CODE = @A_UNIT_TO AND [DEPT_CODE] = @A_DEPT_CODE


			IF @RATE1 IS NULL OR @RATE2 IS NULL OR @RATE2 = 0 OR @RATE1 = 0
			   SET @RESULT = 1;
			ELSE
			  SET @RESULT = @RATE1/@RATE2

			-- Return the result of the function
			
				SELECT @RESULT AS RESULT

			   END
			SET @N_RETURN = 0;
			SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
