SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PR@GET_DATA_PO_FILE_NEW](
@A_WARES   NVARCHAR(50),
@A_PR_LIST  NVARCHAR(MAX),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			
			SELECT 
			FORMAT (getdate(), 'yyyyMMdd') as PO_CREATE,
			PRD.VENDOR_ID,
			'' as KUNNR,
			'' as [BKGRP],
			'' as [PSTYP],
			(CASE WHEN ME.CODE_MERGED IS NOT NULL AND ME.CODE_MERGED != '' THEN ME.CODE_MERGED ELSE prd.SPAREPART_CODE END) as [SPARE_PART_CODE],
			SP.NAME_KR +' '+ SP.[SPECIFICATIONS] AS TXZ01,
			'' AS [WERKS],
			'' AS [LGORT],
			PRD.QUANTITY_NEED_BUY AS [PO_QTY],
			PRD.[UNIT],
			(CASE WHEN @A_WARES = 'USD' THEN PRD.PRICE_US ELSE PRD.PRICE_VN END) AS PRICE,
			1 AS PER,
			@A_WARES AS [WAERS],
			'VZ' AS [MWSKZ],
		    FORMAT (PRD.DATE_NEED_FINISH, 'yyyyMMdd') AS DELIVERY_DATE,
			'K' as [KNTTP],
			'8000' as [MATKL],
			'' as POSID,
			SP.[GL_ACCOUNT],
			SPD.COST_CTR,
			OPR.DEPT_CODE
			FROM [dbo].[EWIP_ORDER_PR] OPR
			INNER JOIN [dbo].[EWIP_PURCHASE_REQUEST] PR ON OPR.PR_CODE = PR.PR_CODE AND OPR.DEPT_CODE = PR.DEPT_CODE
			INNER JOIN [dbo].[EWIP_PURCHASE_REQUEST_DETAIL] PRD ON PR.PR_CODE = PRD.PR_CODE AND PR.MRP_CODE = PRD.MRP_CODE AND PR.DEPT_CODE = PRD.DEPT_CODE
			INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON SP.[SP_DEPT_CODE] = PR.DEPT_CODE AND SP.CODE = PRD.SPAREPART_CODE
			INNER JOIN [dbo].[EWIP_SPARE_PART_DEPT] SPD ON SP.CODE = SPD.SPARE_PART_CODE AND SP.[SP_DEPT_CODE] = SPD.DEPT_CODE
			LEFT JOIN [dbo].[EWIP_MERGE_SPAREPART_CODE] ME ON SP.CODE = ME.SPARE_PART_CODE AND ME.DEPT_CODE = SP.SP_DEPT_CODE
			WHERE OPR.PR_CODE IN (SELECT VALUE FROM STRING_SPLIT(@A_PR_LIST,'^'))

			SELECT PRD.SPAREPART_CODE,PRD.PR_CODE,PRD.DEPT_CODE
			FROM [dbo].[EWIP_ORDER_PR] OPR
			INNER JOIN [dbo].[EWIP_PURCHASE_REQUEST] PR ON OPR.PR_CODE = PR.PR_CODE AND OPR.DEPT_CODE = PR.DEPT_CODE
			INNER JOIN [dbo].[EWIP_PURCHASE_REQUEST_DETAIL] PRD ON PR.PR_CODE = PRD.PR_CODE AND PR.MRP_CODE = PRD.MRP_CODE AND PR.DEPT_CODE = PRD.DEPT_CODE
			INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON SP.[SP_DEPT_CODE] = PR.DEPT_CODE AND SP.CODE = PRD.SPAREPART_CODE
			INNER JOIN [dbo].[EWIP_SPARE_PART_DEPT] SPD ON SP.CODE = SPD.SPARE_PART_CODE AND SP.[SP_DEPT_CODE] = SPD.DEPT_CODE
			WHERE OPR.PR_CODE IN (SELECT VALUE FROM STRING_SPLIT(@A_PR_LIST,'^')) 

       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
