SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PR@GET_PR_DETAIL_BY_CODE](
@A_DEPARTMENT		NVARCHAR(50),
@A_PR_CODE          NVARCHAR(50),
@A_MRP_CODE         NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			SELECT [SPAREPART_CODE] as CODE,SP.NAME_VI AS NAME
			FROM [dbo].[EWIP_PURCHASE_REQUEST_DETAIL] PRD
			INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON SP.SP_DEPT_CODE = PRD.DEPT_CODE AND SP.CODE = PRD.SPAREPART_CODE
			WHERE [PR_CODE] = @A_PR_CODE AND DEPT_CODE = @A_DEPARTMENT AND MRP_CODE = @A_MRP_CODE
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
