SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP@GET_DOCUMENT_BY_ID](
@A_CODE             NVARCHAR(50),-- MA THIET BI
@A_DEPARTMENT		NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  				   
							SELECT [NAME],[CONTENT_TYPE],[USER_UPLOAD],[SYS_TIME]
							FROM [dbo].[EWIP_SPAREPART_DOCUMENT]
							WHERE [DEPT_CODE] = @A_DEPARTMENT AND [CODE] = @A_CODE AND [IS_EQUIPMENT] != '1'				
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH


GO
