SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_EQUIPMENT_MAINTAIN@DELETE](
@A_ID NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			
			DELETE FROM [dbo].[EWIP_EQUIPMENT_MAINTAIN]
			WHERE [MAINTAIN_ID] = @A_ID

			SET @N_RETURN = 0;
			SET @V_RETURN = 'MSG_COM_004';
		END
END TRY
BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
