SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_CHART_SPARE_PART_VALUES@GETDATA](
@A_DEPARTMENT		NVARCHAR(50),
@A_TYPE             NVARCHAR(50),
@A_TIME             NVARCHAR(50),
@A_KRW_VND          NVARCHAR(50),
@A_TOP              NVARCHAR(50),
@A_TYPE_CATEGORY    NVARCHAR(10),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		
			DECLARE @VND_KRW FLOAT = 1

		    IF @A_KRW_VND = 'KRW'
				BEGIN
					SELECT @VND_KRW = 1/RATE FROM [dbo].[EWIP_EXCHANGE_RATE] WHERE [FROM] = 'KRW' AND [TO] = 'VND' ORDER BY VALID_TIME DESC
			    END
			ELSE
				 BEGIN
						  SET @VND_KRW = 1
			    END

				SET @VND_KRW = @VND_KRW*0.001 -- rut gon tien xuong don vi nghin dong

				IF @A_TYPE = 'MONTH'
				   BEGIN
				         DECLARE @TOTAL_VALUE FLOAT = 0
						 
						 SELECT @TOTAL_VALUE = SUM(ISNULL(INVENTORY_VALUES_VN,0))
						 FROM [dbo].[EWIP_INVENTORY_VALUES_BY_TIME] cte
						 INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON CTE.SPARE_PART_CODE = SP.CODE AND CTE.DEPT_CODE =SP.SP_DEPT_CODE
						 WHERE DEPT_CODE = @A_DEPARTMENT AND [MONTH] =  MONTH(CAST(@A_TIME AS DATE)) AND [YEAR] = YEAR(CAST(@A_TIME AS DATE)) AND SP.TYPE = CASE WHEN @A_TYPE_CATEGORY = '1' OR @A_TYPE_CATEGORY = '2' THEN @A_TYPE_CATEGORY ELSE SP.TYPE END

						 IF @TOTAL_VALUE > 0
						    BEGIN

							    SELECT TOP(CAST(@A_TOP AS INT)) SPARE_PART_CODE,INVENTORY_VALUE,PERCENT_VALUE,SUM(PERCENT_VALUE) OVER(ORDER BY INVENTORY_VALUE DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE
								 FROM
								    (
										SELECT ISNULL(SP.NAME_VI,sp.NAME_KR) + '(' + SP.CODE + ')' as SPARE_PART_CODE,[INVENTORY_VALUES_VN]*@VND_KRW AS INVENTORY_VALUE,100*[INVENTORY_VALUES_VN]/@TOTAL_VALUE AS PERCENT_VALUE 
										FROM [dbo].[EWIP_INVENTORY_VALUES_BY_TIME] T
										INNER JOIN [dbo].[EWIP_SPARE_PART]  SP ON T.SPARE_PART_CODE = SP.CODE AND t.DEPT_CODE = sp.SP_DEPT_CODE
										WHERE [MONTH] = MONTH(CAST(@A_TIME AS DATE)) AND [YEAR] = YEAR(CAST(@A_TIME AS DATE)) AND DEPT_CODE = @A_DEPARTMENT AND SP.TYPE = CASE WHEN @A_TYPE_CATEGORY = '1' OR @A_TYPE_CATEGORY = '2' THEN @A_TYPE_CATEGORY ELSE SP.TYPE END
								    ) SUB
								 ORDER BY INVENTORY_VALUE DESC

								 SELECT  SPARE_PART_CODE,INVENTORY_VALUE,PERCENT_VALUE,SUM(PERCENT_VALUE) OVER(ORDER BY INVENTORY_VALUE DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE
								 FROM
								    (
										SELECT ISNULL(SP.NAME_VI,sp.NAME_KR) + '(' + SP.CODE + ')'  as SPARE_PART_CODE,[INVENTORY_VALUES_VN]*@VND_KRW AS INVENTORY_VALUE,100*[INVENTORY_VALUES_VN]/@TOTAL_VALUE AS PERCENT_VALUE 
										FROM [dbo].[EWIP_INVENTORY_VALUES_BY_TIME] T
										INNER JOIN [dbo].[EWIP_SPARE_PART]  SP ON T.SPARE_PART_CODE = SP.CODE AND t.DEPT_CODE = sp.SP_DEPT_CODE
										WHERE [MONTH] = MONTH(CAST(@A_TIME AS DATE)) AND [YEAR] = YEAR(CAST(@A_TIME AS DATE)) AND DEPT_CODE = @A_DEPARTMENT AND SP.TYPE = CASE WHEN @A_TYPE_CATEGORY = '1' OR @A_TYPE_CATEGORY = '2' THEN @A_TYPE_CATEGORY ELSE SP.TYPE END
								    ) SUB
								 ORDER BY INVENTORY_VALUE DESC
						    END
				    END
				ELSE IF @A_TYPE = 'WEEK'
				    BEGIN
					      DECLARE @DATA_WEEK TABLE
						   (	SPARE_PART_CODE  NVARCHAR(50),
								[INVENTORY_VALUES_VN] FLOAT,
								WEEKS INT
							)

						  INSERT INTO @DATA_WEEK
						  SELECT TOP 1 WITH TIES SPARE_PART_CODE,INVENTORY_VALUES_VN,[WEEK]
						  FROM [dbo].[EWIP_INVENTORY_QTY_VALUE_BY_DAY] CTE
						  INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON CTE.SPARE_PART_CODE = SP.CODE AND CTE.DEPT_CODE =SP.SP_DEPT_CODE
						  WHERE DEPT_CODE = @A_DEPARTMENT AND WEEK = CAST(@A_TIME AS INT) AND YEAR([DATE]) = YEAR(GETDATE()) AND SP.TYPE = CASE WHEN @A_TYPE_CATEGORY = '1' OR @A_TYPE_CATEGORY = '2' THEN @A_TYPE_CATEGORY ELSE SP.TYPE END
						  ORDER BY [DATE] DESC

						  DECLARE @TOTAL_WEEK FLOAT = 0;
						  SELECT @TOTAL_WEEK = SUM(ISNULL([INVENTORY_VALUES_VN],0)) FROM @DATA_WEEK

						  IF @TOTAL_WEEK > 0
						     BEGIN
							       SELECT TOP(CAST(@A_TOP AS INT)) ISNULL(SP.NAME_VI,sp.NAME_KR)  + '(' + SP.CODE + ')'  as SPARE_PART_CODE,INVENTORY_VALUE,PERCENT_VALUE,SUM(PERCENT_VALUE) OVER(ORDER BY INVENTORY_VALUE DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE
								   FROM(
									SELECT  SPARE_PART_CODE,INVENTORY_VALUES_VN*@VND_KRW AS INVENTORY_VALUE,100*[INVENTORY_VALUES_VN]/@TOTAL_WEEK AS PERCENT_VALUE
									FROM @DATA_WEEK) SUB
									INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON SUB.SPARE_PART_CODE = SP.CODE AND sp.SP_DEPT_CODE = @A_DEPARTMENT
									ORDER BY INVENTORY_VALUE DESC

									SELECT ISNULL(SP.NAME_VI,sp.NAME_KR) + '(' + SP.CODE + ')'  as SPARE_PART_CODE,INVENTORY_VALUE,PERCENT_VALUE,SUM(PERCENT_VALUE) OVER(ORDER BY INVENTORY_VALUE DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE
								    FROM(
									SELECT SPARE_PART_CODE,INVENTORY_VALUES_VN*@VND_KRW AS INVENTORY_VALUE,100*[INVENTORY_VALUES_VN]/@TOTAL_WEEK AS PERCENT_VALUE
									FROM @DATA_WEEK) SUB
									INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON SUB.SPARE_PART_CODE = SP.CODE AND sp.SP_DEPT_CODE = @A_DEPARTMENT
									ORDER BY INVENTORY_VALUE DESC
							 END

					END
				ELSE IF @A_TYPE = 'QUARTER'
				     BEGIN
							DECLARE @DATA_QUARTER TABLE
						   (	SPARE_PART_CODE  NVARCHAR(50),
								[INVENTORY_VALUES_VN] FLOAT,
								QUARTERS INT
							)

						  INSERT INTO @DATA_QUARTER
						  SELECT TOP 1 WITH TIES SPARE_PART_CODE,INVENTORY_VALUES_VN,[QUARTER]
						  FROM [dbo].[EWIP_INVENTORY_QTY_VALUE_BY_DAY] CTE
						  INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON CTE.SPARE_PART_CODE = SP.CODE AND CTE.DEPT_CODE =SP.SP_DEPT_CODE
						  WHERE DEPT_CODE = @A_DEPARTMENT AND [QUARTER] = CAST(@A_TIME AS INT) AND YEAR([DATE]) = YEAR(GETDATE()) AND SP.TYPE = CASE WHEN @A_TYPE_CATEGORY = '1' OR @A_TYPE_CATEGORY = '2' THEN @A_TYPE_CATEGORY ELSE SP.TYPE END
						  ORDER BY [DATE] DESC

						  DECLARE @TOTAL_QUARTER FLOAT = 0;
						  SELECT @TOTAL_QUARTER = SUM(ISNULL([INVENTORY_VALUES_VN],0)) FROM @DATA_QUARTER

						  IF @TOTAL_QUARTER > 0
						     BEGIN
							       SELECT TOP(CAST(@A_TOP AS INT)) ISNULL(SP.NAME_VI,sp.NAME_KR) + '(' + SP.CODE + ')'  as SPARE_PART_CODE,INVENTORY_VALUE,PERCENT_VALUE,SUM(PERCENT_VALUE) OVER(ORDER BY INVENTORY_VALUE DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE
								   FROM(
									SELECT SPARE_PART_CODE,INVENTORY_VALUES_VN*@VND_KRW AS INVENTORY_VALUE,100*[INVENTORY_VALUES_VN]/@TOTAL_QUARTER AS PERCENT_VALUE
									FROM @DATA_QUARTER) SUB
									INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON SUB.SPARE_PART_CODE = SP.CODE AND sp.SP_DEPT_CODE = @A_DEPARTMENT
									ORDER BY INVENTORY_VALUE DESC

									SELECT ISNULL(SP.NAME_VI,sp.NAME_KR) + '(' + SP.CODE + ')'  as SPARE_PART_CODE,INVENTORY_VALUE,PERCENT_VALUE,SUM(PERCENT_VALUE) OVER(ORDER BY INVENTORY_VALUE DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE
								    FROM(
									SELECT SPARE_PART_CODE,INVENTORY_VALUES_VN*@VND_KRW AS INVENTORY_VALUE,100*[INVENTORY_VALUES_VN]/@TOTAL_QUARTER AS PERCENT_VALUE
									FROM @DATA_QUARTER) SUB
									INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON SUB.SPARE_PART_CODE = SP.CODE AND sp.SP_DEPT_CODE = @A_DEPARTMENT
									ORDER BY INVENTORY_VALUE DESC
							 END
					 END
				 ELSE IF  @A_TYPE = 'YEAR'
				    BEGIN

							DECLARE @DATA_YEAR TABLE
						   (	SPARE_PART_CODE  NVARCHAR(50),
								[INVENTORY_VALUES_VN] FLOAT,
								YEARS INT
							)

							 INSERT INTO @DATA_YEAR
							 SELECT TOP 1 WITH TIES [SPARE_PART_CODE],[INVENTORY_VALUES_VN],[YEAR]
							 FROM [dbo].[EWIP_INVENTORY_VALUES_BY_TIME] CTE
							 INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON CTE.SPARE_PART_CODE = SP.CODE AND CTE.DEPT_CODE =SP.SP_DEPT_CODE
							 WHERE DEPT_CODE = @A_DEPARTMENT AND [YEAR] = YEAR(CAST(@A_TIME AS DATE)) AND SP.TYPE = CASE WHEN @A_TYPE_CATEGORY = '1' OR @A_TYPE_CATEGORY = '2' THEN @A_TYPE_CATEGORY ELSE SP.TYPE END
							 ORDER BY [DATE] DESC


							DECLARE @TOTAL_VALUE_YEAR FLOAT = 0
						 
						    SELECT @TOTAL_VALUE_YEAR = SUM(ISNULL([INVENTORY_VALUES_VN],0)) FROM @DATA_YEAR

						 IF @TOTAL_VALUE_YEAR > 0
						    BEGIN
							    SELECT TOP(CAST(@A_TOP AS INT)) ISNULL(SP.NAME_VI,sp.NAME_KR) + '(' + SP.CODE + ')'  as SPARE_PART_CODE,INVENTORY_VALUE,PERCENT_VALUE,SUM(PERCENT_VALUE) OVER(ORDER BY INVENTORY_VALUE DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE
								   FROM(
									SELECT SPARE_PART_CODE,INVENTORY_VALUES_VN*@VND_KRW AS INVENTORY_VALUE,100*[INVENTORY_VALUES_VN]/@TOTAL_VALUE_YEAR AS PERCENT_VALUE
									FROM @DATA_YEAR) SUB
									INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON SUB.SPARE_PART_CODE = SP.CODE AND sp.SP_DEPT_CODE = @A_DEPARTMENT
									ORDER BY INVENTORY_VALUE DESC

									SELECT ISNULL(SP.NAME_VI,sp.NAME_KR) + '(' + SP.CODE + ')'  as SPARE_PART_CODE,INVENTORY_VALUE,PERCENT_VALUE,SUM(PERCENT_VALUE) OVER(ORDER BY INVENTORY_VALUE DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUMULATIVE
								    FROM(
									SELECT SPARE_PART_CODE,INVENTORY_VALUES_VN*@VND_KRW AS INVENTORY_VALUE,100*[INVENTORY_VALUES_VN]/@TOTAL_VALUE_YEAR AS PERCENT_VALUE
									FROM @DATA_YEAR) SUB
									INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON SUB.SPARE_PART_CODE = SP.CODE AND sp.SP_DEPT_CODE = @A_DEPARTMENT
									ORDER BY INVENTORY_VALUE DESC
						    END
					END
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
