SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PO@GET_PR_BY_PO](
@A_PO_ID NVARCHAR(50),
@A_PO_TEMP  NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			
			SELECT OPR.PR_CODE
			FROM [dbo].[EWIP_ORDER] OD
			INNER JOIN [dbo].[EWIP_ORDER_PR] OPR ON OD.[PO_ID_TEMP] = OPR.PO_ID_TEMP
			WHERE OD.PO_ID = @A_PO_ID AND OD.[PO_ID_TEMP] = @A_PO_TEMP
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
