SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP_MIN_STOCK@PUT](
@A_DEPARTMENT		NVARCHAR(50),
@A_STOCK            VARCHAR(50),
@A_SPARE_PART_CODE  NVARCHAR(50),
@A_UNIT             VARCHAR(20),
@A_MIN_STOCK        FLOAT,
@A_RATE_ALARM       FLOAT,
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			DECLARE @CHECK2 int;

			SELECT @CHECK2 = COUNT(*) FROM [dbo].[EWIP_SETUP_MINSTOCK] WHERE [SPARE_PART_CODE] = @A_SPARE_PART_CODE AND [DEPT_CODE] = @A_DEPARTMENT AND STOCK_CODE = @A_STOCK

			IF @CHECK2 > 0 
				UPDATE [dbo].[EWIP_SETUP_MINSTOCK] 
				SET [MIN_STOCK] = @A_MIN_STOCK ,UNIT_CODE = @A_UNIT ,[RATE_ALARM] = @A_RATE_ALARM,[DATE_UPDATE] = SYSDATETIME()  
				WHERE [SPARE_PART_CODE] = @A_SPARE_PART_CODE AND [DEPT_CODE] = @A_DEPARTMENT AND STOCK_CODE = @A_STOCK
			ELSE
			   INSERT INTO [dbo].[EWIP_SETUP_MINSTOCK]
			   VALUES(@A_SPARE_PART_CODE,@A_UNIT,@A_MIN_STOCK,@A_STOCK,@A_DEPARTMENT,@A_RATE_ALARM,SYSDATETIME())

			  IF EXISTS(SELECT * FROM [dbo].[EWIP_BOM_BY_MONTH] WHERE MONTH = MONTH(GETDATE()) AND YEART = YEAR(GETDATE()))
			     BEGIN
						UPDATE [dbo].[EWIP_BOM_BY_MONTH]
						SET [MIN_STOCK_PACK] = @A_MIN_STOCK * dbo.CONVERT_UNIT(@A_UNIT,'PACK',SPARE_PART_CODE,@A_DEPARTMENT)
						WHERE SPARE_PART_CODE = @A_SPARE_PART_CODE AND DEPT_CODE = @A_DEPARTMENT
				 END
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
