SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_LOCATION@INSERT_BATCH](
@A_LOCATION_TYPE   LOCATION_TYPE  READONLY,
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			DECLARE @DEPART_MENT NVARCHAR(100);
			DECLARE @STOCK VARCHAR(50);
			SELECT DISTINCT @DEPART_MENT =[DEPT_CODE],@STOCK=[STOCK_CODE] FROM @A_LOCATION_TYPE
			INSERT INTO [dbo].[EWIP_LOCATIONS]
            SELECT CODE,[STOCK_CODE],[DEPT_CODE],GETDATE() FROM @A_LOCATION_TYPE WHERE CODE NOT IN (SELECT CODE FROM [dbo].[EWIP_LOCATIONS] WHERE [DEPT_CODE] = @DEPART_MENT AND [STOCK_CODE] = @STOCK)
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
