SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_COMM@GET_LOGIN](
@A_PLANT VARCHAR(50),
@A_USER_ID VARCHAR(50),
@A_DEPARTMENT VARCHAR(50),
@N_RETURN  int			 OUTPUT,
@V_RETURN  NVARCHAR(4000) OUTPUT
)
AS 
BEGIN TRY
	SELECT T1.PASSWORD AS PASSWORD,
			T1.USER_ID AS USER_ID,
			T1.USER_NAME AS USER_NAME
	FROM ESYSMSTUSR T1
	WHERE T1.PLANT = @A_PLANT
	AND T1.USER_ID = @A_USER_ID
	AND T1.DEPARTMENT IN(@A_DEPARTMENT,'ALL')
	AND T1.USEFLAG = 'Y';
  
	SELECT T1.USERROLE,
		   T2.USERROLE_NAME
	FROM ESYSMSTURO T1,
		 ESYSMSTROL T2
	WHERE T1.PLANT = @A_PLANT
	AND T1.USER_ID = @A_USER_ID
	AND T2.PLANT = T1.PLANT
	AND T2.USERROLE = T1.USERROLE;

DECLARE @V_MASTER_FLAG VARCHAR(1);
SET @V_MASTER_FLAG = (SELECT T1.MASTER_FLAG FROM ESYSMSTUSR T1 WHERE T1.USER_ID = @A_USER_ID AND T1.DEPARTMENT = @A_DEPARTMENT)
IF(@V_MASTER_FLAG = 'Y')
BEGIN	
		SELECT DISTINCT T4.[CONTROL_TEXT] AS 'Text',T4.[CONTROL_NAME] AS 'Name',T4.[MENU_SEQ] AS 'FormId',CAST(ISNULL(T4.[USE_FLAG],'False') AS bit) AS 'IsActive',T1.FORM
	    FROM ESYSMSTMEU T1 
			LEFT OUTER JOIN ESYSMSTGLA T2 ON T2.PLANT = T1.PLANT AND T2.GLSR = T1.MENUNAME
			LEFT JOIN (SELECT T1.USERROLE,
							  T2.USERROLE_NAME,
							  T1.PLANT
						FROM ESYSMSTURO T1,
							 ESYSMSTROL T2
						WHERE T1.PLANT = @A_PLANT
						AND T1.USER_ID = @A_USER_ID
						AND T2.PLANT = T1.PLANT
						AND T2.USERROLE = T1.USERROLE AND T1.DEPARTMENT IN(@A_DEPARTMENT,'ALL') AND T2.DEPARTMENT IN(@A_DEPARTMENT,'ALL')) AS SUB ON T1.PLANT = SUB.PLANT 
		   LEFT OUTER JOIN ESYSMSTMRO T3 ON T3.PLANT = T1.PLANT AND T3.MENUSEQ = T1.MENUSEQ AND T3.USERROLE = sub.USERROLE AND t3.DEPARTMENT IN(@A_DEPARTMENT,'ALL')
		   LEFT OUTER JOIN [dbo].[ESYSM_CONTROLS_ROL] T4 ON T4.USERROLE = sub.USERROLE AND T4.DEPARTMENT IN(@A_DEPARTMENT,'ALL') AND T4.PLANT = @A_PLANT AND t4.MENU_SEQ = t1.MENUSEQ
       WHERE T1.PLANT = @A_PLANT
END
ELSE
BEGIN
		SELECT DISTINCT T4.[CONTROL_TEXT] AS 'Text',T4.[CONTROL_NAME] AS 'Name',T4.[MENU_SEQ] AS 'FormId',CAST(ISNULL(T4.[USE_FLAG],'False') AS bit) AS 'IsActive',T1.FORM
	    FROM ESYSMSTMEU T1 
			LEFT OUTER JOIN ESYSMSTGLA T2 ON T2.PLANT = T1.PLANT AND T2.GLSR = T1.MENUNAME
			LEFT JOIN (SELECT T1.USERROLE,
							  T2.USERROLE_NAME,
							  T1.PLANT
						FROM ESYSMSTURO T1,
							 ESYSMSTROL T2
						WHERE T1.PLANT = @A_PLANT
						AND T1.USER_ID = @A_USER_ID
						AND T2.PLANT = T1.PLANT
						AND T2.USERROLE = T1.USERROLE AND T1.DEPARTMENT IN(@A_DEPARTMENT,'ALL') AND T2.DEPARTMENT IN(@A_DEPARTMENT,'ALL')) AS SUB ON T1.PLANT = SUB.PLANT 
			LEFT OUTER JOIN ESYSMSTMRO T3 ON T3.PLANT = T1.PLANT AND T3.MENUSEQ = T1.MENUSEQ AND T3.USERROLE = sub.USERROLE AND t3.DEPARTMENT IN(@A_DEPARTMENT,'ALL')
			LEFT OUTER JOIN [dbo].[ESYSM_CONTROLS_ROL] T4 ON T4.USERROLE = sub.USERROLE AND T4.DEPARTMENT IN(@A_DEPARTMENT,'ALL') AND T4.PLANT = @A_PLANT AND t4.MENU_SEQ = t1.MENUSEQ
       WHERE T1.PLANT = @A_PLANT
	   AND T1.MENUNAME <> 'SYSTEM001' AND T1.MENUNAME <>'SYSTEM002' AND T1.MENUNAME <> 'SYSTEM006' AND T1.MENUNAME <>'SYSTEM007' AND T1.MENUNAME <>'SYSTEM014'
	   AND T1.MENUNAME <> 'MENU_LOG' AND T1.MENUNAME <> 'LOGDAT001' AND T1.MENUNAME <> 'LOGDAT002'
	   AND T1.USEFLAG = 'Y'
END

  SET @N_RETURN = 0;
  SET @V_RETURN = 'MSG_COM_004';
END TRY
BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH


GO
