SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_COMM@GET_MENU](
@A_PLANT		VARCHAR(50),
@A_USER_ID		VARCHAR(50),
@A_LANG			VARCHAR(50),
@A_ACCESS_IP	VARCHAR(50),
@A_ACCESS_PC	VARCHAR(50),
@A_DEPARTMENT	VARCHAR(50),
@N_RETURN		int				OUTPUT,
@V_RETURN		NVARCHAR(4000)	OUTPUT
)
AS

DECLARE @N_CHECK		int;
DECLARE @V_TRAN_TIME	VARCHAR(14);

DECLARE @V_FROM_TIME	VARCHAR(14);
DECLARE @V_TO_TIME		VARCHAR(14);

BEGIN TRY

	SET @V_TRAN_TIME = [dbo].[FUN_CURR_TIME]();

	SELECT @N_CHECK = ISNULL(MAX(T1.HIST_SEQ), 0)
	FROM ESYSLOGLGN T1
	WHERE T1.PLANT = @A_PLANT
	AND T1.USER_ID = @A_USER_ID
	AND T1.DEPARTMENT = @A_DEPARTMENT;

	SET @N_CHECK = @N_CHECK + 1;

	INSERT INTO ESYSLOGLGN(
		PLANT,
		DEPARTMENT,
		USER_ID,
		HIST_SEQ,
		ACCESS_TIME,
		ACCESS_IP,
		ACCESS_PC
	) VALUES (
		@A_PLANT,
		@A_DEPARTMENT,
		@A_USER_ID,
		@N_CHECK,
		@V_TRAN_TIME,
		@A_ACCESS_IP,
		@A_ACCESS_PC
	);

    SELECT T1.MENUSEQ AS MENUSEQ,
            cast(T1.UPRSEQ as varchar(10)) AS UPRSEQ,
            MAX(ISNULL(CASE WHEN @A_LANG = 'KOR' THEN T3.KOR
					 WHEN @A_LANG = 'ENG' THEN T3.ENG
					 WHEN @A_LANG = 'VTN' THEN T3.VTN
					 WHEN @A_LANG = 'CHN' THEN T3.CHN
					 ELSE T3.KOR END, T3.KOR)) AS MENUNAME,
            MAX(T1.FORM) AS FORM,
            MAX(T4.FORMROLE) AS FORMROLE,
            MAX(T1.DISPSEQ) AS DISPSEQ,
            MAX(T1.IMGIDX) AS IMGIDX,
			MAX(T6.ACCESS_TYPE) AS ACCESS_TYPE,
			MAX(T1.IMAGE) AS IMAGE
    FROM ESYSMSTMEU T1
         LEFT OUTER JOIN ESYSMSTMEU T2 ON T2.PLANT = T1.PLANT AND T2.MENUSEQ = T1.UPRSEQ 
         LEFT OUTER JOIN ESYSMSTGLA T3 ON T3.PLANT = T1.PLANT AND T3.GLSR = T1.MENUNAME 
         INNER JOIN ESYSMSTMRO T4 ON T4.PLANT = T1.PLANT AND T4.MENUSEQ = T1.MENUSEQ AND T4.PLANT = T1.PLANT 
         INNER JOIN ESYSMSTURO T5 ON T5.PLANT = T1.PLANT AND T4.USERROLE = T5.USERROLE AND T5.USER_ID = @A_USER_ID
		 LEFT OUTER JOIN ESYSMSTFORM T6 ON T6.PLANT = T1.PLANT AND T6.FORM = T1.FORM 
    WHERE
    T4.USEFLAG = 'Y'
    AND T1.USEFLAG = 'Y'
    AND T1.DISPFLAG = 'Y'
	AND T1.FORM_GUBUN = 'PC'
	AND T1.DEPARTMENT IN ('ALL', @A_DEPARTMENT)
	--AND (T1.UPRSEQ LIKE '1%' OR T1.UPRSEQ LIKE '2%' OR T1.UPRSEQ LIKE '5%')
	GROUP BY T1.MENUSEQ, T1.UPRSEQ
    --ORDER BY ISNULL(T1.UPRSEQ, 0), MAX(T1.DISPSEQ)
	ORDER BY T1.MENUSEQ

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
