SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_DOCUMENT@DOWNLOAD](
@A_CODE             NVARCHAR(50),-- MA THIET BI
@A_DEPARTMENT		NVARCHAR(50),
@A_FILE_NAME        NVARCHAR(250),
@A_CONTENT_TYPE     NVARCHAR(250),
@A_IS_EQUIPMENT     NVARCHAR(5),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  

			SELECT * FROM [dbo].[EWIP_SPAREPART_DOCUMENT]
			WHERE [CODE]= @A_CODE AND [DEPT_CODE] = @A_DEPARTMENT AND [NAME] = @A_FILE_NAME AND [CONTENT_TYPE] = @A_CONTENT_TYPE AND [IS_EQUIPMENT] = @A_IS_EQUIPMENT

		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
