SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_GOC_PLAN@IMPORT_SMT](
@A_USER NVARCHAR(50),
@A_DATA [dbo].[GOC_PLAN_SMT] READONLY,
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			BEGIN TRAN

			TRUNCATE TABLE [EWIP_GOC_PLAN_SMT]

			 MERGE [dbo].[EWIP_GOC_PLAN_SMT] AS TARGET
			 USING @A_DATA AS SOURCE ON (TARGET.MODEL = SOURCE.MODEL AND TARGET.[MONTH] = cast(SOURCE.[MONTH] as INT) AND TARGET.[YEAR_PLAN] = SOURCE.[YEAR_PLAN] AND TARGET.[WEEK] = CAST(SOURCE.[WEEK] AS INT))
			 WHEN MATCHED
			       THEN UPDATE SET [UPDATE_DATE] = CAST(SOURCE.[UPDATE_DATE] AS DATE),
				                   [SALES_PLAN] = CAST(SOURCE.[SALES_PLAN] AS FLOAT),
								   [SALES_PLAN_POINT] = CAST(SOURCE.[SALES_PLAN_POINT] AS FLOAT),
								   [WHC_PLAN] = CAST(SOURCE.[WHC_PLAN] AS FLOAT),
								   [WHC_PLAN_POINT] = CAST(SOURCE.[WHC_PLAN_POINT] AS FLOAT),
								   [STOCK] = CAST(SOURCE.[STOCK] AS FLOAT),
							       [STOCK_POINT] = CAST(SOURCE.[STOCK_POINT] AS FLOAT),
								   [UPDATE_TIME_SYS] = SYSDATETIME(),
								   [USER_UPDATE] = @A_USER
			 WHEN NOT MATCHED BY TARGET
			       THEN INSERT
					      VALUES(SOURCE.[WEEK]
					   		,CAST(SOURCE.[UPDATE_DATE] as DATE)
					   		,SOURCE.[MONTH]
					   		,SOURCE.[MODEL]
					   		,SOURCE.[MODEL_NAME]
					   		,SOURCE.[SALES_PLAN]
					   		,SOURCE.[SALES_PLAN_POINT]
					   		,SOURCE.[WHC_PLAN]
					   		,SOURCE.[WHC_PLAN_POINT]
					   		,SOURCE.[STOCK]
					   		,SOURCE.[STOCK_POINT]
					   		,SYSDATETIME()
					   		,@A_USER
					   		,SOURCE.[YEAR_PLAN]);
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
	COMMIT TRAN
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
  ROLLBACK TRAN
END CATCH
GO
