SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_LOCATION@INSERT_BATCH_VALUE_BY_DAY]
AS
BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			BEGIN TRAN
			DECLARE @A_DEPARTMENT    NVARCHAR(100)
			DECLARE @A_STOCK          NVARCHAR(50)
			DECLARE @SPARE_PART_CODE NVARCHAR(50)
			DECLARE @N_RETURN	int	
			DECLARE @V_RETURN	NVARCHAR(4000)

			DECLARE @IN_VALUE_VN_T6 FLOAT = 0
			DECLARE @IN_VALUE_US_T6 FLOAT = 0
			DECLARE @OUT_VALUE_VN_T6 FLOAT = 0
			DECLARE @OUT_VALUE_US_T6 FLOAT = 0
			DECLARE @IV_VALUE_VN_T6 FLOAT = 0
			DECLARE @IV_VALUE_US_T6 FLOAT = 0

			DECLARE @IN_VALUE_VN_T7 FLOAT = 0
			DECLARE @OUT_VALUE_VN_T7 FLOAT = 0
			DECLARE @IV_VALUE_VN_T7 FLOAT = 0
			DECLARE @IN_VALUE_US_T7 FLOAT = 0
			DECLARE @OUT_VALUE_US_T7 FLOAT = 0
			DECLARE @IV_VALUE_US_T7 FLOAT = 0

			DECLARE @IN_VALUE_VN_T8 FLOAT = 0
			DECLARE @OUT_VALUE_VN_T8 FLOAT = 0
			DECLARE @IV_VALUE_VN_T8 FLOAT = 0
			DECLARE @IN_VALUE_US_T8 FLOAT = 0
			DECLARE @OUT_VALUE_US_T8 FLOAT = 0
			DECLARE @IV_VALUE_US_T8 FLOAT = 0


			DECLARE @IN_VALUE_VN_T9 FLOAT = 0
			DECLARE @OUT_VALUE_VN_T9 FLOAT = 0
			DECLARE @IV_VALUE_VN_T9 FLOAT = 0
			DECLARE @IN_VALUE_US_T9 FLOAT = 0
			DECLARE @OUT_VALUE_US_T9 FLOAT = 0
			DECLARE @IV_VALUE_US_T9 FLOAT = 0

		
			DECLARE cursorDept3 CURSOR LOCAL FOR
			SELECT [CODE] FROM [dbo].[ESYSMSTDEPT] WHERE CODE = 'SMT'

			OPEN cursorDept3

			FETCH NEXT FROM cursorDept3
			INTO @A_DEPARTMENT

			WHILE @@FETCH_STATUS = 0
				BEGIN
					 PRINT @A_DEPARTMENT 
					 DECLARE cursorStock CURSOR LOCAL FOR
					 SELECT [CODE] FROM [dbo].[EWIP_STOCK] WHERE [DEPT_CODE] = 'SMT'

					 OPEN cursorStock

					 FETCH NEXT FROM cursorStock
					 INTO @A_STOCK

					 WHILE @@FETCH_STATUS = 0
					    BEGIN						


								DECLARE cursorSparepart CURSOR LOCAL FOR
								SELECT [CODE] FROM [dbo].[EWIP_SPARE_PART] WHERE [SP_DEPT_CODE] = 'SMT'
							  
								OPEN cursorSparepart

								FETCH NEXT FROM cursorSparepart
								INTO @SPARE_PART_CODE

								WHILE @@FETCH_STATUS = 0
							  	  BEGIN
								    --     PRINT @SPARE_PART_CODE
								    --      EXEC [dbo].[PKG_BUSINESS_CHART_IN_OUT_STOCK@GET_DATA_BY_DAY]
												--@A_TYPE_TIME = 'DAY',
												--@A_TYPE_VALUE = 'MONEY',
												--@A_FROM = '2021-09-18',
												--@A_TO  = '2021-09-18',
												--@A_DEPARTMENT  = 'SMT',
												--@A_SPARE_PART_CODE = @SPARE_PART_CODE,
												--@N_RETURN	= @N_RETURN	OUT,
												--@V_RETURN	 = @V_RETURN   OUT
                                             
											 SELECT @IN_VALUE_VN_T6 = SUM(IN_VALUES_VN),@IN_VALUE_US_T6 = SUM(IN_VALUES_US) 
											 FROM [EWIP_INVENTORY_QTY_VALUE_BY_DAY]
											 WHERE SPARE_PART_CODE = @SPARE_PART_CODE AND MONTH([DATE]) = 9 AND YEAR([DATE]) = 2021 AND DEPT_CODE = 'SMT'

											 SELECT @OUT_VALUE_US_T6 = SUM(OUT_VALUES_US),@OUT_VALUE_VN_T6 = SUM(OUT_VALUES_VN) 
											 FROM [EWIP_INVENTORY_QTY_VALUE_BY_DAY]
											 WHERE SPARE_PART_CODE = @SPARE_PART_CODE AND MONTH([DATE]) = 9 AND YEAR([DATE]) = 2021 AND DEPT_CODE = 'SMT'

											 SELECT TOP 1 @IV_VALUE_VN_T6 = INVENTORY_VALUES_VN,@IV_VALUE_US_T6 = INVENTORY_VALUES_US
											 FROM [EWIP_INVENTORY_QTY_VALUE_BY_DAY]
											 WHERE SPARE_PART_CODE = @SPARE_PART_CODE AND MONTH([DATE]) = 9 AND YEAR([DATE]) = 2021 AND DEPT_CODE = 'SMT'
											 ORDER BY DATE DESC

											 IF EXISTS(SELECT * FROM [dbo].[EWIP_INVENTORY_VALUES_BY_TIME] WHERE SPARE_PART_CODE = @SPARE_PART_CODE AND DEPT_CODE =  'SMT' AND [MONTH] = 9 AND [YEAR] = 2021)
											    BEGIN
														UPDATE [dbo].[EWIP_INVENTORY_VALUES_BY_TIME]
														SET [IN_VALUES_VN] = @IN_VALUE_VN_T6,
														    [IN_VALUES_US] = @IN_VALUE_US_T6,
															[OUT_VALUES_VN] = @OUT_VALUE_VN_T6,
															[OUT_VALUES_US] = @OUT_VALUE_US_T6,
															[INVENTORY_VALUES_VN] = @IV_VALUE_VN_T6,
															[INVENTORY_VALUES_US] = @IV_VALUE_US_T6
															WHERE SPARE_PART_CODE = @SPARE_PART_CODE AND DEPT_CODE =  'SMT' AND [MONTH] = 9 AND [YEAR] = 2021
												END
											 ELSE
											      INSERT INTO [dbo].[EWIP_INVENTORY_VALUES_BY_TIME]
												  VALUES(@SPARE_PART_CODE,'SMT','SMT_K1',GETDATE(),9,2021,@IN_VALUE_VN_T6,@OUT_VALUE_VN_T6,@IV_VALUE_VN_T6,@IN_VALUE_US_T6,@OUT_VALUE_US_T6,@IV_VALUE_US_T6,GETDATE())

											FETCH NEXT FROM cursorSparepart
											INTO @SPARE_PART_CODE
								   END
								   CLOSE cursorSparepart
								  DEALLOCATE cursorSparepart

								FETCH NEXT FROM cursorStock
								INTO @A_STOCK
						END

						CLOSE cursorStock
						DEALLOCATE cursorStock

					 FETCH NEXT FROM cursorDept3
					INTO @A_DEPARTMENT
				END

			CLOSE cursorDept3
			DEALLOCATE cursorDept3
				COMMIT TRAN;
		END
END TRY
BEGIN CATCH
  ROLLBACK TRAN;
END CATCH

GO
