SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PKG_LOGDAT002@GET_LIST](
@A_PLANT			VARCHAR(50),
@A_FROM_DATE		VARCHAR(50),
@A_TO_DATE			VARCHAR(50),
@A_USER_ID			VARCHAR(50),
@A_LANG				VARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
if(@A_USER_ID = '')
set @A_USER_ID = NULL;
	SELECT T1.USER_ID AS USER_ID,
		   MAX(T2.USER_NAME) AS USER_NAME,
            T1.FORM_CODE AS FORM_CODE,
			 MAX(CASE WHEN @A_LANG = 'KOR' THEN T3.KOR
					  WHEN @A_LANG = 'VTN' THEN T3.VTN
				ELSE T3.VTN END) AS FORMNAME,
            COUNT(*) AS ACCESS_COUNTER,
            MAX(dbo.[CHAR_TO_DATE](T1.ACCESS_TIME)) AS LAST_ACCESS_TIME
    FROM ESYSLOGFOM T1,
            ESYSMSTUSR T2,
            ESYSMSTGLA T3
    WHERE T1.PLANT = @A_PLANT
    AND T2.PLANT = T1.PLANT
    AND T2.USER_ID = T1.USER_ID
    AND T3.PLANT = T1.PLANT
    AND T3.GLSR = T1.FORM_CODE
    AND T2.USER_ID = ISNULL(@A_USER_ID,T2.USER_ID)
    AND T1.ACCESS_TIME > @A_FROM_DATE+'000000' AND T1.ACCESS_TIME < @A_TO_DATE +'235959'
	and T1.USER_ID <> 'H2002001'
    GROUP BY T1.USER_ID, T1.FORM_CODE
    --ORDER BY T1.USER_ID, COUNT(*) DESC;
	ORDER BY LAST_ACCESS_TIME DESC

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH








GO
