SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_UNIT_SPAREPART@GET_UNIT_MIN_BY_SPAREPART](
@A_DEPT_CODE                 NVARCHAR(50),
@A_SPARE_PART_CODE           NVARCHAR(50),
@A_UNIT_CODE                 NVARCHAR(50),
@N_RETURN					 int OUTPUT,
@V_RETURN					 NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			SELECT UNIT_CODE,UNIT_CODE_MIN,RATE
			FROM [dbo].[EWIP_SPAREPART_UNIT] uni
			WHERE SPARE_PART_CODE = @A_SPARE_PART_CODE AND uni.DEPT_CODE = @A_DEPT_CODE AND UNIT_CODE = @A_UNIT_CODE
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
