SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_MRP_LIST_GROUP@GET](
@A_DEPARTMENT		NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		     SELECT ML.MRP_CODE, [SPAREPART_CODE],SP.NAME_VI,[QUANTITY_NEED_BUY],[UNIT],[DATE_NEED_REQUIRED],[DATE_NEED_BUY],M.[DATE_NEED_FINISH],M.[DATE_END_ACTUAL],M.[STATUS],M.ID
			 FROM [dbo].[EWIP_MRP_LIST] ML
			 INNER JOIN [dbo].[EWIP_MRP] M ON ML.MRP_CODE = M.MRP_CODE AND ML.DEPT_CODE = M.DEPT_CODE
			 INNER JOIN [dbo].[EWIP_SPARE_PART] SP ON SP.CODE = M.SPAREPART_CODE AND SP.SP_DEPT_CODE = M.DEPT_CODE
			 WHERE ML.DEPT_CODE = @A_DEPARTMENT
			 ORDER BY ML.DATE_CREATE DESC

			 SELECT MRP_CODE,TITLE,[DATE_NEED_FINISH],[STATUS] FROM [dbo].[EWIP_MRP_LIST] WHERE DEPT_CODE = @A_DEPARTMENT

			 SELECT [CODE],[NAME] FROM [dbo].[EWIP_STATUS_PUR]
        END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
