SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_EQUIPMENT_MAINTAIN@INIT](
@A_DEPARTMENT  NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			DECLARE @PACK_UNIT NVARCHAR(50) = 'PACK';

			SELECT [EQUIPMENT_ID],[EQUIPMENT_NAME],[EQUIPMENT_TYPE] FROM [dbo].[EWIP_EQUIPMENT] WHERE [DEPT_CODE] = @A_DEPARTMENT

			SELECT CODE,NAME_VI
			FROM [dbo].[EWIP_SPARE_PART]
			WHERE SP_DEPT_CODE = @A_DEPARTMENT

			SELECT [DATE_MAINTAIN],EQ_M.[SPARE_PART_CODE],
			       ISNULL(T.PRICE_US/[dbo].[CONVERT_UNIT](T.UNIT,@PACK_UNIT,T.[SPARE_PART_CODE],@A_DEPARTMENT),SUB.PRICE_US) AS PRICE_US_PACK,
				   ISNULL(T.PRICE_VN/[dbo].[CONVERT_UNIT](T.UNIT,@PACK_UNIT,T.[SPARE_PART_CODE],@A_DEPARTMENT),SUB.PRICE_VN) AS PRICE_VN_PACK,
			       EQ_M.[EQUIPMENT_ID],EQ.[EQUIPMENT_TYPE],L.[EQ_LOCATION_NAME], SP.NAME_VI,SP.NAME_KR,EQ_M.[SERIAL_PRE],CASE WHEN EQ_M.[DATE_IN_PRE] = '1900-01-01' THEN NULL ELSE EQ_M.[DATE_IN_PRE] END AS [DATE_IN_PRE],EQ_M.[CONDITION_PRE],
				   CASE WHEN  EQ_M.[DATE_IN_AFTER] = '1900-01-01' THEN NULL ELSE EQ_M.[DATE_IN_AFTER] END AS [DATE_IN_AFTER],EQ_M.[CONDITION_AFTER],
				   EQ_M.[SERIAL_AFTER],EQ_M.[GANTRY_ID],EQ_M.[SEGMENT_ID],
				   EQ_M.USER_MAINTAIN,EQ_M.MAINTAIN_ID,[TIME_MAINTAIN],CASE WHEN [DATE_SUCCESS] = '1900-01-01' THEN NULL ELSE [DATE_SUCCESS] END AS [DATE_SUCCESS],[CAUSE_MAINTAIN],[IMAGE_ERROR]
			FROM [dbo].[EWIP_EQUIPMENT_MAINTAIN] EQ_M
			LEFT JOIN [dbo].[EWIP_EQUIPMENT] EQ ON EQ_M.[EQUIPMENT_ID] = EQ.[EQUIPMENT_ID] AND EQ_M.[DEPT_CODE] = EQ.[DEPT_CODE]
			LEFT JOIN [dbo].[EWIP_EQUIPMENT_LOCATION_RELATION] EQ_L ON EQ_L.[EQUIPMENT_ID] = EQ_M.[EQUIPMENT_ID]  AND EQ_L.[DEPT_CODE] = EQ_M.[DEPT_CODE]
			LEFT JOIN [dbo].[EWIP_EQUIPMENT_LOCATION] L ON EQ_L.[EQ_LOCATION_ID] = L.ID
			LEFT JOIN [dbo].[EWIP_SPARE_PART] SP ON SP.CODE = EQ_M.[SPARE_PART_CODE] AND SP.SP_DEPT_CODE = EQ_M.[DEPT_CODE]
			LEFT JOIN (SELECT TOP 1 WITH TIES 
						[SPARE_PART_CODE],
						[PRICE_VN]/[dbo].[CONVERT_UNIT]([UNIT_CODE],@PACK_UNIT,[SPARE_PART_CODE],@A_DEPARTMENT) AS [PRICE_VN],
						[PRICE_US]/[dbo].[CONVERT_UNIT]([UNIT_CODE],@PACK_UNIT,[SPARE_PART_CODE],@A_DEPARTMENT) AS [PRICE_US], 
						@PACK_UNIT AS UNIT
						FROM [dbo].[EWIP_SPAREPART_PRICE]
						WHERE [DEPT_CODE] = @A_DEPARTMENT 
						ORDER BY ROW_NUMBER() OVER(PARTITION BY SPARE_PART_CODE ORDER BY [DATE] DESC)) SUB ON SUB.SPARE_PART_CODE = EQ_M.[SPARE_PART_CODE]
			LEFT JOIN [dbo].[EWIP_INVENTORY_BY_TIME] T ON [MONTH_MAINTAIN] = T.[MONTH] AND [YEAR_MAINTAIN] = [YEAR] AND T.[SPARE_PART_CODE] = EQ_M.[SPARE_PART_CODE] AND T.DEPT_CODE = EQ_M.[DEPT_CODE]
			WHERE EQ_M.[DEPT_CODE] = @A_DEPARTMENT

			SET @N_RETURN = 0;
			SET @V_RETURN = 'MSG_COM_004';
		END
END TRY
BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
