SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_CHART_IN_OUT_STOCK@INIT_SPAREPART](
@A_DEPARTMENT		NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			SELECT SP.CODE,SP.NAME_VI AS [NAME]
			FROM  [dbo].[EWIP_SPARE_PART] SP  
			INNER JOIN [dbo].[EWIP_SPARE_PART_DEPT] SD ON SP.CODE = SD.SPARE_PART_CODE AND SP.SP_DEPT_CODE = SD.DEPT_CODE
			WHERE SP.SP_DEPT_CODE = @A_DEPARTMENT
			ORDER BY SP.ID

			SELECT CODE,[DEPARTMENT]
			FROM [dbo].[ESYSMSTDEPT]
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
