SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_PRICE@INIT](
@A_DEPT_CODE  NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			SELECT TOP 1 RATE FROM [dbo].[EWIP_EXCHANGE_RATE] WHERE [FROM] = 'USD' AND [TO] = 'VND'
			ORDER BY [VALID_TIME] DESC

			SELECT PRICE.ID,SP.CODE as SPARE_PART_CODE,SP.NAME_VI,SP.NAME_KR,[PRICE_VN],[PRICE_US],[UNIT_CODE] AS UNIT,[DATE],T.NAME AS TYPENAME,[INPUT_DEFAULT],O.[OPERATION_NAME] AS STAGE
			FROM [dbo].[EWIP_SPAREPART_PRICE] PRICE
			RIGHT JOIN [dbo].[EWIP_SPARE_PART] SP ON PRICE.DEPT_CODE = SP.SP_DEPT_CODE AND PRICE.SPARE_PART_CODE = SP.CODE
			LEFT JOIN [dbo].[EWIP_SPAREPART_TYPE] T ON SP.TYPE = T.CODE
			LEFT JOIN [dbo].[EWIP_OPERATION] O ON SP.DESCRIPTION = O.[OPERATION_ID] AND SP.SP_DEPT_CODE = O.[DEPT_CODE]
			WHERE SP.SP_DEPT_CODE = @A_DEPT_CODE
			ORDER BY PRICE.DATE DESC

			SELECT CODE,NAME_VI FROM [dbo].[EWIP_SPARE_PART] WHERE SP_DEPT_CODE = @A_DEPT_CODE

			SELECT CODE,NAME FROM [dbo].[EWIP_UNITS]

			SELECT TOP 1 RATE FROM [dbo].[EWIP_EXCHANGE_RATE] WHERE [FROM] = 'KRW' AND [TO] = 'VND'
			ORDER BY [VALID_TIME] DESC
       END
	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
