SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_UNIT_SPAREPART@GET_UNIT_BY_SPAREPART](
@A_DEPT_CODE                 NVARCHAR(50),
@A_SPARE_PART_CODE           NVARCHAR(50),
@N_RETURN					 int OUTPUT,
@V_RETURN					 NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			SELECT UNIT_CODE AS CODE,UNIT_CODE AS [NAME] , sp.IMAGE  
			FROM [dbo].[EWIP_SPAREPART_UNIT] uni
			INNER JOIN [dbo].[EWIP_SPARE_PART] sp ON sp.CODE = uni.SPARE_PART_CODE AND sp.[SP_DEPT_CODE] = uni.DEPT_CODE
			WHERE SPARE_PART_CODE = @A_SPARE_PART_CODE AND uni.DEPT_CODE = @A_DEPT_CODE
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH
GO
