SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[PKG_BUSINESS_SP@GET_DATA_TO_EXCEL](
@A_DEPARTMENT		NVARCHAR(50),
@N_RETURN			int				OUTPUT,
@V_RETURN			NVARCHAR(4000)	OUTPUT
)
AS

BEGIN TRY
		BEGIN
		    SET NOCOUNT OFF;  
			SELECT ROW_NUMBER() OVER(ORDER BY sp.id ASC) AS Rowid,sp.CODE,sp.NAME_VI,sp.NAME_KR,sp.GL_ACCOUNT,spd.COST_CTR,v.NAME as VENDOR,SP.IMAGE,O.[OPERATION_NAME] AS STAGE,T.NAME AS TYPENAME,sp.SPECIFICATIONS AS SPECIFICATION,SP.MIN_ORDER,SP.LEAD_TIME,'' NOTE
			FROM EWIP_SPARE_PART sp 
			     INNER JOIN EWIP_SPARE_PART_DEPT spd ON sp.CODE = spd.SPARE_PART_CODE AND sp.[SP_DEPT_CODE] = spd.DEPT_CODE
				 INNER JOIN EWIP_VENDER v ON SP.VENDER_ID = V.VENDER_ID
				 INNER JOIN EWIP_UNITS u ON SP.UNIT_ID = u.CODE
				 LEFT JOIN EWIP_SPAREPART_TYPE T ON SP.TYPE = T.CODE
				 LEFT JOIN [dbo].[EWIP_MERGE_SPAREPART_CODE] ME ON SP.CODE = ME.SPARE_PART_CODE AND SP.SP_DEPT_CODE = ME.DEPT_CODE
				 LEFT JOIN [dbo].[EWIP_OPERATION] O ON SP.DESCRIPTION = O.[OPERATION_ID] AND SP.SP_DEPT_CODE = O.[DEPT_CODE]
			WHERE sp.[SP_DEPT_CODE] = @A_DEPARTMENT
			ORDER BY SP.ID ASC;
		END

	SET @N_RETURN = 0;
	SET @V_RETURN = 'MSG_COM_004';
END TRY
	BEGIN CATCH
  SET @N_RETURN = ERROR_NUMBER();
  SET @V_RETURN = ERROR_MESSAGE();
END CATCH


GO
