CREATE TABLE [dbo].[EWIP_VENDER]
(
[VENDER_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESS] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHONE] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAIL] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_VENDER] ADD CONSTRAINT [PK_EWIP_VENDER_1] PRIMARY KEY CLUSTERED ([VENDER_ID]) ON [PRIMARY]
GO
