CREATE TABLE [dbo].[EWIP_SPAREPART_CONDITION]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[CODE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_SPAREPART_CONDITION] ADD CONSTRAINT [PK_EWIP_SPAREPART_CONDITION] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', N'NEW, OKE, NG', 'SCHEMA', N'dbo', 'TABLE', N'EWIP_SPAREPART_CONDITION', 'COLUMN', N'NAME'
GO
