CREATE TABLE [dbo].[EWIP_MRP_LIST]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[MRP_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DATE_CREATE] [date] NULL,
[STATUS] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPT_CODE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DATE_END_ACTUAL] [date] NULL,
[DATE_NEED_FINISH] [date] NULL,
[USER_CREATE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_UPDATE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_UPDATE] [date] NULL,
[TITLE] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_MRP_LIST] ADD CONSTRAINT [PK_EWIP_MRP_LIST] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
