CREATE TABLE [dbo].[EWIP_SPAREPART_LEND]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[SPARE_PART_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_LEND] [date] NULL,
[QUANTITY] [float] NULL,
[UNIT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_PAY] [date] NULL,
[DATE_PAY_ACTUAL] [date] NULL,
[USER_CREATE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_UPDATE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_UPDATE] [date] NULL,
[DEPT_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IS_PAY] [bit] NULL,
[QUANTITY_PAY] [float] NULL,
[LEND_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_SPAREPART_LEND] ADD CONSTRAINT [PK_EWIP_SPAREPART_LEND] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
