CREATE TABLE [dbo].[ESYSMSTGLA]
(
[PLANT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEPARTMENT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ESYSMSTGLA_DEPARTMENT] DEFAULT ('ALL'),
[GLSR] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ENG] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KOR] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHN] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VTN] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MASTER_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATE_TIME] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CREATE_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPDATE_TIME] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPDATE_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USE_FLAG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_ESYSMSTGLA_USE_FLAG] DEFAULT ('N')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESYSMSTGLA] ADD CONSTRAINT [PK_ESYSMSTGLA] PRIMARY KEY CLUSTERED ([PLANT], [DEPARTMENT], [GLSR]) ON [PRIMARY]
GO
