CREATE TABLE [dbo].[EWIP_OPERATION]
(
[OPERATION_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OPERATION_NAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPT_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_OPERATION] ADD CONSTRAINT [PK_EWIP_OPERATION] PRIMARY KEY CLUSTERED ([OPERATION_ID], [DEPT_CODE]) ON [PRIMARY]
GO
