CREATE TABLE [dbo].[EWIP_SPAREPART_TYPE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[CODE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_SPAREPART_TYPE] ADD CONSTRAINT [PK_EWIP_SPAREPART_TYPE] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
