CREATE TABLE [dbo].[EWIP_INVENTORY_SHEET]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[SHEET_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DATE_START] [date] NULL,
[DATE_END] [date] NULL,
[DEPT_CODE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STOCK_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_CREATE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_UPDATE] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_UPDATE] [date] NULL,
[TITLE] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INVENTORY_SHEET_MONTH] [date] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_INVENTORY_SHEET] ADD CONSTRAINT [PK_EWIP_INVENTORY_SHEET] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
