CREATE TABLE [dbo].[ESYSMSTMEU]
(
[PLANT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEPARTMENT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MENUSEQ] [int] NOT NULL,
[UPRSEQ] [int] NULL,
[MENUNAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FORM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMGIDX] [int] NULL,
[DISPSEQ] [int] NULL,
[DISPFLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ESYSMSTMEU_DISPLAG] DEFAULT ('Y'),
[USEFLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ESYSMSTMEU_USEFLAG] DEFAULT ('Y'),
[FORM_GUBUN] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MASTER_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMARKS] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMAGE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATE_TIME] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CREATE_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPDATE_TIME] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPDATE_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESYSMSTMEU] ADD CONSTRAINT [PK_ESYSMSTMEU] PRIMARY KEY CLUSTERED ([PLANT], [DEPARTMENT], [MENUSEQ]) ON [PRIMARY]
GO
