CREATE TABLE [dbo].[SPAREPART_CODE_ENCRIPT]
(
[SPARE_PART_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ENCRIPT_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPT_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SPAREPART_CODE_ENCRIPT] ADD CONSTRAINT [PK_SPAREPART_CODE_ENCRIPT] PRIMARY KEY CLUSTERED ([SPARE_PART_CODE], [DEPT_CODE]) ON [PRIMARY]
GO
