CREATE TABLE [dbo].[ESYSMSTDEPT]
(
[CODE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEPARTMENT] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESYSMSTDEPT] ADD CONSTRAINT [PK_ESYSMSTDEPT] PRIMARY KEY CLUSTERED ([CODE]) ON [PRIMARY]
GO
