CREATE TABLE [dbo].[EWIP_MRP]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[SPAREPART_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[QUANTITY_NEED_BUY] [float] NOT NULL,
[UNIT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STATUS] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MRP_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPT_CODE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DATE_NEED_BUY] [date] NULL,
[DATE_NEED_FINISH] [date] NULL,
[DATE_END_ACTUAL] [date] NULL,
[USER_UPDATE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_UPDATE] [date] NULL,
[OFF_NOTI] [bit] NULL,
[DATE_NEED_REQUIRED] [date] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_MRP] ADD CONSTRAINT [PK_EWIP_MRP] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
