CREATE TABLE [dbo].[EWIP_MERGE_SPAREPART_CODE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[SPARE_PART_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CODE_MERGED] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPT_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_CREATE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_CREATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_MERGE_SPAREPART_CODE] ADD CONSTRAINT [PK_EWIP_MERGE_SPAREPART_CODE] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
