CREATE TABLE [dbo].[EWIP_EQUIPMENT_LOCATION]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[EQ_LOCATION_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FACTORY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_EQUIPMENT_LOCATION] ADD CONSTRAINT [PK_EWIP_EQUIPMENT_LOCATION] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
