CREATE TABLE [dbo].[EWIP_ORDER_PR]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[PO_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PR_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATUS] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_NEED_FINISH] [date] NULL,
[DATE_END_ACTUAL] [date] NULL,
[DATE_CREATE] [date] NULL,
[DATE_UPDATE] [date] NULL,
[USER_CREATE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_UPDATE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPT_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PO_ID_TEMP] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_ORDER_PR] ADD CONSTRAINT [PK_EWIP_ORDER_PR] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
