CREATE TABLE [dbo].[EWIP_STOCK]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[CODE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPT_CODE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MANAGERMENT_EMAIL1] [nvarchar] (320) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MANAGERMENT_EMAIL2] [nvarchar] (320) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_STOCK] ADD CONSTRAINT [PK_EWIP_STOCK] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
