CREATE TABLE [dbo].[EWIP_SETUP_MINSTOCK]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[SPARE_PART_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UNIT_CODE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MIN_STOCK] [float] NOT NULL,
[STOCK_CODE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEPT_CODE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RATE_ALARM] [float] NULL,
[DATE_UPDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_SETUP_MINSTOCK] ADD CONSTRAINT [PK_EWIP_SETUP_MINSTOCK] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
