CREATE TABLE [dbo].[EWIP_UNITS]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[CODE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_UNITS] ADD CONSTRAINT [PK_EWIP_UNITS] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
