CREATE TABLE [dbo].[EWIP_INVENTORY_QTY_VALUE_BY_DAY]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[SPARE_PART_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPT_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STOCK_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE] [date] NULL,
[IN_VALUES_VN] [float] NULL,
[OUT_VALUES_VN] [float] NULL,
[INVENTORY_VALUES_VN] [float] NULL,
[IN_VALUES_US] [float] NULL,
[OUT_VALUES_US] [float] NULL,
[INVENTORY_VALUES_US] [float] NULL,
[QUANTITY_IN] [float] NULL,
[QUANTITY_OUT] [float] NULL,
[QUANTITY_INVENTORY] [float] NULL,
[QTY_INVENTORY_INCLUDE] [float] NULL,
[SYS_TIME] [datetime] NULL,
[UNIT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WEEK] [int] NULL,
[QUARTER] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_INVENTORY_QTY_VALUE_BY_DAY] ADD CONSTRAINT [PK_EWIP_INVENTORY_QTY_VALUE_BY_DAY] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
