CREATE TABLE [dbo].[EWIP_EQUIPMENT_TYPE]
(
[CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_EQUIPMENT_TYPE] ADD CONSTRAINT [PK_EWIP_EQUIPMENT_TYPE] PRIMARY KEY CLUSTERED ([CODE]) ON [PRIMARY]
GO
