CREATE TABLE [dbo].[EWIP_FILE_TEMP]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[Name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ContenType] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Data] [varbinary] (max) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_FILE_TEMP] ADD CONSTRAINT [PK_EWIP_FILE_TEMP] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
