CREATE TABLE [dbo].[EWIP_EQUIPMENT_MAINTAIN]
(
[MAINTAIN_ID] [int] NOT NULL IDENTITY(1, 1),
[EQUIPMENT_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SPARE_PART_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SERIAL_PRE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_MAINTAIN] [datetime] NULL,
[MONTH_MAINTAIN] [int] NULL,
[YEAR_MAINTAIN] [int] NULL,
[WEEK] [int] NULL,
[QUARTER] [int] NULL,
[DATE_SUCCESS] [datetime] NULL,
[TIME_MAINTAIN] [int] NULL,
[CAUSE_MAINTAIN] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_MAINTAIN] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMAGE_ERROR] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONDITION_PRE] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_IN_PRE] [date] NULL,
[SERIAL_AFTER] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONDITION_AFTER] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_IN_AFTER] [date] NULL,
[USER_UPDATE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYS_TIME] [datetime] NULL,
[DEPT_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GANTRY_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEGMENT_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_EQUIPMENT_MAINTAIN] ADD CONSTRAINT [PK_EWIP_EQUIPMENT_MAINTAIN] PRIMARY KEY CLUSTERED ([MAINTAIN_ID]) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', N'NGUYEN NHAN', 'SCHEMA', N'dbo', 'TABLE', N'EWIP_EQUIPMENT_MAINTAIN', 'COLUMN', N'CAUSE_MAINTAIN'
GO
EXEC sp_addextendedproperty N'MS_Description', N'THOI GIAN CAN DE SUA CHUA', 'SCHEMA', N'dbo', 'TABLE', N'EWIP_EQUIPMENT_MAINTAIN', 'COLUMN', N'TIME_MAINTAIN'
GO
