CREATE TABLE [dbo].[ESYSM_CONTROLS_ROL]
(
[PLANT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEPARTMENT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USERROLE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MENU_SEQ] [int] NOT NULL,
[CONTROL_NAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CONTROL_TEXT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USE_FLAG] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPDATE_USER] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPDATE_TIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESYSM_CONTROLS_ROL] ADD CONSTRAINT [PK_ESYSM_CONTROLS_ROL] PRIMARY KEY CLUSTERED ([PLANT], [DEPARTMENT], [USERROLE], [MENU_SEQ], [CONTROL_NAME]) ON [PRIMARY]
GO
