CREATE TABLE [dbo].[EWIP_GL_ACCOUNT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[GL_ACCOUNT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SHORT_TEXT_VN] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHORT_TEXT_KR] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_GL_ACCOUNT] ADD CONSTRAINT [PK_EWIP_GL_ACCOUNT] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
