CREATE TABLE [dbo].[EWIP_EXCHANGE_RATE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[VALID_TIME] [date] NOT NULL,
[FROM] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TO] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RATE] [float] NOT NULL,
[UPDATED_AT] [date] NULL,
[CREATED_AT] [date] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_EXCHANGE_RATE] ADD CONSTRAINT [PK_EWIP_EXCHANGE_RATE] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
