CREATE TABLE [dbo].[EWIP_EQUIPMENT_LOCATION_RELATION]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[EQUIPMENT_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EQ_LOCATION_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEPT_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUB_LOCATION] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_EQUIPMENT_LOCATION_RELATION] ADD CONSTRAINT [PK_EWIP_EQUIPMENT_LOCATION_RELATION] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
