CREATE TABLE [dbo].[EWIP_STATUS_PUR]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NAME_KR] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_STATUS_PUR] ADD CONSTRAINT [PK_EWIP_STATUS_PUR] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
