CREATE TABLE [dbo].[ESYSMSTROL]
(
[PLANT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEPARTMENT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USERROLE] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USERROLE_NAME] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USEFLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ESYSMSTROL_USEFLAG] DEFAULT ('Y'),
[REMARKS] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATE_TIME] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CREATE_USER] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPDATE_TIME] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPDATE_USER] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESYSMSTROL] ADD CONSTRAINT [PK_ESYSMSTROL] PRIMARY KEY CLUSTERED ([PLANT], [DEPARTMENT], [USERROLE]) ON [PRIMARY]
GO
