CREATE TABLE [dbo].[EWIP_SPAREPART_DOCUMENT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEPT_CODE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NAME] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTENT_TYPE] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATA] [varbinary] (max) NULL,
[SYS_TIME] [datetime] NULL,
[USER_UPLOAD] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IS_EQUIPMENT] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_SPAREPART_DOCUMENT] ADD CONSTRAINT [PK_EWIP_SPAREPART_DOCUMENT] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
