CREATE TABLE [dbo].[EWIP_INVENTORY_SHEET_DETAIL]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[SPARE_PART_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOCATION] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QUANTITY] [float] NULL,
[UNIT] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHEET_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEPT_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STOCK_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QUANTITY_REAL] [float] NULL,
[DIFF] [float] NULL,
[IS_CHECK] [bit] NULL,
[CONDITION_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIME_IN] [date] NULL,
[EXPIRED_DATE] [date] NULL,
[PO_NO] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_INVENTORY_SHEET_DETAIL] ADD CONSTRAINT [PK_EWIP_INVENTORY_SHEET_DETAIL] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
