CREATE TABLE [dbo].[ESYSLOGLGN]
(
[PLANT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEPARTMENT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USER_ID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[HIST_SEQ] [int] NOT NULL,
[ACCESS_TIME] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACCESS_IP] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCESS_PC] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESYSLOGLGN] ADD CONSTRAINT [PK_ESYSLOGLGN] PRIMARY KEY CLUSTERED ([PLANT], [DEPARTMENT], [USER_ID], [HIST_SEQ]) ON [PRIMARY]
GO
