CREATE TABLE [dbo].[EWIP_INVENTORY_VALUES_BY_TIME]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[SPARE_PART_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPT_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STOCK_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE] [date] NULL,
[MONTH] [int] NULL,
[YEAR] [int] NULL,
[IN_VALUES_VN] [float] NULL,
[OUT_VALUES_VN] [float] NULL,
[INVENTORY_VALUES_VN] [float] NULL,
[IN_VALUES_US] [float] NULL,
[OUT_VALUES_US] [float] NULL,
[INVENTORY_VALUES_US] [float] NULL,
[SYS_DATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_INVENTORY_VALUES_BY_TIME] ADD CONSTRAINT [PK_EWIP_INVENTORY_VALUES_BY_TIME] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
