CREATE TABLE [dbo].[EWIP_SAP_PO]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[PO_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SAP_PO_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENDOR] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_SYS] [datetime] NULL,
[USER_UPDATE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_SAP_PO] ADD CONSTRAINT [PK_EWIP_SAP_PO] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
