CREATE TABLE [dbo].[ESYSLOGFORM]
(
[PLANT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USER_ID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[HIST_SEQ] [int] NOT NULL,
[FORM_CODE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEPARTMENT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ACCESS_TIME] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESYSLOGFORM] ADD CONSTRAINT [PK_ESYSLOGFORM] PRIMARY KEY CLUSTERED ([PLANT], [USER_ID], [HIST_SEQ], [FORM_CODE], [DEPARTMENT]) ON [PRIMARY]
GO
