CREATE TABLE [dbo].[ESYSMSTURO]
(
[PLANT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEPARTMENT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USER_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ITEM_NO] [int] NOT NULL,
[USERROLE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATE_TIME] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATE_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPDATE_TIME] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPDATE_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESYSMSTURO] ADD CONSTRAINT [PK_ESYSMSTURO] PRIMARY KEY CLUSTERED ([PLANT], [DEPARTMENT], [USER_ID], [ITEM_NO]) ON [PRIMARY]
GO
