CREATE TABLE [dbo].[ESYSMSTUSR]
(
[PLANT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEPARTMENT] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USER_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PASSWORD] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USER_NAME] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHONE_NUM] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAIL] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USEFLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ESYSMSTUSR_USEFLAG] DEFAULT ('Y'),
[ADDRESS] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMARKS] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATE_TIME] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CREATE_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UPDATE_TIME] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPDATE_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MASTER_FLAG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESYSMSTUSR] ADD CONSTRAINT [PK_ESYSMSTUSR] PRIMARY KEY CLUSTERED ([PLANT], [DEPARTMENT], [USER_ID]) ON [PRIMARY]
GO
