CREATE TABLE [dbo].[EWIP_PURCHASE_REQUEST]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[DATE_CREATE] [date] NULL,
[PR_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PR_STATUS] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MRP_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOTAL_VALUE] [float] NULL,
[DATE_NEED_FINISH] [date] NULL,
[DATE_END_ACTUAL] [date] NULL,
[DEPT_CODE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PURPOSE_OF_BUYING] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_CREATE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_UPDATE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_UPDATE] [date] NULL,
[TOTAL_VALUE_US] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_PURCHASE_REQUEST] ADD CONSTRAINT [PK_EWIP_PURCHASE_REQUEST] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
