CREATE TABLE [dbo].[ESYSMSTMRO]
(
[PLANT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DEPARTMENT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USERROLE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MENUSEQ] [int] NOT NULL,
[FORMROLE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USEFLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_ESYSMSTMRO_USEFLAG] DEFAULT ('Y'),
[CREATE_TIME] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPDATE_TIME] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATE_USER] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESYSMSTMRO] ADD CONSTRAINT [PK_ESYSMSTMRO] PRIMARY KEY CLUSTERED ([PLANT], [DEPARTMENT], [USERROLE], [MENUSEQ]) ON [PRIMARY]
GO
