CREATE TABLE [dbo].[EWIP_LABEL]
(
[CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LABEL] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESC] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_LABEL] ADD CONSTRAINT [PK_EWIP_LABEL] PRIMARY KEY CLUSTERED ([CODE]) ON [PRIMARY]
GO
