CREATE TABLE [dbo].[EWIP_ORDER]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[PO_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_ORERED] [datetime] NULL,
[DATE_CREATE] [datetime] NULL,
[STATUS] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPDATED_DATE] [datetime] NULL,
[TITLE] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_ACTUAL_END] [date] NULL,
[DATE_NEED_FINISH] [date] NULL,
[PO_ID_TEMP] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_ORDER] ADD CONSTRAINT [PK_EWIP_ORDER] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', N'NULL : CHUA ORDER ,1: ORDERED 0: HUY ORDER', 'SCHEMA', N'dbo', 'TABLE', N'EWIP_ORDER', 'COLUMN', N'STATUS'
GO
