CREATE TABLE [dbo].[EWIP_EQUIPMENT_BOM]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[EQUIPMENT_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPARE_PART_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEP_CODE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EWIP_EQUIPMENT_BOM] ADD CONSTRAINT [PK_EWIP_EQUIPMENT_BOM] PRIMARY KEY CLUSTERED ([ID]) ON [PRIMARY]
GO
